### PR TITLE
chore(*): removing support for Rinkeby!

### PR DESCRIPTION
**Pull request by julien51**
It is time to remove support for Rinkeby now that the network has been deprecated...
This PR removes it in many places.

### CODE REVIEW

**Comment by julien51** [comment]
Also removed from the docs: https://github.com/unlock-protocol/docs/pull/173

**Comment by kalidiagne** [comment]
> It is time to remove support for Rinkeby now that the network has been deprecated... This PR removes it in many places.

I see we have a lot of `rinkeby` ref inside `docker` folder, we need to remove those as well? 
for example `LOCKSMITH_UNLOCK_CONTRACT_ADDRESS`

**Review by searchableguy — APPROVED** [review]

**Comment by julien51** [comment]
> I see we have a lot of rinkeby ref inside docker folder, we need to remove those as well?

Let me look

**Comment by searchableguy** [comment]
Those variables mentioning rinkeby are not used anywhere as far I know. 

So good to clean up.

**Comment by searchableguy** [comment]
not the files :p 

The rinkeby.locksmith and other related variables.

**Pull request merged**
