### PR TITLE
Replacing the code snippet with the app store

### PR DESCRIPTION
**Pull request by julien51**
# Description

Since we do not have a single code snippet anymore, we cannot show one.
However, we now have a few apps which we can point people who have created a lock to.

This PR has probably a bit too many things, but I am pushing it as is and I'll slice and dice a few things from there.

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [X] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Oh look! A link to Etherscan and the integrations!
image

And the integrations look really cool:

image

**Comment by cnasc** [comment]
Looks great! I'd definitely say getting the icons and such in a separate PR would make it easier to review

**Comment by julien51** [comment]
yes, on it!

**Comment by julien51** [comment]
ok, PTAL @cnasc

**Pull request merged**
