### PR TITLE
Fix package-lock.json

### PR DESCRIPTION
**Pull request by cnasc**
# Description

Somehow we ended up with inconsistency between `package.json` and `package-lock.json` all throughout the repo. As a result, `npm ci` would not get the correct dependencies required to run the app. This PR fixes that by updating all the `package-lock.json`s.
# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cnasc** [comment]
These package-locks ended up removing necessary packages from locksmith. I think we're blocked on this until we figure out what's going on. Until then, the workaround is to just use `npm install` and not commit any package-locks.

**Comment by julien51** [comment]
Where are we on this front @cnasc ?

**Comment by cnasc** [comment]
I am not 100% sure on how to proceed with this.

The current state is as follows:

- Running `npm ci` doesn't produce a repository that works in development (though obviously it does work in CI/Production)
- Running `npm install` produces a repository that allows you to run the dev build, but which seems to produce a different dependency tree than what we strictly expect to find, and which also modifies the `package-locks` in a way that should not be merged.

**Comment by cellog** [comment]
A haiku to suggest a fix:


Off in the distance 
A single crow cries and caws
Let's use yarn for this

**Comment by julien51** [comment]
>  * Running `npm ci` doesn't produce a repository that works in development (though obviously it does work in CI/Production)

I just did a `npm run nuke` locally and then `npm ci` and I see no issue?

Could you tell us more about what is non functional on your end?

**Comment by cnasc** [comment]
View a recording of the example session [here](https://asciinema.org/a/OVEsAx22HnxorzAU7kDf07RV7)

After a fresh clone and `npm ci`, running `npm run dev` gives me:
```
> unlock-app@0.1.0 dev /Users/christoph/projects/unlock/unlock-app
> npm run build-paywall && npm run setup-dev && npm run set-link && nodemon src/server.js


> unlock-app@0.1.0 build-paywall /Users/christoph/projects/unlock/unlock-app
> cross-env NODE_ENV=production rollup -c rollup.paywall.config.js -o ./src/static/paywall.min.js

sh: cross-env: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! unlock-app@0.1.0 build-paywall: `cross-env NODE_ENV=production rollup -c rollup.paywall.config.js -o ./src/static/paywall.min.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the unlock-app@0.1.0 build-paywall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christoph/.npm/_logs/2019-02-28T16_36_04_536Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unlock-app@0.1.0 dev: `npm run build-paywall && npm run setup-dev && npm run set-link && nodemon src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unlock-app@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christoph/.npm/_logs/2019-02-28T16_36_04_580Z-debug.log
```

`npm run test` produces:
```
> unlock-app@0.1.0 test /Users/christoph/projects/unlock/unlock-app
> cross-env UNLOCK_ENV=test jest --env=jsdom

sh: cross-env: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! unlock-app@0.1.0 test: `cross-env UNLOCK_ENV=test jest --env=jsdom`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the unlock-app@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christoph/.npm/_logs/2019-02-28T16_35_59_653Z-debug.log
```

Running `npm install` allows me to run our scripts without issue, but it updates the package configuration in what seems like an erroneous way.

**Comment by julien51** [comment]
There is a bug at second 51. What does it say?

**Comment by julien51** [comment]
so @cnasc that suspense is killing me. What is going on at second 51? 👽

**Comment by cnasc** [comment]
Completely forgot to look into this today! I'll try tomorrow--I want to see if I can reproduce on a different machine.

**Comment by cnasc** [comment]
I have confirmed that this issue also occurs on my Linux box. `postinstall.sh` spits out a traceback and then a bunch of `npm` usage-info outputs (because the script tries to run `npm` commands that don't work?):

```
> unlock@1.0.0 postinstall /home/cjn/code/unlock
> ./scripts/postinstall.sh

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Usage: npm <command>
[editor's note: truncated a number of npm usage outputs]
```

I suppose the issue is [here](https://github.com/unlock-protocol/unlock/blob/837d39c18c757bd1bdb4bd8b67edec220478b1df/scripts/postinstall.sh#L8) in `postinstall.sh`. Are we passing a bad path somewhere?

**Comment by julien51** [comment]
hooo, maybe this python command is not always working as epxected?
Basically the goal here is to know which of `ci` or `install` was run to run the exact command in the sub-directories.

**Pull request closed without merging**
