### PR TITLE
fix(unlock-app): looking up ens names from addresses (#13090)

### LINKED ISSUE #13090: ENS reverse resolution
We show address in _many_ places inside of the dashboard.
Let's add support for ENS reverse resolution (from an address, show the ENS) and let's apply that in every place where we show addresses.

### PR DESCRIPTION
**Pull request by teawaterwire**
# Description

Fixing the reverse lookup of ENS names (from an Ethereum address). 

image

image

image

# Issues

Fixes #13090

### CODE REVIEW

**Review by julien51 — APPROVED** [review]
so ENS only exists on ethereum mainnet for now... so I think we should ignore the network that the user is connected to and just use `1` for lookups?

**Comment by teawaterwire** [comment]
> Ho wow that was quick :) Can you please check all the places were we display addresses and see if we can show the ENS ( I am thinking about the lock settings with lock managers, the members UI... etc)

i replaced it where `useEns` was used (see screenshots)

> so ENS only exists on ethereum mainnet for now... so I think we should ignore the network that the user is connected to and just use 1 for lookups?

if we use `1` then it doesn't work on Goerli

**Comment by julien51** [comment]
> if we use 1 then it doesn't work on Goerli

Well that's the bug :) We need to make sure can do the reverse resolution anywhere on the app, whatever network the user is connected to :)

**Comment by teawaterwire** [comment]
ok now resolving always on mainnet: 
image

**Review by julien51 — APPROVED** [review]

**Review by julien51 — APPROVED** [review]

**Pull request merged**
