### PR TITLE
Using the useProvider hook on components

### PR DESCRIPTION
**Pull request by julien51**
# Description

Components are now using the useProvider hook!
After this we can clean up the handling of provider from inside the middlewares.

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cnasc** [comment]
Do we know what caused the storyshots changes?

**Comment by julien51** [comment]
Yes, the 2 snapshots which have changed are:

* Storyshots DashboardContent dashboard, no user account 1
image

* Storyshots DashboardContent the dashboard, waiting for wallet 1
image

In both cases, we were showing nothing before that...

**Pull request merged**
