### PR TITLE
Removed Earning

### PR DESCRIPTION
**Pull request by smombartz**
# Description
removed earning column from dashboard header and cleaned up unused header buttons (etherscan, upload, export) since we're not using them.

image

image

### CODE REVIEW

**Comment by smombartz** [comment]
having issues with git pushing a cleanup change and updated test...

**Comment by julien51** [comment]
do you mind also posting a screenshot from mobile just to make sure things look good?

**Comment by smombartz** [comment]
@benwerd mobile shot added

**Comment by cellog** [comment]
unrelated issue - the column headers are wrapping, we probably need a completely different look for mobile, one that does not have column headers at all, but has small locks that when clicked expand down into vertical form stuff

**Comment by smombartz** [comment]
@cellog they are actually not wrapping but stacked :)

image

**Pull request merged**
