### PR TITLE
feat(tests): add logic for integration tests

### PR DESCRIPTION
**Pull request by clemsos**
# Description

This PR updates the way we deploy Unlock's infrastructure to make sure we can run integration tests through it

NB: the new eth-node was split into #9648 so should review and merge that one first, then rebase it

~~NB: This needs to be rebased once #9462 is merged~~

 

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by clemsos** [comment]
The PR is passing without integration tests so far, so just the docker images and scripts to run everything. I will add the actual tests to another PR as this one is already big enough...

**Review by julien51 — APPROVED** [review]
This looks good but please let's add a README on how this works and more importantly, how to add new integration tests!

**Comment by julien51** [comment]
@clemsos Do you think all tests need to run hardhat? I wonder if this isn't going to make our life harder for e2e front-end tests?

**Comment by clemsos** [comment]
> @clemsos Do you think all tests need to run hardhat? I wonder if this isn't going to make our life harder for e2e front-end tests?

the frontend e2e does not need to run hardhat but the subgraph does. We can have different testing logic in this repo with two different yarn tasks

**Pull request merged**
