### PR TITLE
Updates the code coverage path ignore patterns to exclude stories

### PR DESCRIPTION
**Pull request by akeem**
# Description

We noticed that these files where being considered in the code coverage calculation. As this metric is currently push blocking, it is reasonable that it correctly reflect the intended items under measurement.

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Thanks, would it be worth quickly adding all of the stories in other applications as well?

**Comment by julien51** [comment]
Also, as part of this PR let's update the `coverageThreshold` once this has run once?

**Comment by akeem** [comment]
> Also, as part of this PR let's update the `coverageThreshold` once this has run once?

I've updated the branch to reflect the thresholds as they stand now.  TBH it might end up blocking a bit of code but we'll see how that shakes out

**Comment by akeem** [comment]
> Thanks, would it be worth quickly adding all of the stories in other applications as well?

I think this will serve as a good template for those looking to make similar changes in other projects

**Comment by cnasc** [comment]
`Jest: Uncovered count for statements (170)exceeds global threshold (168)` close!

**Pull request merged**
