### PR TITLE
add eth-gas-reporter

### PR DESCRIPTION
**Pull request by metjm**
# Description
Adds eth-gas-reporter as dev dependency, and added it to the truffle config.It will be run when `truffle test` is executed.

# Issues
#4096 

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by NickCuso** [comment]
The report looks great locally.  Will investigate the CI fail..

**Comment by NickCuso** [comment]
@benwerd Could you help with cla-bot?  Both accounts have already signed CLAssistant

**Comment by julien51** [comment]
Hey @NickCuso! @metjm  is not in the list? I'll add them.

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/pull/4115

**Pull request merged**
