### PR TITLE
add new ACCOUNT_REGEXP constant

### PR DESCRIPTION
**Pull request by cellog**
# Description

In preparation for #1312 (and along the path to #1287) we need to be able to validate incoming account information. This extracts just the account portion of `LOCK_PATH_NAME_REGEXP` into a new regexp `ACCOUNT_REGEXP`

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

**Comment by julien51** [comment]
wow that was fast ;)

**Comment by cellog** [comment]
fast like tiger

**Comment by cellog** [comment]
On second thought, we can still use this information to provide a better user experience, go ahead and review

**Comment by cellog** [comment]
re-closing, as I learn more about the problem, I think we can ditch this portion.

**Pull request closed without merging**
