### PR TITLE
Replacing unlock-app's web3Service with the npm module version

### PR DESCRIPTION
**Pull request by julien51**
This replaces the use of the web3Service inside unlock-app with the version from the npm module.

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
I have no idea what is going on in CI:

```
npm ERR! path /home/unlock/unlock-app/node_modules/unlock
npm ERR! code EEXIST
npm ERR! errno -17
npm ERR! syscall mkdir
npm ERR! EEXIST: file already exists, mkdir '/home/unlock/unlock-app/node_modules/unlock'
npm ERR! File exists: /home/unlock/unlock-app/node_modules/unlock
npm ERR! Move it away, and try again.
```

**Comment by julien51** [comment]
Annoying: this is an npm bug: https://npm.community/t/npm-ci-fails-with-transitive-local-packages/4059

**Comment by julien51** [comment]
This leaves us with an option to publish the npm module. I am not a huge fan of that idea since our module is far from being usable independently, but I think that is the only way for now.

**Comment by cnasc** [comment]
That's annoying, it might slow us down a bit too :/

**Pull request merged**
