### PR TITLE
Add PublicLock to zos project

### LINKED ISSUE #5627: Use ZOS to deploy PublicLock template
In the `project.json` file, we currently have added only 2 contracts:
```
"contracts": {
    "Unlock": "Unlock",
    "UnlockDiscountToken": "UnlockDiscountToken"
  },
```
I believe adding a third contract, `PublicLock` to the project here will both simplify deployment (zos push will now deploy our PublicLock template as well) as well as make tracking the deployed address easier( as the PublicLock template's deployed address will be recorded in the network file, eg: `zos.mainnet.json`).

### PR DESCRIPTION
**Pull request by nfurfaro**
# Description
Adding a third contract, PublicLock to the project here will both simplify deployment (zos push will now deploy our PublicLock template as well) as well as make tracking the deployed address easier( as the PublicLock template's deployed address will be recorded in the network file, eg: zos.mainnet.json).

# Issues

Fixes #5627 
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by nfurfaro** [comment]
Hmm. Trying to run the smart contract tests results in this error:
```
Error: One or more contracts have validation errors. Please review the items listed above and fix them, or run this command again with the --force option.
```

**Comment by julien51** [comment]
Do you want to try to rebase here?

**Comment by nfurfaro** [comment]
I will try shortly, at the dentist with my daughter.

**Comment by julien51** [comment]
😺

**Comment by nfurfaro** [comment]
Update: No luck after the rebase. I've asked a question in the oz forum here: https://forum.openzeppelin.com/t/trouble-with-testing-when-a-contract-has-a-selfdestruct-operation/2113

Looks like I got a response to look into.

cc @julien51

**Comment by julien51** [comment]
Oh, yes, I think it's now redundant. I'd much rather deploy everything thru our own library TBH  as it makes things much easier to script/test/control.

**Pull request closed without merging**
