### PR TITLE
Sets up a fall through for signing of ticket information

### PR DESCRIPTION
**Pull request by akeem**
# Description

Our use of HTTPProvider has presented us with a scenario that does quite reflect what will be deployed and user will encounter.

This gives us a few options to be used when preparing QR codes.

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cellog** [comment]
for references, #2986 is the PR I am referring to that should precede this one

**Comment by cellog** [comment]
The code will look almost the same in `walletService`:

```js
```

**Comment by akeem** [comment]
@cellog sounds good!

**Comment by julien51** [comment]
@cellog we need this out ASAP for the tickets apps. Any clarification on why this cannot be merged?

**Comment by cellog** [comment]
now it can, but it needs to be refactored to use ethers. Code is in a comment above

**Comment by cellog** [comment]
this can be closed, the new signature stuff is in master

**Comment by julien51** [comment]
@akeem Ok to close?

**Pull request closed without merging**
