### PR TITLE
renaming index.js into home.js

### PR DESCRIPTION
**Pull request by julien51**
We should always use the component name in the filename for that code of that component.
We should only use `index.js` for exports.

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [X] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Hum. It looks like we're tripping on the next.js carpet once more here. I'll revisit after https://github.com/unlock-protocol/unlock/pull/2147

**Comment by cellog** [comment]
hey the integration tests worked! They show the rename failed. 🌮 to Akeem :)

**Comment by julien51** [comment]
Yup! thanks!

**Comment by julien51** [comment]
Thanks @greg! All fixed, PTAL!

**Pull request merged**
