### PR TITLE
Router is now connected to Redux

### LINKED ISSUE #1694: Router in redux does not update when you change pages
**Describe the bug**
The router in redux never updates after it is first set. So if you just load the root url, `pathname` will be `/`. Visiting any page after that, it stays on `/`.

**To Reproduce**
1. Load the app
2. Take note of the router state
3. Navigate elsewhere without actually reloading the page (that is, click a link, don't modify the url and hit enter)
4. See that router state has not changed

**Expected behavior**
Router information in the state will update to reflect page navigation.

**Screenshots**
My Redux state on the homepage
image

My Redux state after having moved from the homepage to the dashboard via the green button on the homepage
image

### PR DESCRIPTION
**Pull request by cnasc**
# Description

This PR connects Redux with the Next router. Previously, there was a router object in the state that did not track movement between pages--this is because we used `connected-react-router` despite our usage of Next router. I changed the dependency to `connected-next-router`, which handles updating the router state automagically for anything wrapped in a `next/Link` component.

Additionally, changes were made to allow the initial state of the app to include the page you directly queried.

# Issues

Fixes #1694 
Refs #1688 #1805 

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cnasc** [comment]
So it's:

1. First PR adds `connected-next-router` and hooks it up
2. Second PR removes `connected-react-router`?

**Comment by cellog** [comment]
> So it's:
> 
> 1. First PR adds `connected-next-router` and hooks it up
> 2. Second PR removes `connected-react-router`?

Yep, ping Julien if you want the rationale from the source, it has to do with separating config changes from code changes, in case we need to revert, it's easier (in case future commits depend on that config change)

**Comment by cnasc** [comment]
Yup, makes total sense just wanted to make sure I split it correctly the first time and not have to redo it!

**Comment by cnasc** [comment]
This is ready for another look--I'll follow up shortly with a PR to remove `connected-react-router`

**Pull request merged**
