### PR TITLE
Allow walletService to properly connect to UnlockProvider

### LINKED ISSUE #3611: Special case UnlockProvider in walletService
`UnlockProvider` has an API that matches the method call syntax used by the `ethers` provider wrapper. Unfortunately, `UnlockProvider` is itself wrapped by `ethers`, so it currently receives params in the JSON-RPC style, which causes it to fail. We need to add a line in the `connect()` method of `walletService` which will avoid wrapping `UnlockProvider`.

See #3609

### PR DESCRIPTION
**Pull request by cnasc**
# Description

Fixing the issue raised yesterday around the API boundary between `walletService` and `UnlockProvider`.

# Issues

Fixes #3611

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cnasc** [comment]
The ad remover paywall should not be using UnlockProvider, and should probably have tests that help us identify breakage

**Comment by cellog** [comment]
Basically, if you change the signature of `send` to:

```js
  async send({ method, params }, callback) {
```

That then makes it a web3-compatible provider. Unless there is something else I don't see, this would make the changes to walletService unnecessary, you can pass in an unlockProvider and it will just work.

Of course, you'd have to change the send method to something like:

```js
    if (typeof this[method] === 'undefined') {
      // We haven't implemented this method, defer to the fallback provider.
      // TODO: Catch methods we don't want to dispatch and throw an error
      try {
        const result = this.fallbackProvider.send(method, params)
        callback(null, result)
      } catch (e) {
        callback(e)
      }
    } else {
      const { result, error } = this[method](params)
      callback(error, result)
    }
```

**Comment by cellog** [comment]
> The ad remover paywall should not be using UnlockProvider, and should probably have tests that help us identify breakage

then we definitely need to talk, assumptions are not in alignment - the same base code is going to be used for all paywalls

**Comment by cnasc** [comment]
> > The ad remover paywall should not be using UnlockProvider, and should probably have tests that help us identify breakage
> 
> then we definitely need to talk, assumptions are not in alignment - the same base code is going to be used for all paywalls

You're right: here are my assumptions:

- The ad remover paywall does not use `UnlockProvider`, which is not complete enough for any app to use it. 
- We interact with providers through `walletService`

**Comment by cnasc** [comment]
Per discussion with @julien51 and @akeem, including some comments about the future direction of this file to tighten up the abstractions used in here PTAL

**Pull request merged**
