### PR TITLE
feat(unlock-app) - update dashboard links and page content

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
- Update dashboard page with correct components to list locks + header
- Update `/dashboard` links to `/locks`

Screenshot 2022-10-05 at 10 07 22

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by kalidiagne** [comment]
In you blog we have a lot of article that points to `/dashboard`, we can keep it as is or update everything to `/locks` URL.

eg.

`
On Avalanche you can deploy NFT contracts using the [Unlock Dashboard](https://app.unlock-protocol.com/dashboard)
`

Is still fine to call `/locks` the dashboard? can be confusing

**Comment by searchableguy** [comment]
I think it is better to keep the `/dashboard` because many people have linked `/dashboard` outside of our blog and adding a redirect adds extra delay. 

But up to you.

**Comment by julien51** [comment]
@searchableguy I get the point but I tested things on our end and the redirect is really not much compared to the tine used to load the app so I am in favor of doing a redirect to a more explicit `/locks`.

**Comment by julien51** [comment]
LG, but let's also see if we can add a server-side redirect

**Review by julien51 — APPROVED** [review]

**Pull request merged**
