### PR TITLE
adding loading svg and react components

### PR DESCRIPTION
**Pull request by julien51**
This will be displayed when content on the page is being loaded.

Refs #2302

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Note: the react component was generated with/via: `npm run svg-2-components`

**Comment by julien51** [comment]
Hum. This is strange: if I click on "SVG" in the storybooks' list of stories I see this:

image

You can see that the loading icon is visible (black on white, animated)

**Comment by julien51** [comment]
Note that it is exactly like all other svg files...

**Comment by cellog** [comment]
Screen Shot 2019-03-23 at 10 39 20 PM

from https://www.chromaticqa.com/snapshot?appId=5c7d369cd530c00020ea8e0e&id=5c96b5ab298bde0020ccee46

and similarly:

https://www.chromaticqa.com/component?buildNumber=896&specNumber=1&appId=5c7d369cd530c00020ea8e0e&name=SVG&branch=julien-loadingSvg&viewport=1200

I suspect chromatic doesn't like the animation?

**Pull request merged**
