### PR TITLE
feat(unlock-app) - show actions to lock manager

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
Show manage lock page as "`read only`" for non-lock managers:
- Hide edit buttons 
- Hide connect stripe
- Hide enable recurring
- Hide withdraw button

This actions throw error for not lock manager but seeing the buttons is not ideal 

**Page for non-lock manager** 
Screenshot 2022-10-05 at 17 30 47

**Page ock manager** 
Screenshot 2022-10-05 at 17 29 37

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by kalidiagne** [comment]
@julien51  is ok for a non-lock manager to see the balance of the lock?

**Review by searchableguy — APPROVED** [review]
LGTM

I will add some information about the status of current user somewhere though.

Otherwise they might wonder why they can't see the buttons.

**Comment by julien51** [comment]
> @julien51 is ok for a non-lock manager to see the balance of the lock, we can hide it as well?

Of course. That info is on chain anyway...

> I will add some information about the status of current user somewhere though.

Agreed: we should add a message like `You are connected as 0x... and this address is not a manager for this lock. If you want to update details, please connect as as lock manager.`

**Comment by kalidiagne** [comment]
> > @julien51 is ok for a non-lock manager to see the balance of the lock, we can hide it as well?
> 
> Of course. That info is on chain anyway...
> 
> > I will add some information about the status of current user somewhere though.
> 
> Agreed: we should add a message like `You are connected as 0x... and this address is not a manager for this lock. If you want to update details, please connect as as lock manager.`
Added banner non-manager 

**Not manager**
Screenshot 2022-10-05 at 18 44 04

**Manager**
Screenshot 2022-10-05 at 18 44 19

**Comment by julien51** [comment]
LGTM!

**Pull request merged**
