### PR TITLE
Remove unused truffle-contract package.

### PR DESCRIPTION
**Pull request by hardlydifficult**
# Description

Fixes https://github.com/unlock-protocol/unlock/pull/1045 which is requesting we update a package which is not used.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

**Comment by julien51** [comment]
Why the why is Travis not running branch tests anymore :/

**Comment by julien51** [comment]
WAIT, could it be because you are an external contributor?

**Comment by hardlydifficult** [comment]
They run on my branch: https://github.com/hardlydifficult/unlock/runs/50857391

**Comment by julien51** [comment]
Ok that's reassuring. I guess this is fine. I had no idea that Github was doing that! Thanks for this.

**Pull request merged**
