### PR TITLE
fix the flash of content on the paywall

### LINKED ISSUE #2257: Paywall landing page flashes briefly when loading paywall in main window
When loading a lock in the main window, the landing page flashes briefly. This should not happen.

### PR DESCRIPTION
**Pull request by cellog**
# Description

This removes the flash of the landing page when viewing the paywall in a new window. It also improves loading time for the paywall.

It does this by splitting the `home` page into two next pages, `home` and `paywall`. Then, it uses `_server.js` in local dev and `src/static/_redirects` on netlify to control which page is returned. Basically, the `home` page is returned for any URL except `/0x....` which returns the paywall.

Screen Shot 2019-03-22 at 1 22 25 PM
Screen Shot 2019-03-22 at 1 22 16 PM
Screen Shot 2019-03-22 at 1 17 50 PM
Screen Shot 2019-03-22 at 1 17 36 PM
Screen Shot 2019-03-22 at 1 17 20 PM

# Issues

Fixes #2257

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [X] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cellog** [comment]
couldn't get to the deploy preview since circle is down, closing

**Comment by cellog** [comment]
alas, this is not working, I may need some help. See the deploy preview at:

https://5c9543665ce6064d3c3e505a--staging-pawyall-unlock-protocol.netlify.com

**Comment by cnasc** [comment]
Netlify link is broken

**Comment by cellog** [comment]
don't merge still don't have this working on netlify

**Comment by cellog** [comment]
working now!

**Pull request merged**
