### PR TITLE
Merge NetworkConfig(s) type declarations

### LINKED ISSUE #7809: Conflicting NetworkConfig type def
Two different NetworkConfig type defs exists, conflicting on import. 

- in [@unlock-protocol/networks](https://github.com/unlock-protocol/unlock/blob/c2274496b6eec5dac0a46c48e72283515dfc63e8/packages/networks/src/types/index.ts#L1)
- in [@unlock-protocol/types](https://github.com/unlock-protocol/unlock/blob/c2274496b6eec5dac0a46c48e72283515dfc63e8/packages/types/src/types/unlockTypes.ts#L26-L33)

This creates a conflict and make using `unlock-js` in ts impossible.

Types should all move to `@unlock-protocol/types`

### PR DESCRIPTION
**Pull request by clemsos**
# Description

Remove duplicate NetworkConfig type def that were preventing unlock-js from being used w typescript

# Issues

Fixes #7809 
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by clemsos** [comment]
note that this should be published to npm

**Comment by clemsos** [comment]
this is a case where we want to force to run all tests, so maybe we can merge gh actions first (or pull /rebase it here)

**Review by julien51 — APPROVED** [review]

**Comment by julien51** [comment]
Makes sense!

**Comment by clemsos** [comment]
merged #7816 so tests can run properly

**Review by julien51 — APPROVED** [review]

**Pull request merged**
