### PR TITLE
feat(unlock-protocol-com) Redesign

### LINKED ISSUE #8324: New Website review!
We are getting ready to test the new website! Please help us identify issues, gotchas and things we can improve!
Here is how you can help:

1. Open the [Figma design](https://www.figma.com/file/cksSEyuTPGfHfzRdPosxXw/Unlock-x-DeepWork?node-id=6682%3A2948) in one tab.
2.  Open staging site: https://staging.unlock-protocol.com/
3. Report any discrepancy you might see. Some of them are expected (we changed some of the wording...) but please, report _anything_ that _feels_ off.
4. Click on all links and buttons and make sure they point to the "right" thing (expected based on the button or link's anchor).
5. Feel free to navigate the whole site, not just the landing page and apply the same heuristic as above.

Important: please also test on a a mobile device!

To report issues, the easiest is to open a comment below for _all_ of your comments/issues feedback and create a list using the markdown syntax. @searchableguy and I will update/write inline comments to indicate resolution.

Thanks a lot!

Related: https://github.com/unlock-protocol/unlock/issues/8217

PR: https://github.com/unlock-protocol/unlock/pull/8344

### PR DESCRIPTION
**Pull request by julien51**
# Description

Opening the big redesign PR.

Fixes #8324

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
For some reason, we are facing this issue where nextjs build in CI fails but work properly on netlify and local environment. 

Any explanation that comes to mind? @clemsos 

(maybe we can downgrade next, we upgraded it recently)

**Comment by searchableguy** [comment]
I've changed how we use environment variables. We now follow the next recommended way where any environment variable available to the browser is prefixed with NEXT_PUBLIC. I've moved the configuration from runtime nextjs.config.js to the config folder in unlock.ts so modify any values from there. We need to next configuration setup because it's not used.

(The technical reason for this is not to turn off automatic static optimization)

The only variable that needs to be changed is UNLOCK_ENV which should be NEXT_PUBLIC_UNLOCK_ENV for unlock-protocol-com netlify. Just look into the file, I relayed it to clement.

Also I don't have the GA ID so I didn't set it in production config inside `src/config/unlock.ts`

**Comment by searchableguy** [comment]
We didn't add the animation @julien51

**Comment by julien51** [comment]
I know we'll replace in the next iteration.

**Comment by searchableguy** [comment]
The problem is the current webm won't be visible on iOS mobile because apple safari only supports hevc format. @julien51

**Pull request merged**
