### PR TITLE
fix(networks): correct checks for testnets

### PR DESCRIPTION
**Pull request by clemsos**
# Description

This fixes checks for testnets especially (multisig signers, etc)

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/base-sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 is verified
- ✅ Contract PublicLockPrevious at 0xF241F12506fb6Bf1909c6bC176A199166414007a is verified
- ✅ Contract Unlock at 0x259813B665C8f6074391028ef782e27B65840d89 is verified
- ✅ Contract UDTv3 at 0x68a8011d72E6D41bf7CE9dC49De0aeaEBAAC9b39 is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x8c5D54B2CAA4C2D08B0DDF82a1e6D2641779B8EC is verified
- ✅ Unlock source code at 0x259813B665C8f6074391028ef782e27B65840d89 matches packaged UnlockV13
- ✅ PublicLock source code at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig

We have found the following errors :

- ❌ Unexpected policy: 2/3 for 4/3 expected




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_CAPTCHA is missing
- ⚠️ Contract onKeyPurchaseHook_GUILD is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

### packages/networks/src/networks/sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x3E25924b97A275B4004896a1794b671BeCBEEA2C is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x36b34e10295cCE69B652eEB5a8046041074515Da is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract UDTv3 at 0x447B1492C5038203f1927eB2a374F5Fcdc25999d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x34EbEc0AE80A2d078DE5489f0f5cAa4d3aaEA355 is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x639143cbf90F27eA5Ce4b3A7D869d4D7878009A5 is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x0aC1a84AcaB08b630714d59dA74576D7274E68d5 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0x499C854E40Ce4056266822c86D1A326f0FE6491a is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xd0b14797b9D08493392865647384974470202A78 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x323Fd488F101F2F9252ecE9f9fe3e56C48912880 is verified
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig

We have found the following errors :

- ❌ Unlock source code at 0x36b34e10295cCE69B652eEB5a8046041074515Da does not match packaged UnlockV13
- ❌ PublicLock source code at 0x3E25924b97A275B4004896a1794b671BeCBEEA2C does not match packaged PublicLockV14
- ❌ Unexpected policy: 2/3 for 4/3 expected




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/base-sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 is verified
- ✅ Contract PublicLockPrevious at 0xF241F12506fb6Bf1909c6bC176A199166414007a is verified
- ✅ Contract Unlock at 0x259813B665C8f6074391028ef782e27B65840d89 is verified
- ✅ Contract UDTv3 at 0x68a8011d72E6D41bf7CE9dC49De0aeaEBAAC9b39 is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x8c5D54B2CAA4C2D08B0DDF82a1e6D2641779B8EC is verified
- ✅ Unlock source code at 0x259813B665C8f6074391028ef782e27B65840d89 matches packaged UnlockV13
- ✅ PublicLock source code at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_CAPTCHA is missing
- ⚠️ Contract onKeyPurchaseHook_GUILD is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

### packages/networks/src/networks/sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x3E25924b97A275B4004896a1794b671BeCBEEA2C is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x36b34e10295cCE69B652eEB5a8046041074515Da is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract UDTv3 at 0x447B1492C5038203f1927eB2a374F5Fcdc25999d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x34EbEc0AE80A2d078DE5489f0f5cAa4d3aaEA355 is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x639143cbf90F27eA5Ce4b3A7D869d4D7878009A5 is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x0aC1a84AcaB08b630714d59dA74576D7274E68d5 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0x499C854E40Ce4056266822c86D1A326f0FE6491a is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xd0b14797b9D08493392865647384974470202A78 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x323Fd488F101F2F9252ecE9f9fe3e56C48912880 is verified
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig

We have found the following errors :

- ❌ Unlock source code at 0x36b34e10295cCE69B652eEB5a8046041074515Da does not match packaged UnlockV13
- ❌ PublicLock source code at 0x3E25924b97A275B4004896a1794b671BeCBEEA2C does not match packaged PublicLockV14




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/base-sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 is verified
- ✅ Contract PublicLockPrevious at 0xF241F12506fb6Bf1909c6bC176A199166414007a is verified
- ✅ Contract Unlock at 0x259813B665C8f6074391028ef782e27B65840d89 is verified
- ✅ Contract UDTv3 at 0x68a8011d72E6D41bf7CE9dC49De0aeaEBAAC9b39 is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x8c5D54B2CAA4C2D08B0DDF82a1e6D2641779B8EC is verified
- ✅ Unlock source code at 0x259813B665C8f6074391028ef782e27B65840d89 matches packaged UnlockV13
- ✅ PublicLock source code at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_CAPTCHA is missing
- ⚠️ Contract onKeyPurchaseHook_GUILD is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

### packages/networks/src/networks/sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x3E25924b97A275B4004896a1794b671BeCBEEA2C is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x36b34e10295cCE69B652eEB5a8046041074515Da is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract UDTv3 at 0x447B1492C5038203f1927eB2a374F5Fcdc25999d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x34EbEc0AE80A2d078DE5489f0f5cAa4d3aaEA355 is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x639143cbf90F27eA5Ce4b3A7D869d4D7878009A5 is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x0aC1a84AcaB08b630714d59dA74576D7274E68d5 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0x499C854E40Ce4056266822c86D1A326f0FE6491a is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xd0b14797b9D08493392865647384974470202A78 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x323Fd488F101F2F9252ecE9f9fe3e56C48912880 is verified
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig

We have found the following errors :

- ❌ Unlock source code at 0x36b34e10295cCE69B652eEB5a8046041074515Da does not match packaged UnlockV13
- ❌ PublicLock source code at 0x3E25924b97A275B4004896a1794b671BeCBEEA2C does not match packaged PublicLockV14




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by clemsos** [comment]
waiting for sepolia multisig tx to be executed before relaunching checks

**Comment by julien51** [comment]
I just executed the Sepolia transactions!

**Review by julien51 — APPROVED** [review]

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/base-sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 is verified
- ✅ Contract PublicLockPrevious at 0xF241F12506fb6Bf1909c6bC176A199166414007a is verified
- ✅ Contract Unlock at 0x259813B665C8f6074391028ef782e27B65840d89 is verified
- ✅ Contract UDTv3 at 0x68a8011d72E6D41bf7CE9dC49De0aeaEBAAC9b39 is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x8c5D54B2CAA4C2D08B0DDF82a1e6D2641779B8EC is verified
- ✅ Unlock source code at 0x259813B665C8f6074391028ef782e27B65840d89 matches packaged UnlockV13
- ✅ PublicLock source code at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_CAPTCHA is missing
- ⚠️ Contract onKeyPurchaseHook_GUILD is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

### packages/networks/src/networks/sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x36b34e10295cCE69B652eEB5a8046041074515Da is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract UDTv3 at 0x447B1492C5038203f1927eB2a374F5Fcdc25999d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x34EbEc0AE80A2d078DE5489f0f5cAa4d3aaEA355 is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x639143cbf90F27eA5Ce4b3A7D869d4D7878009A5 is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x0aC1a84AcaB08b630714d59dA74576D7274E68d5 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0x499C854E40Ce4056266822c86D1A326f0FE6491a is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xd0b14797b9D08493392865647384974470202A78 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x323Fd488F101F2F9252ecE9f9fe3e56C48912880 is verified
- ✅ Unlock source code at 0x36b34e10295cCE69B652eEB5a8046041074515Da matches packaged UnlockV13
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig

We have found the following errors :

- ❌ Verification failed for PublicLockLatest at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482: Contract source code not verified
- ❌ PublicLock source code at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 does not match packaged PublicLockV14




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/base-sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 is verified
- ✅ Contract PublicLockPrevious at 0xF241F12506fb6Bf1909c6bC176A199166414007a is verified
- ✅ Contract Unlock at 0x259813B665C8f6074391028ef782e27B65840d89 is verified
- ✅ Contract UDTv3 at 0x68a8011d72E6D41bf7CE9dC49De0aeaEBAAC9b39 is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x8c5D54B2CAA4C2D08B0DDF82a1e6D2641779B8EC is verified
- ✅ Unlock source code at 0x259813B665C8f6074391028ef782e27B65840d89 matches packaged UnlockV13
- ✅ PublicLock source code at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_CAPTCHA is missing
- ⚠️ Contract onKeyPurchaseHook_GUILD is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

### packages/networks/src/networks/sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x36b34e10295cCE69B652eEB5a8046041074515Da is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract UDTv3 at 0x447B1492C5038203f1927eB2a374F5Fcdc25999d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x34EbEc0AE80A2d078DE5489f0f5cAa4d3aaEA355 is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x639143cbf90F27eA5Ce4b3A7D869d4D7878009A5 is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x0aC1a84AcaB08b630714d59dA74576D7274E68d5 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0x499C854E40Ce4056266822c86D1A326f0FE6491a is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xd0b14797b9D08493392865647384974470202A78 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x323Fd488F101F2F9252ecE9f9fe3e56C48912880 is verified
- ✅ Unlock source code at 0x36b34e10295cCE69B652eEB5a8046041074515Da matches packaged UnlockV13
- ✅ PublicLock source code at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Pull request merged**
