### PR TITLE
Unplugging the redux store from the app

### PR DESCRIPTION
**Pull request by julien51**
# Description

I think after that I can remove all actions, reducers and finally the dependencies!

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
rebase!

**Comment by julien51** [comment]
Getting a different error every time. There is something strange going on here.

**Comment by cnasc** [comment]
We don't rely on the connected router for navigation in some way, do we?

**Comment by julien51** [comment]
I am not sure. Looking into that.

**Pull request merged**
