### PR TITLE
adding erc1820

### PR DESCRIPTION
**Pull request by julien51**
# Description

This is required by v12 for testing.

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [X] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by NickCuso** [comment]
erc1820 does expect a web3 instance, which i think would make the -js package heavier.  to avoid maybe we should port the code to ethers.js.  it's not much code: https://github.com/0xjac/ERC1820/blob/master/js/deployment.js

**Comment by julien51** [comment]
Dang. what is a `web3` instance exactly? I was indeed hoping to use ethers.js

**Comment by julien51** [comment]
Maybe we can use the `generateDeployTx` function.

**Comment by NickCuso** [comment]
it expects this package https://www.npmjs.com/package/web3

we could use generateDeployTx and then just port the deploy section, but that still adds a couple dependencies.  i'm not sure if that would be significant.  however ethers.js should have the same capabilities already, so it would be redundant it seems

**Comment by julien51** [comment]
I think I got this. `generateDeployTx` yields the stuff we need for `sendTransaction` https://docs.ethers.io/ethers.js/html/api-providers.html#contract-execution

**Comment by NickCuso** [comment]
We could also consider using a proxy to forward web3 apis to ethers.  Something like:
const web3Proxy = {
eth: {
getCode: (address) => {
return provider.getCode(address); // https://docs.ethers.io/ethers.js/html/api-providers.html?highlight=getcode
} 
}
}

**Pull request merged**
