### PR TITLE
chore: Upgrade to node 16

### PR DESCRIPTION
**Pull request by searchableguy**
# Description

Upgrade node version in our dockerfile to node 16. This should apply to all services using the file.

Let's see if it breaks anything.

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
Due to how we detect changes in CI, this won't run all the tests though :/

Is there a way to forcefully run?

**Comment by clemsos** [comment]
Yes there you need to label the PR with run-all-tests then commit sth

**Comment by julien51** [comment]
Also, want to try `14` first?

**Comment by searchableguy** [comment]
Breaking changes introduced by npm 
https://github.com/npm/cli/issues/1935

So we will need another environment variable to be set globally for our scripts to work as is.

**Comment by julien51** [comment]
Assigning to @clemsos for the smart contract tests issues...

**Comment by julien51** [comment]
Team work is dream work!

**Comment by julien51** [comment]
Annoyingly a bunch of styling things were added. It looks like my vscode prettyfying config has changed? Any hint @searchableguy on how to fix this?

**Comment by julien51** [comment]
Also that fixes https://github.com/unlock-protocol/unlock/issues/7510

**Comment by julien51** [comment]
Ok it looks like we have a green build!

**Pull request merged**
