### PR TITLE
Adding Celo Alfajores testnet configuration network values

### PR DESCRIPTION
**Pull request by nestorbonilla**
# Description

I included the Celo Alfajores testnet network configuration file, with most of the data needed to deploy Unlock Protocol on Alfajores. There are only a few fields that need to be completed by the Unlock team:
- unlockAddress
- multisig
- keyManagerAddress
- teamMultisig

I also included three native stablecoins on the tokens attribute.

### CODE REVIEW

**Comment by julien51** [comment]
Thanks @nestorbonilla ! Please send some test tokens to julien51.eth so I can deploy the contracts.

**Comment by nestorbonilla** [comment]
Hi @julien51, sure! Here's the [tx](https://alfajores.celoscan.io/tx/0x8a0e20e6e796611e4099d4666d0498dccb6826a0070b0c33b1e3aceea0e70ed3) of some test tokens sent to the public key mapped to julien51.eth. Thanks!

**Comment by julien51** [comment]
@nestorbonilla I will get started on this shortly! Thanks for your patience!

**Comment by julien51** [comment]
Hey @nestorbonilla I realize this has been stale for a long time. Is there a subgraph for Alfajores?
I will close for now, please re-open if you really want this to be merged and make sure you update the config file as well as send some test tokens to julien51.eth so we can complete the deployment.

**Pull request closed without merging**
