### PR TITLE
feat(unlock-app) - enable recurring 

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
Add ability to enable recurring in new dashboard.

**Button** 
Screenshot 2022-10-04 at 14 01 04

**Recurring enable** 
Screenshot 2022-10-04 at 14 25 04

**Loading state** 
Screenshot 2022-10-04 at 14 33 25

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
Not very obvious recurring is already enabled here. I would replace button with a label or similar.

**Review by julien51 — APPROVED** [review]

**Comment by julien51** [comment]
> Not very obvious recurring is already enabled here. I would replace button with a label or similar.

Agreed so if you can change to a label that's better!

**Comment by kalidiagne** [comment]
> > Not very obvious recurring is already enabled here. I would replace button with a label or similar.
> 
> Agreed so if you can change to a label that's better!

Screenshot 2022-10-04 at 14 55 52

**Review by searchableguy — APPROVED** [review]
LGTM.

**Pull request merged**
