### PR TITLE
feat(unlock-protocol-com) - fix encode string and render description as html

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
- Fix wrong title issue on "Add to calendar" without specific encoding when special char is present
- Shoe event description as html

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Screenshot!

**Comment by kalidiagne** [comment]
> Screenshot!


**Event with correct title**
Screenshot 2022-07-29 at 15 49 24

**Event box**
Screenshot 2022-07-29 at 15 49 18

**Render as html**
Screenshot 2022-07-29 at 15 49 36

**Review by julien51 — APPROVED** [review]

**Comment by kalidiagne** [comment]
- [x] Remove duplicate events
- [x] Change formatting if start date and end date are not in the same day 

**Formatting for same start/end same day**
Screenshot 2022-07-29 at 17 31 28

**Formatting for different start/end day**
Screenshot 2022-07-29 at 17 31 21


**Remove duplicated events** 
Screenshot 2022-07-29 at 17 33 11

**Review by julien51 — APPROVED** [review]

**Comment by julien51** [comment]
Actuallu one quick change: don't show the hour if the event is over multiple days!

**Comment by kalidiagne** [comment]
> Actuallu one quick change: don't show the hour if the event is over multiple days!
Screenshot 2022-07-29 at 17 43 26

**Pull request merged**
