### PR TITLE
Implement prettier using pretter-eslint

### LINKED ISSUE #461: Use prettier to automatically implement a style guide
**Is your feature request related to a problem? Please describe.**

linting is not automatic, and fixing linting errors often is time wasted adding commas, spaces, and the like.

Linting is best for finding actual problems, such as missing prop-types declarations, unused code.

**Describe the solution you'd like**
https://prettier.io/docs/en/index.html

Prettier automatically formats code to a given strict style

Prettier can be set up as a pre-commit hook to automatically format files staged for commit in a number of ways:

https://prettier.io/docs/en/precommit.html

It can also be easily configured for any code IDE to format on save.

**Describe alternatives you've considered**
The alternatives are manual editing and running `npm run lint` repeatedly.

### PR DESCRIPTION
**Pull request by cellog**
Fixes #461 

## Proposed Changes

  - use prettier --write followed by eslint --fix to easily enforce a style guide
  - package "prettier-eslint" does this internally
  - add .prettierrc
  - update README to help set up dev environment

A 2nd PR based on this one having actually run the reformat command is forthcoming as well.

### CODE REVIEW

**Comment by cellog** [comment]
oops, thought this was merged, so I closed it. sorry!

**Comment by julien51** [comment]
Ha no worries!

**Comment by julien51** [comment]
Hey @cellog , I am sorry to ask this but I think there was a follow up PR to this one? Could you please elaborate on what needs to be done? I'd love to merge it!

Thanks!

**Comment by cellog** [comment]
Hi,

The follow-up PR just showed how the source code would change after running `npm reformat`, so can be replicated locally.

**Comment by cellog** [comment]
oh looks like I need to re-base this too. If I have a chance tomorrow in the snow (ha) I will do that

**Comment by julien51** [comment]
Thanks a lot @cellog ! I'll merge this now and start working on a subsequent PR with `npm run reformat` ;)

**Pull request merged**
