### PR TITLE
Keep track of whether event creation form is submitted

### PR DESCRIPTION
**Pull request by cnasc**
# Description

This PR adds one piece of state to the Event creation form in the tickets app. Right now there is no visual impact, but we can use this state to change the page once the form is submitted. This should help us make a nice UX improvement once we have an idea what we'd like to do to indicate that the form was submitted.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
test?

**Comment by cnasc** [comment]
> test?

I don't think we have a good way to test this right now since `rtl` discourages actually testing methods. We can sit on this PR until we have some kind of effect dependent on this state, and then test for the presence or absence of that element.

**Comment by cellog** [comment]
because this is local state, I think you should implement the UI in this PR, then it can be tested

**Comment by cellog** [comment]
(i.e. there are no possible side effects, so it is not like redux in that you need to split the PR)

**Pull request closed without merging**
