### PR TITLE
feat(unlock-app) - add more specific parameters check for verifier page

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
- add more specific parameters check for verifier page
Screenshot 2022-06-03 at 16 21 04

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Review by julien51 — CHANGES_REQUESTED** [review]
Maybe we should use toasts so it is consistent in all of the application?

**Comment by searchableguy** [comment]
There is a middleware for valid network somewhere. You can use that.

**Comment by searchableguy** [comment]
> @searchableguy change verifier page URL from query to parameters as suggested, thk!

Need one more param for network in the url as well. We want to move away from current system of switching network to everything networks usable at once.

**Comment by kalidiagne** [comment]
> > @searchableguy change verifier page URL from query to parameters as suggested, thk!
> 
> Need one more param for network in the url as well. We want to move away from current system of switching network to everything networks usable at once.

@searchableguy changed with this `/verifiers/[network]/[lock]` path

I'm wondering if this does not cause  issues, for example, the case when the current network in metamask doesn't match the network in the parameters

**Comment by searchableguy** [comment]
It won't

**Comment by kalidiagne** [comment]
> It won't

Actually sure! no issue because is done via API!
if all is okay for you please approve it so I can merge, thk!

**Comment by searchableguy** [comment]
Hm, do you think using `/[network]/locks/[lock]/verifiers` as path?

**Comment by kalidiagne** [comment]
> Hm, do you mind using `/[network]/locks/[lock]/verifiers` as path?

Done!

**Review by searchableguy — APPROVED** [review]

**Review by julien51 — APPROVED** [review]

**Pull request merged**
