### PR TITLE
feat(networks): add Uniswap oracles addresses for UDT

### LINKED ISSUE #9518: Keeping track of Oracles
Let's add the oracle contract addresses used on the Unlock contracts to the networks package.
Let's also deploy any missing oracle for the networks that we support.

### PR DESCRIPTION
**Pull request by clemsos**
# Description

This PR adds oracle V2 and V3 addresses used for UDT prices to the network packages (when available)

### V2 

- [x] mainnet
- [x] polygon
- [x] rinkeby

### v3

mainnet: [0x951A807b523cF6e178e0ab80fBd2C9B035521931](https://etherscan.io/address/0x951A807b523cF6e178e0ab80fBd2C9B035521931)
goerli : [0x25197CaCDE16500032EF4B35d60c6f7aEd4a38a5](https://goerli.etherscan.io/address/0x25197CaCDE16500032EF4B35d60c6f7aEd4a38a5)
polygon : [0xE77c7F14e8EB9925ca418bF80c0a81a5B9C87683](https://polygonscan.com/address/0xE77c7F14e8EB9925ca418bF80c0a81a5B9C87683)
arbitrum : [0x821d830a7b9902F83359Bf3Ac727B04b10FD461d](https://arbiscan.io/address/0x821d830a7b9902F83359Bf3Ac727B04b10FD461d)
optimism : [0x1FF7e338d5E582138C46044dc238543Ce555C963](https://optimistic.etherscan.io/address/0x1FF7e338d5E582138C46044dc238543Ce555C963#code)
celo : [0x5108412Dd50A6ea79d2F13D5d1A23FDD9bF532db](https://celoscan.io/address/0x5108412Dd50A6ea79d2F13D5d1A23FDD9bF532db#code)
mumbai : [0x5108412Dd50A6ea79d2F13D5d1A23FDD9bF532db](https://mumbai.polygonscan.com/address/0x5108412Dd50A6ea79d2F13D5d1A23FDD9bF532db#code)

# Issues

Fixes #9518
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
>  xdai -> not deployed

Oh I really think it was deployed on xDAI

**Comment by clemsos** [comment]
We may want a syntax to differentiate contract using uniswap v2 from v3

**Comment by clemsos** [comment]
@julien51  is that still needed now that we are planning to use depay?

**Comment by julien51** [comment]
@julien51 is that still needed now that we are planning to use depay?


Absolutely! Depay is used to swap and purchase. Here we need to take into account transactions for the GNP...

**Review by searchableguy — APPROVED** [review]
LGTM

**Pull request merged**
