### PR TITLE
Add paywall/ to Travis

### PR DESCRIPTION
**Pull request by cnasc**
# Description

This PR adds the new split-off paywall to Travis. Travis will now lint (implemented, with a lint error fixed in this PR so we can merge) and test (once there are actual tests) the paywall as it does with all other Unlock code.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

**Comment by cellog** [comment]
I think the issue is that the copying of eslint to paywall isn't happening. I forgot the name of the thing that does it, but check in the scripts dir for that. I think it belongs in this PR, as it's all about config.

**Comment by cnasc** [comment]
Right, `link-parent-bin` should take care of that. Odd, it seems like it should do it for all subdirs already...

**Comment by cnasc** [comment]
> We shouldn't commit artifacts, but should gitignore them and rebuild like unlock-app does, otherwise they'll show modifications every time we run dev

So in this case, `artifacts` is just a symlink not the actual artifacts themselves, which is the same as what `unlock-app` has at the moment

**Comment by cellog** [comment]
Right, but isn't that in gitignore in unlock-app or did that change when I
wasn't looking? :)

**Pull request merged**
