### PR TITLE
Add Telegram link

### LINKED ISSUE #680: Telegram Link
We use telegram for community communications: [https://t.me/unlockprotocol](https://t.me/unlockprotocol).
We need a link to that channel on the website, in the top menu icon bar (to the right):
screen shot 2018-12-07 at 10 28 37
as well as  in the footer.

The telegram svg icon is already in the project and can be used. 
Please make sure that the layout is also good on mobile devices.

### PR DESCRIPTION
**Pull request by xhw1**
Fixes #680 
screen shot 2018-12-17 at 2 22 01 am
screen shot 2018-12-17 at 2 22 10 am
screen shot 2018-12-17 at 2 21 38 am
screen shot 2018-12-17 at 2 21 50 am

## Proposed Changes

- Add Telegram link in Header and Footer
- Update href of Telegram button

### CODE REVIEW

**Comment by julien51** [comment]
@xhw1 Not sure you got my previous messages ;) Please could you update the snapshots so we can merge? Thanks!

**Comment by xhw1** [comment]
> @xhw1 Not sure you got my previous messages ;) Please could you update the snapshots so we can merge? Thanks!

Yes, I'm working on it.

**Comment by cellog** [comment]
snapshots still failing, see output from travis:

```
unlock_1   |   ● withConfig High Order Component › when the current network is not in the list of required networks › should show a message indicating that the network needs to be changed
unlock_1   | 
unlock_1   |     expect(value).toMatchSnapshot()
unlock_1   | 
unlock_1   |     Received value does not match stored snapshot "withConfig High Order Component when the current network is not in the list of required networks should show a message indicating that the network needs to be changed 1".
unlock_1   | 
unlock_1   |     - Snapshot
unlock_1   |     + Received
unlock_1   | 
unlock_1   |     @@ -407,10 +407,11 @@
unlock_1   |               </a>
unlock_1   |               <a
unlock_1   |                 className="c7 c8"
unlock_1   |                 href="https://t.me/unlockprotocol"
unlock_1   |                 onClick={[Function]}
unlock_1   |     +           title="Telegram"
unlock_1   |               >
unlock_1   |                 <svg
unlock_1   |                   name="Telegram"
unlock_1   |                   viewBox="0 0 24 24"
unlock_1   |                 >
unlock_1   |     @@ -546,10 +547,11 @@
unlock_1   |               <a
unlock_1   |                 className="c7 c11"
unlock_1   |                 href="https://t.me/unlockprotocol"
unlock_1   |                 onClick={[Function]}
unlock_1   |                 size="48px"
unlock_1   |     +           title="Telegram"
unlock_1   |               >
unlock_1   |                 <svg
unlock_1   |                   name="Telegram"
unlock_1   |                   viewBox="0 0 24 24"
unlock_1   |                 >
unlock_1   | 
unlock_1   |       41 |         )
unlock_1   |       42 |         .toJSON()
unlock_1   |     > 43 |       expect(tree).toMatchSnapshot()
unlock_1   |          |                    ^
unlock_1   |       44 |     })
unlock_1   |       45 |   })
unlock_1   |       46 | })
unlock_1   | 
unlock_1   |       at Object.toMatchSnapshot (src/__tests__/utils/withConfig/missingProvidersWithConfig.test.js:43:20)
```

you'll need to rebase and then run npm test -- -u, then all should be well on the next commit

**Comment by xhw1** [comment]
> snapshots still failing, see output from travis:
> 
> ```
> unlock_1   |   ● withConfig High Order Component › when the current network is not in the list of required networks › should show a message indicating that the network needs to be changed
> unlock_1   | 
> unlock_1   |     expect(value).toMatchSnapshot()
> unlock_1   | 
> unlock_1   |     Received value does not match stored snapshot "withConfig High Order Component when the current network is not in the list of required networks should show a message indicating that the network needs to be changed 1".
> unlock_1   | 
> unlock_1   |     - Snapshot
> unlock_1   |     + Received
> unlock_1   | 
> unlock_1   |     @@ -407,10 +407,11 @@
> unlock_1   |               </a>
> unlock_1   |               <a
> unlock_1   |                 className="c7 c8"
> unlock_1   |                 href="https://t.me/unlockprotocol"
> unlock_1   |                 onClick={[Function]}
> unlock_1   |     +           title="Telegram"
> unlock_1   |               >
> unlock_1   |                 <svg
> unlock_1   |                   name="Telegram"
> unlock_1   |                   viewBox="0 0 24 24"
> unlock_1   |                 >
> unlock_1   |     @@ -546,10 +547,11 @@
> unlock_1   |               <a
> unlock_1   |                 className="c7 c11"
> unlock_1   |                 href="https://t.me/unlockprotocol"
> unlock_1   |                 onClick={[Function]}
> unlock_1   |                 size="48px"
> unlock_1   |     +           title="Telegram"
> unlock_1   |               >
> unlock_1   |                 <svg
> unlock_1   |                   name="Telegram"
> unlock_1   |                   viewBox="0 0 24 24"
> unlock_1   |                 >
> unlock_1   | 
> unlock_1   |       41 |         )
> unlock_1   |       42 |         .toJSON()
> unlock_1   |     > 43 |       expect(tree).toMatchSnapshot()
> unlock_1   |          |                    ^
> unlock_1   |       44 |     })
> unlock_1   |       45 |   })
> unlock_1   |       46 | })
> unlock_1   | 
> unlock_1   |       at Object.toMatchSnapshot (src/__tests__/utils/withConfig/missingProvidersWithConfig.test.js:43:20)
> ```
> you'll need to rebase and then run npm test -- -u, then all should be well on the next commit

Thanks, I'm so glad it finally passed!

**Comment by julien51** [comment]
Hey, great job, but your git commit is very poluted here :/ Not sure how that happened. 
Could you do something like this `git checkout master`, `git pull origin master`, `git checkout xhw1-add-telegram-link`, `git rebase master`, `git push --force`? This should clean things up alittle bit! Thanks

**Comment by xhw1** [comment]
> Hey, great job, but your git commit is very poluted here :/ Not sure how that happened.
> Could you do something like this `git checkout master`, `git pull origin master`, `git checkout xhw1-add-telegram-link`, `git rebase master`, `git push --force`? This should clean things up alittle bit! Thanks

Thank you so much! I think It's because I rebased directly on the upstream/master. Now I have rebased my master branch and rebased the working branch on my master branch.

**Comment by julien51** [comment]
Perfect! Thank you *very* much!

**Pull request merged**
