### PR TITLE
Update truffle-config.js with mainnet network

### PR DESCRIPTION
**Pull request by nfurfaro**
This PR fixes#896 by adding a network configuration for mainnet in our `truffle-config.js` file. It's a WIP and likely needs modification depending on the details of how we'll connect to a mainnet node for deployment.
cc @julien51 

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

**Comment by hardlydifficult** [comment]
Will localhost work for this? Maybe it should point to an Infura node

**Comment by nfurfaro** [comment]
We currently have a node running on AWS, but I want to check in with @julien51 ajout this.

**Comment by nfurfaro** [comment]
Update: After discussing with  @julien51, I think these setting should be fine, at least as a starting point. As far as the `gas` and `gasPrice` I think these are reasonable figures but would appreciate a second opinion @hardlydifficult . I've checked against what zOS is using to deploy their own demo projects to mainnet, as well as Aragon.. The current EthGasStation "standard"  gas price is 2.5 Gwei, so 3.5 seems reasoinable to ensure we don't wait too long. One thing we can double check though is to run `eth.getBlock("latest").gasLimit` on our AWS mainnet node to see where it's at. We may be able to bump ours up a bit depending on what this returns.

**Comment by hardlydifficult** [comment]
Looks good.

One thing we could consider, but is probably not necessary, is using an Oracle to dynamically assign the gasPrice.  That can't be in the config directly, but could be added to the migrations logic, e.g. https://web3js.readthedocs.io/en/1.0/web3-eth.html#getgasprice

**Comment by nfurfaro** [comment]
@hardlydifficult Yes, dynamically assigning the gasPrice could come in handy when we progress towards automated upgrades on rinkeby. I think the idea for mainnet was to keep it as a somewhat manual process, so probably not necessary for this deployment.

**Pull request merged**
