### PR TITLE
feat(locksmith): Run renewal jobs weekly and monthly

### PR DESCRIPTION
**Pull request by searchableguy**
# Description

fixes https://github.com/unlock-protocol/unlock/issues/10185

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Please add a daily cycle too.

**Comment by julien51** [comment]
For weekly, we run on _all_ the keys that have ever expired.
For daily we run on all of the keys that have expired in the month.
We add one that runs every 3 hours and that runs on all the keys that have expired within the day.
The current one runs every minute and renews anything expired within 30 minutes

Let's start with that.

Later we will add subgraphs that let us identify *when* someone who had an expired key has re-approved by stopping up their balance of ERC20 or bumped the approval.

**Comment by searchableguy** [comment]
Added 

weekly - keys within the last year. This is a good cut off instead of forever which can be unexpected from a user's perspective too if they authorized balance but didn't have any until a year later and suddenly get cut. 

daily - within the last week
every 5 minute - within the last hour

**Review by julien51 — APPROVED** [review]
Lgtm! 

Quick note: do you think we should have a way to "report" when the script ran with something like:
" Ran reveals for keys expired between x and y and renewed z successfully"

We could then pay to sentry for example?

**Pull request merged**
