### PR TITLE
added more files to nuke

### PR DESCRIPTION
**Pull request by julien51**
While trying to debug a local issue I noticed that several folders are not correctly removed.
This PR adds them to the list of folders to remove.

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [X] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by hardlydifficult** [comment]
would a ` git clean -X -d -f` maybe be more effective?

**Comment by julien51** [comment]
I think it could... but I worry that it may delete things we are not 100% sure we can delete?

**Comment by julien51** [comment]
For example I constantly have a few transient files which are not committed and that `git clean` would wipe.

**Comment by hardlydifficult** [comment]
not to press the issue, but you could consider making the command stash, clean, stash pop.

**Pull request merged**
