### PR TITLE
Addressing Compilation Warnings

### LINKED ISSUE #5406: Address contract warnings
**Describe the bug**
CI is reporting the following:
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom

Spot checking initialize, it appears we are not following best-practices.

### PR DESCRIPTION
**Pull request by nfurfaro**
# Description
This PR clears up all the warnings about initialize() we've been seeing on compilation.

One possible extra change would be to switch the initialize functions in `MixinLockCore` from `internal` to `public`

# Issues

Fixes #5406
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by NickCuso** [comment]
This is an improvement, but the warnings are still being emited.. is it possible the ZOS recommendation of using public initialize for all is now countering a solidity best practice of don't shadow functions?  

What if we switched to `_initializeMixinFunds(...) internal` for each?  That should remove the warnings since nothing is shadowed that way.  And it can save gas by 1) only using the modifier once, at the top level public initialize function and 2) removing some public functions from the lookup table which should never actually be called, potentially saving gas on other calls.

**Comment by nfurfaro** [comment]
Yeah, I just saw this. There are none of these warnings when compiling locally, but they show up when running tests.
I will implement your sufggestions above and re-push. I think they are good ideas.

**Comment by nfurfaro** [comment]
RE:
>What if we switched to _initializeMixinFunds(...) internal for each?

&
> only using the modifier once, at the top level public initialize function

No change to the warnings after doing this, but I still think it's a good change.

**Comment by nfurfaro** [comment]
Ah, yep. Call that a small win for now.

**Pull request merged**
