### PR TITLE
IPFS deploy

### PR DESCRIPTION
**Pull request by gawainb**
Added IPFS run commands with Pinata env varibles.

# Description

# Issues

#7198

Fixes #
Refs #

# Checklist:

- [ x ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by gawainb** [comment]
@julien51 here is where I began working on the CircleCi integration. I could use another set of 👀 eyes to look over it.

**Comment by gawainb** [comment]
> 
> 
> Thank you for your pull request and welcome to Unlock! We require contributors to sign our [Contributor License Agreement](https://github.com/unlock-protocol/unlock/blob/master/CLA.txt), and we don't seem to have the users @gawainb on file. In order for us to review and merge your code, please contact us (easiest way is to [open an issue](https://github.com/unlock-protocol/unlock/issues)) to get yourself added.

How can I sign this agreement?

**Comment by julien51** [comment]
Thanks! 
Easiest way is to open another PR in which you add your username to this file: https://github.com/unlock-protocol/unlock/blob/master/.clabot

**Comment by julien51** [comment]
Hey @gawainb ! I hope all is well, please let me know if I can help push this over the finish line in any way :)

**Comment by gawainb** [comment]
> Hey @gawainb ! I hope all is well, please let me know if I can help push this over the finish line in any way :)

Absolutely, there are some areas I could use your expertise in as setting it up.

**Comment by julien51** [comment]
Please write more :)

**Comment by julien51** [comment]
Hey @gawainb Can we push this over the finish line?

**Comment by gawainb** [comment]
> Hey @gawainb Can we push this over the finish line?

Yes I'm available now. I'll ping you on Discord.

**Comment by julien51** [comment]
Hey @gawainb, what is the problem you're seeing?

**Comment by gawainb** [comment]
I'm looking at this for reference. https://github.com/ipfs-shipyard/ipfs-dns-deploy. Should I make a whole new config for IPFS and IPNS?

**Comment by julien51** [comment]
Closing because it's inactive unfortunately. Let's re-open when ready to pass the finish line @gawainb ? Thanks for your work so far...

**Pull request closed without merging**
