### PR TITLE
This PR implements the viewport addon for our storybook stories

### PR DESCRIPTION
**Pull request by cellog**
# Description

This PR adds the viewport addon. This allows us to change the viewport size to see how our CSS responds to different screen sizes without having to resize the browser window.

It depends on #1941 to be merged first and then this PR to be rebased upon master.

screen shot 2019-03-06 at 10 00 00 pm
screen shot 2019-03-06 at 9 59 52 pm
screen shot 2019-03-06 at 9 59 43 pm
screen shot 2019-03-06 at 9 59 35 pm

# Issues

Refs #973

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [X] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Does this need a rebase before review?

**Comment by julien51** [comment]
Ha! I missed your comment below the screenshot ;)

**Comment by cellog** [comment]
rebased

**Comment by cellog** [comment]
this is ready for another look

**Pull request merged**
