### PR TITLE
running reformat and failing if some files have been changed

### PR DESCRIPTION
**Pull request by julien51**
On each PR, this script will now run `npm run reformat` and make sure that nothing was changed. If the styles are changed, the PR will fail. This should at least enforce that no code is ever merged that has a different format.

I believe an important next step here would be to find a way to run `npm install` any time the versions in `package-lock.json` has been changed.

### CODE REVIEW

**Comment by julien51** [comment]
Ho,ooo, this failed and could very well be the same problem that you're seeing @benwerd ?

**Comment by benwerd** [comment]
This is a very different problem to what I'm seeing. Here reformat seems to be being run on text files and markdown?!

**Comment by julien51** [comment]
This is failing because of an out of date package-lock.json file. See https://github.com/unlock-protocol/unlock/pull/726

**Comment by julien51** [comment]
Ok, @benwerd I think this should be mostly good now? PTAL?

**Comment by julien51** [comment]
FYI I added 2 files whose styles were not right :/

**Pull request merged**
