### PR TITLE
introducing CheckoutOptimisticFlag

### PR DESCRIPTION
**Pull request by cellog**
# Description

This is the optimistic flag we will use in the checkout, once we know where to put it. Based on https://www.figma.com/file/EZ4mtBKGj54EQCQvYDArtqKs/Forbes-Crypto-Blockchain?node-id=1%3A428

Note: I added the Unlock logo, which is not present in the design for desktop. I assumed this was an oversight since it's present in the mobile view. I based it on the confirmed flag (which does have the logo in desktop).

This is based upon the existing Optimistic flag, which is unmodified for mobile view in the design.

Screen Shot 2019-06-06 at 10 51 00 AM
Screen Shot 2019-06-06 at 10 50 42 AM

# Issues

Refs #2903

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [X] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by smombartz** [comment]
@cellog good point on that inconsistency. i would actually now suggest to use our wordmark throughout. 
image

**Comment by cellog** [comment]
?? this is a huge change, would you mind updating the figma?

**Comment by smombartz** [comment]
we might want to do this later then. figma is updated.

**Comment by cellog** [comment]
thank you!

**Comment by cellog** [comment]
closing in order to address major changes to make

**Pull request closed without merging**
