### PR TITLE
Deploy v8 to Rinkeby

### PR DESCRIPTION
**Pull request by NickCuso**
# Description

TODO:
 - Upgrade proxies (after unlock-js is updated)
 - Configure UniswapV2
 - Follow steps here https://github.com/unlock-protocol/unlock/issues/4282#issuecomment-656379823

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by NickCuso** [comment]
@julien51 I've tried re-running CI a few times, but it keeps failing with the same error `JavaScript heap out of memory`. But the changes are in files that are not used by tests. I don't know what might be causing this. Any ideas?

**Comment by julien51** [comment]
Hum. I looked and I am not sure.
The lines above
```
<--- Last few GCs --->

[89:0x556987616be0]   663824 ms: Scavenge 1366.2 (1415.7) -> 1365.5 (1415.7) MB, 12.0 / 0.0 ms  (average mu = 0.156, current mu = 0.083) allocation failure 
[89:0x556987616be0]   663896 ms: Scavenge 1367.5 (1417.0) -> 1366.9 (1417.5) MB, 12.6 / 0.0 ms  (average mu = 0.156, current mu = 0.083) allocation failure 
[89:0x556987616be0]   663920 ms: Scavenge 1367.9 (1417.5) -> 1367.2 (1418.5) MB, 7.9 / 0.0 ms  (average mu = 0.156, current mu = 0.083) allocation failure 
```

Seem to indicate that the memory consumption is pretty high ( > 1GB). A quick search seems to indicate that this should stay below the limit on Circle, so that might not be it.

Does this fail at the same "point" every time?

**Comment by NickCuso** [comment]
Yes - it fails at the exact same line each time. 

The retry history: https://app.circleci.com/pipelines/github/unlock-protocol/unlock?branch=hardlydifficult%2FrinkebyDeploy

hmm, I'm going to checkout this branch and run all the tests locally to ensure nothing strange is happening

**Comment by NickCuso** [comment]
It does fail the same way locally. Hmmm... I'll look into this some more..

**Comment by NickCuso** [comment]
I split this PR into parts. The GC error is due to this change: https://github.com/unlock-protocol/unlock/pull/6800/files#diff-45afcf2d0dc203257d2eaa06a30a5c63R6

I have no idea why though..

**Pull request closed without merging**
