### PR TITLE
Remove remix-ide and use hosted IDE instead.

### PR DESCRIPTION
**Pull request by hardlydifficult**
# Description

Removing the `remix-ide` and changing the command to connect to the hosted solution instead.  To use:

 - `npm run remix`
 - Open browser to remix.ethereum.org
 - Click `Connect to localhost`

And the directory appears on the left.  You can edit files and they are synced with your local file system.

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by nfurfaro** [comment]
I would be ok with this, but just wondering what benefits it provides over the current setup?

**Comment by nfurfaro** [comment]
I'm ok with this, but would like to know how it's better than our current setup?

**Comment by hardlydifficult** [comment]
One less package to install and update I guess.  I just thought it would be easier to use the hosted version, and might as well turn off the read-only restriction.

That said, neither approach actually works ATM.  The node references do not compile.  So this is not terribly important either way ;)

**Comment by nfurfaro** [comment]
re:
>The node references do not compile.
Is there a specific error you're getting for this?

**Comment by hardlydifficult** [comment]
Reference not found. Does it work for you?

**Comment by nfurfaro** [comment]
Will give it a try now

**Comment by nfurfaro** [comment]
Usually the error about reference to AST nodes is fixed by deleting artifacts and re-compiling contracts

**Comment by hardlydifficult** [comment]
Ah, well there's a good reason for this PR - at least you'll get the IDE to open without issue.

But once you get past that the import will fail.  Remix has a special syntax for importing external packages, which sucks.  But having this integration available can still be handy, especially when doing a prototype.

**Comment by nfurfaro** [comment]
I'm cool with this as long as @julien51 is comfortable with it.

**Pull request merged**
