### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by NickCuso**
# Description

Output from `imgbot`
This bot attempts to lossless compression on all images in the repo.  It triggered as soon as I made a fork of Unlock.  We might want to consider enabling this 

https://imgbot.net/

*Total -- 7,640.58kb -> 6,765.21kb (11.46%)

/unlock-app/src/static/images/unlock-word-mark.png -- 40.05kb -> 20.84kb (47.97%)
/unlock-protocol.com/src/static/images/unlock-word-mark.png -- 40.05kb -> 20.84kb (47.97%)
/unlock-protocol.com/src/static/images/blog/erc20-locks/dai-lock.png -- 49.42kb -> 32.20kb (34.85%)
/smart-contracts/Contracts_and_Interfaces.png -- 314.68kb -> 209.21kb (33.52%)
/unlock-protocol.com/src/static/images/blog/erc20-locks/select-dai.png -- 37.98kb -> 27.40kb (27.85%)
/unlock-protocol.com/src/static/images/blog/non-fungible-tokens-betaworks/non-fongible-tokens-betaworks-locked.png -- 206.11kb -> 149.16kb (27.63%)
/unlock-protocol.com/src/static/images/blog/adsupportedweb/adblocker.png -- 29.88kb -> 22.01kb (26.32%)
/unlock-protocol.com/src/static/images/blog/erc20-locks/purchase-key.png -- 151.87kb -> 112.40kb (25.99%)
/unlock-protocol.com/src/static/images/blog/protocol-for-memberships.png -- 395.84kb -> 301.03kb (23.95%)
/unlock-protocol.com/src/static/images/blog/non-fungible-tokens-betaworks/non-fongible-tokens-betaworks.png -- 132.04kb -> 101.18kb (23.37%)
/unlock-protocol.com/src/static/images/blog/erc20-locks/approve-withdraw-erc20.png -- 185.24kb -> 149.35kb (19.38%)
/unlock-protocol.com/src/static/images/blog/nftdevmeetup/hero.jpg -- 498.66kb -> 405.23kb (18.74%)
/unlock-protocol.com/src/static/images/blog/announcingv0/newlock.png -- 90.72kb -> 74.14kb (18.28%)
/unlock-app/src/static/images/illustrations/background-cover.jpg -- 144.48kb -> 126.43kb (12.5%)
/unlock-protocol.com/src/static/images/blog/itstimetounlocktheweb/unlocklegacy.jpg -- 99.23kb -> 87.58kb (11.74%)
/unlock-protocol.com/src/static/images/blog/known/unlock-fields.png -- 39.04kb -> 34.77kb (10.94%)
/unlock-app/src/static/images/unlock.png -- 126.43kb -> 113.55kb (10.19%)
/unlock-protocol.com/src/static/images/unlock.png -- 126.43kb -> 113.55kb (10.19%)
/unlock-protocol.com/src/static/images/blog/known/unlock-admin.png -- 99.13kb -> 89.59kb (9.62%)
/unlock-protocol.com/src/static/images/blog/erc20-locks/create-lock.png -- 9.12kb -> 8.37kb (8.27%)
/unlock-protocol.com/src/static/images/blog/known/unlock-modal.png -- 52.06kb -> 47.90kb (7.99%)
/unlock-protocol.com/src/static/images/blog/adsupportedweb/1984.jpg -- 327.62kb -> 301.93kb (7.84%)
/unlock-app/src/static/images/blog/whatisunlock.jpg -- 571.82kb -> 530.93kb (7.15%)
/unlock-protocol.com/src/static/images/blog/whatisunlock.jpg -- 571.82kb -> 530.93kb (7.15%)
/tickets/src/static/images/png/tickets.png -- 1,125.35kb -> 1,049.94kb (6.7%)
/unlock-protocol.com/src/static/images/blog/freedomofspeech/thisisforeveryone.jpg -- 610.31kb -> 575.73kb (5.67%)
/tickets/src/static/images/jpg/tickets.jpg -- 205.00kb -> 194.16kb (5.29%)
/unlock-protocol.com/src/static/images/blog/known/known-unlock.png -- 68.73kb -> 65.99kb (3.99%)
/unlock-protocol.com/src/static/images/blog/announcingv0/paywalldemo.png -- 127.53kb -> 123.81kb (2.92%)
/unlock-protocol.com/src/static/images/pages/png/simple-hover.png -- 126.92kb -> 123.54kb (2.66%)
/unlock-app/src/static/images/pages/png/simple-hover.png -- 126.92kb -> 123.54kb (2.66%)
/unlock-protocol.com/src/static/images/blog/waystounlocktheweb/hero.jpg -- 546.76kb -> 536.10kb (1.95%)
/unlock-protocol.com/src/static/images/pages/png/more-hover.png -- 181.67kb -> 180.96kb (0.39%)
/unlock-app/src/static/images/pages/png/more-hover.png -- 181.67kb -> 180.96kb (0.39%)

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cnasc** [comment]
Imgbot looks really helpful, and it should be pretty quick to enable on the repo (free open source plan tier), thoughts @julien51?

**Comment by NickCuso** [comment]
Yup, I pitched this bot previously.  One-click to get started and then once in a blue moon (maybe when we blog or something) it'll find a new image to compress.  Above is just a copy paste of the bot's PR.

**Comment by julien51** [comment]
Let's do this!

**Comment by julien51** [comment]
you need to rebase tho @NickCuso !

**Comment by NickCuso** [comment]
If you want to turn on the bot, go ahead with that.  We can close this PR and let the bot do its thing. @julien51

**Comment by NickCuso** [comment]
Just rebased again for the cla update

**Comment by NickCuso** [comment]
FYI I still think closing this and turning on the bot is a better solution, but I'll go ahead and merge this.

**Comment by cnasc** [comment]
> FYI I still think closing this and turning on the bot is a better solution, but I'll go ahead and merge this.

I think so too, but unfortunately I can't add apps to our Github and I don't know if @julien51 will have the time to do so anytime soon. So this is a reasonable stopgap

**Pull request merged**
