### PR TITLE
fix(ci): fix use of `run all tests` tag

### LINKED ISSUE #9306: Run all tests command does not show feedback
On CI, the /run-all-tests command effectively run the tests but does not post the results back to the PR.

### PR DESCRIPTION
**Pull request by clemsos**
# Description

This PR simplify the use of `run all tests` tag, that will now run normally as part of the test suite.
 

# Issues

Fixes #9306
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by clemsos** [comment]
\run-all-tests

**Comment by clemsos** [comment]
> Dammit!
> 
> Screen Shot 2022-12-07 at 9 33 19 AM

yes its normal as the CI is still running with the file from master.

**Comment by julien51** [comment]
But...

Screen Shot 2022-12-07 at 4 43 01 PM

**Comment by clemsos** [comment]
> But...
> 
> Screen Shot 2022-12-07 at 4 43 01 PM

yes I removed the tag because it still fail as we have to merge into master to use the fix - gh actions using the file from master branch

**Pull request merged**
