### PR TITLE
Yarn workspaces and upgrade to v2

### PR DESCRIPTION
**Pull request by clemsos**
# Description

- [x] yarn workspaces
- [x] linter conf as package
- [ ] fix various issues preventing install -- see `yarn dlx @yarnpkg/doctor`
- [ ] upgrade to yarn v2  

# Issues

Refs #7427

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by clemsos** [comment]
The recommendation for yarn v2 is to check `.yarn/cache` into the monorepo so the build time get down to a few seconds. In our case this is ~500M of files so not sure yet if this is the best way to go as it could also slow down things quite a lot ( cloning indexing etc).

Need to be reassess

**Comment by julien51** [comment]
Oh wow! Maybe we can discard some of the (heaviest) dependencies we have? any way to assess them?

**Comment by clemsos** [comment]
yep I will look into that

**Comment by clemsos** [comment]
> Oh wow! Maybe we can discard some of the (heaviest) dependencies we have? any way to assess them?

to answer this, it seems that won't be necessary after all. What will be good is to rely on yarn cache on rebuild. There is sth called "plug n play" on yarn 2 and if we manage to activate the cache, that will be like few secs only to install packages once its setup.

The main thing now is to create a proper multi-stage docker image to build directly from monorepo, with stage 1 being the current core image, and other targets building different packages and apps (using docker buildkit ).

If we can use yarn cache properly then it will be much faster. Also we can also bundle all alpine/apk deps inside stage 1 so we dont get to rebuild all these either. Stages per services can then be used directly in compose, which is one less hassle.

There is a [yarn prod-install plugin](https://gitlab.com/Larry1123/yarn-contrib/-/blob/master/packages/plugin-production-install/README.md#example-dockerfile-advanced) that helps package things for Docker.

**Comment by julien51** [comment]
😱 all of the conflicts :(

**Comment by clemsos** [comment]
yes that's a lot of conflicts, but again we can get rid of all the locks so it is going to be fine.

I am in the middle of cleaning the deps anyway, running some utils to check deps. What works best so far 

- `yarn workspaces foreach dlx depcheck`
- `yarn dlx @yarnpkg/doctor`

**Comment by julien51** [comment]
Thanks for the clarification here! Maybe one thing we need to understand is see why we have more than 500MB of deps? Any clear culprit that we can remove or cleanup?

**Comment by clemsos** [comment]
> Thanks for the clarification here! Maybe one thing we need to understand is see why we have more than 500MB of deps? Any clear culprit that we can remove or cleanup?

yes thats a better approach. Here 

```sh
$ du -sh ./node_modules/* | sort -nr | grep '\dM.*' | head -n20

142M    ./node_modules/@netlify
141M    ./node_modules/@storybook
113M    ./node_modules/truffle
 95M    ./node_modules/@openzeppelin
 87M    ./node_modules/@vue
 70M    ./node_modules/hardlydifficult-ethereum-contracts
 66M    ./node_modules/aws-sdk
 63M    ./node_modules/@truffle
 61M    ./node_modules/mcl-wasm
 61M    ./node_modules/ethers
 58M    ./node_modules/typescript
 58M    ./node_modules/microbundle-crl
 54M    ./node_modules/detective-typescript
 54M    ./node_modules/@firebase
 49M    ./node_modules/ethereumjs-testrpc
 46M    ./node_modules/solidity-coverage
 45M    ./node_modules/ganache-core
 43M    ./node_modules/hardhat
 33M    ./node_modules/hardlydifficult-eth
 30M    ./node_modules/next
```

what we can do

1. cleanup `smart-contracts-extension`:  remove `@vue/cli`(unused), migrate to hardhat (remove truffle + ganache), remove deprec `@openzeppelin/upgrades`
1. replace netlify deployment by docker-based solution. It should be possible to dockerize the cli and build from an image instead of a node dep. That will remove the `@netlify` and `detective-typescript`
2. remove unused ref `@openzeppelin/cli` in smart-contracts. Will also remove firebase

I think we can already cut down the size to >150M with this

**Comment by julien51** [comment]
Sounds good!

Please, do move smart-contract-extensions to hardhat first! I think that's a low hanging fruit and you have experience with i already :)

I can look at the`@netlify` stuff and the `@openzeppelin/cli`.

I will also look into storybooks and see if we can make it ligther.

**Comment by clemsos** [comment]
ok lots of learning here, also some complexity. I am gonna close this and split the problems into smaller PRs

**Pull request closed without merging**
