### PR TITLE
Fix compile warnings

### PR DESCRIPTION
**Pull request by NickCuso**
# Description

Fix all the Solidity compile warnings.  This should not change our bytecode at all.

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by nfurfaro** [comment]
So you've switched from comment directives, to simply commenting out the parameter names. Why the `suppressCompileWarning++` ? Would we not see warnings reappear if this approach failed?

**Comment by NickCuso** [comment]
The suppressCompileWarning variable thing is for the warning which says could be `pure` instead.

**Comment by NickCuso** [comment]
I'm not sure if there's a better way to get rid of those.  But it's just a test artifact so this might be sufficient.

**Comment by nfurfaro** [comment]
Ah, I see. Yeah, maybe this is sufficient then. Could we just mark these as `pure` to fix the warning?

**Comment by NickCuso** [comment]
No, it's trying to match the erc20 abi.

**Pull request merged**
