### PR TITLE
feat(unlock-app) - show warning ticket is not marked as checked in

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
This PR add a warning if ticket is not marked as "checked in". This to make sure the button is not cliccked accidentally or to avoid missing ticket checked-in.

Screenshot 2022-09-07 at 11 59 16

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by kalidiagne** [comment]
Added new Dialog as warning, check PR description for ref

**Review by julien51 — CHANGES_REQUESTED** [review]
Can you center the "Warning", also use this sentence: "The current ticket has not been checked-in. Are you sure you want to  scan the next one?"

**Comment by kalidiagne** [comment]
> Can you center the "Warning", also use this sentence: "The current ticket has not been checked-in. Are you sure you want to scan the next one?"

Updated! here is a screenshoot 
Screenshot 2022-09-07 at 16 08 30

**Comment by julien51** [comment]
Great!

**Review by julien51 — APPROVED** [review]
I think we will need to create a more generic "alert" but that'll do for this one!

**Pull request merged**
