### PR TITLE
fix(subgraph) commenting tokenUri update because it breaks on large collections

### PR DESCRIPTION
**Pull request by julien51**
# Description

When a collection is (very?) large, we can't loop over the keys and update them all without breaking indexing on our subgragh.

For now we'll skip updating the tokenURI but we probably need something better.

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
Can you also update any place where subgraph service is used with tokenURI in keys?

**Comment by julien51** [comment]
> Can you also update any place where subgraph service is used with tokenURI in keys?

Well we still have the `tokenUri` property... but it will just be outdated. I am trying to find what the best option is from The Graph team

**Comment by clemsos** [comment]
A workaround would be to assess what "very" large means and then bypass the operation if the `totalKeys` is let's more than 1000. Not ideal but can save us some pain until graph team sorts out the issue

**Comment by julien51** [comment]
I think this is a good idea. The problem is we have to "guess" what the timeout is :/

**Comment by clemsos** [comment]
> I think this is a good idea. The problem is we have to "guess" what the timeout is :/

do we know which lock is failing?

**Comment by julien51** [comment]
> do we know which lock is failing?

Yes: https://polygonscan.com/token/0xafcfff71f3e717fcdb0b6a1bf20026304fd41bee (40k keys!)

**Comment by clemsos** [comment]
Isn't 100 a bit low? Also shouldn't we check to have this condition only on Polygon (if that only fails there)?

**Pull request merged**
