### PR TITLE
Skipping jobs when changes are not relevants

### PR DESCRIPTION
**Pull request by julien51**
# Description

In order to speed our builds (and decrease the costs on both Circle and Chromatic!) I am introducing
a new script which will skip jobs if:
1. The build is not on master (we run all jobs on master)
2. The files changed are not relevant to the job in question

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [X] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
For now, the only thing which runs every-time will be integration tests!

**Comment by cnasc** [comment]
I think we have to adjust the chromatic config to handle the cases where the stories don't actually run

**Comment by julien51** [comment]
So, this is annoying. 2 options:
* Find a way to tell Chromatic to tell Github that things are ok
* Make Chromatic "not required"

The 2nd option is easy but I worry that we may merge PR which actually do not pass Chromatic in the future?

**Comment by cnasc** [comment]
I think the first option is the better one. I tried searching for ways to make Chromatic report a success without running anything. Maybe we should reach out to their support?

**Comment by julien51** [comment]
Yup! Done that ;)

**Comment by julien51** [comment]
The only thing that is not perfect about that first solution is that it will still require us to build the docker image first tho...

**Comment by julien51** [comment]
I am worried there is no good way of doing 1. now, so for now I will make the ChromaticQa checks optional.

**Comment by cnasc** [comment]
> I am worried there is no good way of doing 1. now, so for now I will make the ChromaticQa checks optional.

We'll just have to be vigilant that we don't accidentally merge regressions

**Pull request merged**
