### PR TITLE
feat(unlock-app)  - replace logos section on events page

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description

**Desktop**

**Event landing page**
Screenshot 2023-07-20 at 16 46 39

**Certificate landing page**
Screenshot 2023-07-20 at 16 47 55

**Mobile** 

Screenshot 2023-07-20 at 16 48 19

Screenshot 2023-07-20 at 16 48 11

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by ccarfi** [comment]
Screen Shot 2023-07-20 at 8 49 19 AM

Screen Shot 2023-07-20 at 8 53 29 AM

**Comment by ccarfi** [comment]
Screen Shot 2023-07-20 at 8 48 02 AM

**Comment by ccarfi** [comment]
Screen Shot 2023-07-20 at 8 46 39 AM

**Comment by ccarfi** [comment]
@kalidiagne two things to fix please

1) button copy is different here than it is in prod. please see images above and refer to prod. buttons should read "Get started for free"

2) the images for the PROBLEM section have different heights, which causes the alignment of the paragraphs below to be raggedy

**Comment by ccarfi** [comment]
Screen Shot 2023-07-20 at 8 58 05 AM

this section disappeared. please put it back.

**Comment by kalidiagne** [comment]
> @kalidiagne two things to fix please
> 
> 1. button copy is different here than it is in prod. please see images above and refer to prod. buttons should read "Get started for free"
> 2. the images for the PROBLEM section have different heights, which causes the alignment of the paragraphs below to be raggedy

For the first point, copy was changed here https://github.com/unlock-protocol/unlock/pull/12374, need to restore it? 

here is also the fix for "The Problem" section 

Screenshot 2023-07-20 at 18 57 32

**Review by ccarfi — APPROVED** [review]

**Pull request merged**
