### PR TITLE
Adds support for v7 to unlock-js

### PR DESCRIPTION
**Pull request by julien51**
# Description

This PR adds support for v7 to our unlock-js library.
It will be easier to review commit by commit (I can split in smaller pieces if that's helpful).

* `d0dd31930` ading unlock-abi-7 is just adding the npm module and running `yarn run build`
* `f3709043b` copies over the files (identically) from v13 to v7
* `be9396886` renames v13 in v7 in the appropriate locations
* `318109516` to add the custom version of `configureUnlock` for v7
* `0f919fcf7`  bumps version!

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [X] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cnasc** [comment]
Looks good in general, but there's a failing test

**Comment by julien51** [comment]
Yeah, I think there will be more breakage. That was _too_ easy until now ;)

**Comment by julien51** [comment]
Ok, looking good! 
Let's see if tests pass this time.

**Comment by julien51** [comment]
Ok, all passed! I'll add 2 commits

`318109516` to add the custom version of `configureUnlock` for v7
`0f919fcf7` wwhich bumps versions

**Pull request merged**
