### PR TITLE
feat(unlock-app) - update pagination component

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description

Implement `2.3` solution for the pagination component (ref: https://uxdesign.cc/ui-cheat-sheet-pagination-infinite-scroll-and-the-load-more-button-e5c452e279a8)

Screenshot 2022-10-06 at 13 40 14

Screenshot 2022-10-06 at 13 39 58

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Review by julien51 — APPROVED** [review]

**Comment by julien51** [comment]
Can you make sure this works well in all places where we have pagination please?

**Comment by kalidiagne** [comment]
> Can you make sure this works well in all places where we have pagination please?

The pagination component is used only for new Dashboard, this will change only on that side, I leave as a draft until I double-check everything and different scenarios.

**Comment by kalidiagne** [comment]
Component tested and fixed: 

https://user-images.githubusercontent.com/20865711/195316047-dd1128c0-750e-4071-b3e2-4f4fa5da9e5a.mov

**Review by julien51 — APPROVED** [review]
LGTM!

**Pull request merged**
