### PR TITLE
fixing expirationAsText

### PR DESCRIPTION
**Pull request by julien51**
# Description

The paywall UI is broken because we show too much precision. (see screenshot below)
image

This PR also simplifies things!

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cnasc** [comment]
Is this different from #4244?

**Comment by julien51** [comment]
Yeah #4244 was making a mess of showing the screenshot above...

**Comment by cellog** [comment]
Is that from staging? Because #4244 did not ever show more than 1 unit. If it was production that would suggest it has not been pushed yet. Just a note that this PR should probably also remove the logic from getDurationAsText that it does not use, or remove it altogether.

Last question: #4244 would show an expiry date for expirations longer than a month instead of a duration, did you mean to remove that?

**Comment by julien51** [comment]
It's from master.

**Pull request merged**
