### PR TITLE
fix(smart-contracts): pass `tokenId` as param to the `onPurchase` hook

### LINKED ISSUE #9588: Include tokenId in onKeyPurchaseHook
We should include the `tokenId` when calling `onKeyPurchaseHook`.

### PR DESCRIPTION
**Pull request by clemsos**
# Description

Pass the created `tokenId` of the key as param to the `onPurchase` hook

# Issues

Fixes #9588
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Review by julien51 — COMMENTED** [review]
I am trying to think about what happens for existing hooks... and if there is a way to mitigate breakage

**Comment by clemsos** [comment]
> I am trying to think about what happens for existing hooks... and if there is a way to mitigate breakage

yes thats a breaking change from previous versions. We could do a try/catch with the earlier signature (without `tokenId`) to ensure backward compat

**Review by julien51 — APPROVED** [review]

**Comment by clemsos** [comment]
We also need to release the new hooks abi in the contracts package

**Comment by clemsos** [comment]
maybe we can version the hooks somehow, so we get a version check when upgrading/trying to set an old one?

**Pull request merged**
