### PR TITLE
Removing key specific data

### PR DESCRIPTION
**Pull request by hardlydifficult**
# Description

Per recent discussions we are simplifying the contract a bit by removing key specific data.  More info in the issue referenced below.

# Issues

Refs #831

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cellog** [comment]
Can you clarify how it breaks the tests on the paywall (and why, if you know)?

**Comment by hardlydifficult** [comment]
See https://circleci.com/gh/unlock-protocol/unlock/4834?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

e.g. the `keyDataFor` method does not exist anymore and `purchaseFor` expects 1 argument now and not 2.

**Comment by hardlydifficult** [comment]
Regarding the larger process point, anytime an external API changes in the contracts we need a process for updating dependencies such as the paywall.  For this specific change the `Key` struct changed, function `keyDataFor` was removed, and both `purchaseFor` and `purchaseForFrom` requires one less param.

**Comment by hardlydifficult** [comment]
BTW this is the first breaking change in contracts - if not this specific change, I would love to see us see some breaking change implemented end-to-end sooner than later.  It's a great proof of our upgradability.

**Comment by cellog** [comment]
So my specific reaction is this affects all apps, because the functionality is in walletService, which is about to become a shared library. So we will want a way to detect which contract version it is, and to abstract to the correct implementation of the functions you mentioned.

Is there a version explicit that we can grab from the contract?

**Comment by hardlydifficult** [comment]
Yes - in this case we are talking about PublicLock specifically and not the Unlock contract.  

`publicLockVersion` was not implemented in v0, which means call it and you should get the default value / i.e. 0 as expected. 
V0 returns 1.

**Comment by cellog** [comment]
Ok, we definitely need to key @julien51 into this conversation. This decision needs to be made very deliberately so we have a clear path both of how to handle this but also how to make the code intelligible.

**Comment by julien51** [comment]
Thanks for the work on this @hardlydifficult !
My thinking is that we *definetely* need to use the packaged versions in the app so that when we do introduce breaking changes in the smart contract, we do no unintentionally break the apps that are using it.

The way forward, IMO, is to make sure that all apps use the packaged npm, and not the current smart contracts. 
Then we package the *newer* version of the smart contract and add support inside `web3Service` and `walletService` for it.
When we have confidence that all is clean, we can upgrade our on chain contracts.

**Comment by hardlydifficult** [comment]
Sounds good.  Opened #1950 to track this.

**Comment by hardlydifficult** [comment]
Looks like the build is passing.  Promoting to a normal PR for review.

**Comment by nfurfaro** [comment]
@hardlydifficult Can you summarise this in a one-liner so I know what I'm looking at going in? IE: Is key data removed completely, or just to a data structure external to the Key struct?

**Comment by hardlydifficult** [comment]
All references to the key specific data field have been removed.

**Pull request merged**
