### PR TITLE
feat(unlock-app): Allow list hook for lock's settings

### PR DESCRIPTION
**Pull request by julien51**
# Description

Adding support for an Allow-list on the lock manager side 

https://www.loom.com/share/c15d72c2992445908931b2b225d5de9d?from_recorder=1&focus_title=1

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig
- ✅ Contract PublicLockLatest at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x36b34e10295cCE69B652eEB5a8046041074515Da is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract UDTv3 at 0x447B1492C5038203f1927eB2a374F5Fcdc25999d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x34EbEc0AE80A2d078DE5489f0f5cAa4d3aaEA355 is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x639143cbf90F27eA5Ce4b3A7D869d4D7878009A5 is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x0aC1a84AcaB08b630714d59dA74576D7274E68d5 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0x499C854E40Ce4056266822c86D1A326f0FE6491a is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xd0b14797b9D08493392865647384974470202A78 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x323Fd488F101F2F9252ecE9f9fe3e56C48912880 is verified
- ✅ Unlock source code at 0x36b34e10295cCE69B652eEB5a8046041074515Da matches packaged UnlockV13
- ✅ PublicLock source code at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 matches packaged PublicLockV14

We have found the following errors :

- ❌ Verification failed for onKeyPurchaseHook_ALLOW_LIST at 0x95222290DD7278Aa3Ddd389Cc1E1d165CC4BAfe5: Contract source code not verified




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig
- ✅ Contract PublicLockLatest at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x36b34e10295cCE69B652eEB5a8046041074515Da is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract UDTv3 at 0x447B1492C5038203f1927eB2a374F5Fcdc25999d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x34EbEc0AE80A2d078DE5489f0f5cAa4d3aaEA355 is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x639143cbf90F27eA5Ce4b3A7D869d4D7878009A5 is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x0aC1a84AcaB08b630714d59dA74576D7274E68d5 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0x499C854E40Ce4056266822c86D1A326f0FE6491a is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xd0b14797b9D08493392865647384974470202A78 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x323Fd488F101F2F9252ecE9f9fe3e56C48912880 is verified
- ✅ Unlock source code at 0x36b34e10295cCE69B652eEB5a8046041074515Da matches packaged UnlockV13
- ✅ PublicLock source code at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 matches packaged PublicLockV14

We have found the following errors :

- ❌ Verification failed for onKeyPurchaseHook_ALLOW_LIST at 0x95222290DD7278Aa3Ddd389Cc1E1d165CC4BAfe5: Contract source code not verified




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig
- ✅ Contract PublicLockLatest at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x36b34e10295cCE69B652eEB5a8046041074515Da is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract UDTv3 at 0x447B1492C5038203f1927eB2a374F5Fcdc25999d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x34EbEc0AE80A2d078DE5489f0f5cAa4d3aaEA355 is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x639143cbf90F27eA5Ce4b3A7D869d4D7878009A5 is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x0aC1a84AcaB08b630714d59dA74576D7274E68d5 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0x499C854E40Ce4056266822c86D1A326f0FE6491a is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xd0b14797b9D08493392865647384974470202A78 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x323Fd488F101F2F9252ecE9f9fe3e56C48912880 is verified
- ✅ Contract onKeyPurchaseHook_ALLOW_LIST at 0x92954dB2CeB43C2BF241C6a968EF711124408B00 is verified
- ✅ Unlock source code at 0x36b34e10295cCE69B652eEB5a8046041074515Da matches packaged UnlockV13
- ✅ PublicLock source code at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 matches packaged PublicLockV14







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Review by 0xTxbi — APPROVED** [review]

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/sepolia.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig
- ✅ Contract PublicLockLatest at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x36b34e10295cCE69B652eEB5a8046041074515Da is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract UDTv3 at 0x447B1492C5038203f1927eB2a374F5Fcdc25999d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x34EbEc0AE80A2d078DE5489f0f5cAa4d3aaEA355 is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x639143cbf90F27eA5Ce4b3A7D869d4D7878009A5 is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x0aC1a84AcaB08b630714d59dA74576D7274E68d5 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0x499C854E40Ce4056266822c86D1A326f0FE6491a is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xd0b14797b9D08493392865647384974470202A78 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_GITCOIN at 0x323Fd488F101F2F9252ecE9f9fe3e56C48912880 is verified
- ✅ Contract onKeyPurchaseHook_ALLOW_LIST at 0x92954dB2CeB43C2BF241C6a968EF711124408B00 is verified
- ✅ Unlock source code at 0x36b34e10295cCE69B652eEB5a8046041074515Da matches packaged UnlockV13
- ✅ PublicLock source code at 0xCbdcCc1C39f89CB2D292E66A82558698E54f8482 matches packaged PublicLockV14







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Pull request merged**
