### PR TITLE
New Profile Pics

### PR DESCRIPTION
**Pull request by smombartz**
New profile pictures of Akeem, Julien, Sascha for the about page

### Screenshot
screen shot 2018-12-14 at 14 51 05

### CODE REVIEW

**Comment by julien51** [comment]
Hey! Looks good! Do you mind running these files thru some kind of image size optimizer? It looks like they're fairly heavy? Maybe https://shortpixel.com/ or https://kraken.io/?

**Comment by smombartz** [comment]
@julien51 nice one! optimized and pushed.

**Comment by julien51** [comment]
@smombartz I *think* you can merge? LMK if you do not have a green button below to do that!

**Comment by benwerd** [comment]
Envious of the rest of you! I'm almost tempted to Photoshop in that wall ...

**Comment by vikaskyadav** [comment]
Hi all, Just a quick suggestion. The phrase `personal site` doesn't look that appealing and looks a little unnecessary. It would be better to replace it with something more meaningful... may be `icons`

**Pull request merged**
