### PR TITLE
[draft] Adding Paywall object to module

### PR DESCRIPTION
**Pull request by cnasc**
# Description

This PR starts to expose the paywall object from the paywall module. We need to determine how this gets built (ie with which config variables)

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
The configuration variable is a great question. Now that I think about it I wonder if these should be configurable? Maybe adding anothe argument to the `Paywall` constructor?

**Comment by cnasc** [comment]
@julien51 I think we're in pretty good shape here now. Before bumping the version and publishing we should do a smoke test just to make sure everything works as expected.

Once this is in place, we can extend to allow a provider to be passed in the constructor.

**Comment by cnasc** [comment]
Going to have to figure out what's up with eslint here

**Comment by cnasc** [comment]
`eslint-disable` appears not to be sufficient to resolve this

**Comment by cnasc** [comment]
This is confirmed working on local dev, ready for review

**Pull request merged**
