### PR TITLE
Contract gas usage testing

### PR DESCRIPTION
**Pull request by hardlydifficult**
# Description

Adding tests to track gas usage for a few primary function calls.  There are two parts:
 - it asserts that the limits defined in `walletService.js` are likely still valid
 - it logs exact gas usage to the console

e.g. 
```
  Contract: Unlock
    gas usage
2,106,954
      √ ^ gas used to createLock (115ms)

  Contract: Lock
    gas usage
175,408
      √ ^ gas used to purchaseFor w/o key data (92ms)
180,662
      √ ^ gas used to purchaseFor w/ key data (90ms)
107,057
      √ ^ gas used to transferFrom w/o key data (235ms)
126,857
      √ ^ gas used to transferFrom w/ key data (270ms)
```

Logging to the console during a unit test is unusual.  If you have a better suggestion please let me know.  My goal is to start collecting some data, with this we could check back at previous builds as needed to help trackdown what may have caused a significant change to gas requirements.

This is for #1113, although longer term we could probably improve on this approach.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by hardlydifficult** [comment]
The numbers shown are not correct, fix coming.

**Comment by hardlydifficult** [comment]
k fixed

**Comment by cnasc** [comment]
Is it possible, instead of having the logging in the test itself, to have it as the output of an NPM command? Then that's something we could have the CI server run, then do something with the result (send/write it somewhere we can easily access it) rather than having to parse it out of the test logs.

**Comment by hardlydifficult** [comment]
Just to clarify - remove the log from the tests (but maybe keep the test for the asserts) and then create a separate command which prints the log lines in an easy to consume format.  Have `npm run ci` execute both the tests and this gas logger.

Correct?  if so, sounds good to me

**Comment by cnasc** [comment]
That's what I had in mind, that way the tests stay "clean" although I'll let others chime in to see if that's palatable to the group at large

**Comment by hardlydifficult** [comment]
I'll need to experiment a bit to see how that would turn out.  It may be a little hacky since I need `truffle` to execute the gas logger as a test.  However I have an idea to try out.

**Comment by cellog** [comment]
so here's what I would do: create a test that loads `walletService` to grab the current gas values, and then computes the current ones, and asserts that they are less than the max value
then, create 4 tests that use the actual value in the title of the test, and do a dummy assertion
that way you can see the gas usage

**Comment by hardlydifficult** [comment]
I need a hand.  I'm a bit of a JS newb.  How do I load walletService?

I tried two ways...


const WalletService = require('../../../unlock-app/src/services/walletService')
fails with
```
Error: Plugin 0 specified in "E:\\UnlockProtocol\\unlock\\unlock-app\\node_modules\\next\\babel.js" provided an invalid property of "default" (While processing preset: "E:\\UnlockProtocol\\unlock\\unlock-app\\node_modules\\next\\babel.js")
    at Plugin.init (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:152:12)
    at E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:14
    at E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-register\lib\node.js:103:45)
    at loader (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (E:/UnlockProtocol/unlock/smart-contracts/test/Unlock/gas.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at E:\UnlockProtocol\unlock\smart-contracts\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (E:\UnlockProtocol\unlock\smart-contracts\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (E:\UnlockProtocol\unlock\smart-contracts\node_modules\mocha\lib\mocha.js:536:10)
    at E:\UnlockProtocol\unlock\smart-contracts\node_modules\truffle\build\webpack:\packages\truffle-core\lib\test.js:125:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

import WalletService from '../../../unlock-app/src/services/walletService'
fails with
```
(function (exports, require, module, __filename, __dirname) { import WalletService from '../../../unlock-app/src/services/walletService';
                                                                     ^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at loader (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\UnlockProtocol\unlock\smart-contracts\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at E:\UnlockProtocol\unlock\smart-contracts\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (E:\UnlockProtocol\unlock\smart-contracts\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (E:\UnlockProtocol\unlock\smart-contracts\node_modules\mocha\lib\mocha.js:536:10)
    at E:\UnlockProtocol\unlock\smart-contracts\node_modules\truffle\build\webpack:\packages\truffle-core\lib\test.js:125:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by cellog** [comment]
ah yes, it needs to be pre-processed by babel. I guess the smart contracts tests aren't doing that then :/. The solution would be to put the gas costs in a separate file and include it in both. For now,  I suggest hard-coding them and open an issue for the split I suggested

**Comment by hardlydifficult** [comment]
I added a `walletServiceMock` to hard code the values for now.  

I was not able to put the gas values into the strings used to title tests as it seems they are processed before code in the `before` block (even when nested under another `describe`).  However...

It looks like the suggestion from @cnasc may work.  I just pushed an update for that.  The downside of this approach is it may add to the build time - I included the package.json changes so we can see.

The report should appear after the solidity-coverage table and look something like this:

```
  Contract: Reports
Gas Usage
  createLock: 2,106,954
  purchaseFor w/o Key data: 130,408
  purchaseFor w/ Key data: 150,662
  transferFrom w/o Key data: 107,057
  transferFrom w/ Key data: 126,857
    √ gas usage report (695ms)


  1 passing (1s)
```

**Comment by hardlydifficult** [comment]
Report starts here: https://travis-ci.com/unlock-protocol/unlock/builds/102264749#L2712

**Comment by hardlydifficult** [comment]
So options ATM are:
 - keep a separate npm command like the most recent build
or 
 - run this with the usual test suite, but keep them grouped into a single test so the output is easy to read (like shown above)

**Pull request merged**
