### PR TITLE
WIP: Initial AccountApprovals implementation

### LINKED ISSUE #4753: Move User Account Lock approval process on chain
As part of moving quickly with the approval process of onboarding Locks to the User Accounts/managed account flow it became clear that we could probably move this on chain and gain a few benefits along the way.

The contract should provide the ability to store a mapping where the approved lock address is the key and associated metadata are the respective values. 

The Unlock multisig wallet should be the owner of this contract. We should ensure that we also capture the revocation of approval and that appropriate data is readable

### PR DESCRIPTION
**Pull request by NickCuso**
# Description

@akeem looking for confirmation on the approach.  If this is okay, I'll add some comments & tests and we can merge.

The `whitelist` combines two roles:
 - WhitelistAdmin can add/remove admins and add/remove whitelist operators.  It is possible to be a WhitelistAdmin without operator privileges 
 - Whitelist operators can issue the `approve` function here

This may be overkill.  We could simplify and use a single role instead of both operators and admins.  Let me know.

In terms of approvals themselves, you can set the data to anything if the account is approved.  Set it to an empty array to effectively remove approval.

Read approval data by calling `accountData(_account)`

# Issues

Fixes #4753
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by akeem** [comment]
@NickCuso I think this looks cool, I need to think a bit deeper about a worse case scenario of everyone losing access to make future modifications. Tagging @julien51 as he expressed interest in the ongoings here

**Comment by NickCuso** [comment]
@julien51 any notes before we move forward with this?

**Comment by julien51** [comment]
Sorry for the delay here. I think this works. This is for the EthWaterlook tickets, right?

**Comment by NickCuso** [comment]
@julien51 this is for onboarding Locks to the User Accounts/managed account flow

**Comment by julien51** [comment]
Ho, can we use `LockApproval` instead of accounts? and add comments in the file?

**Comment by NickCuso** [comment]
Great thanks.  This was just about confirming the general approach.  Closing, tracking via the original issue.

**Pull request closed without merging**
