### PR TITLE
removed artifacts from the repo

### PR DESCRIPTION
**Pull request by julien51**
This was causing confusion on several PRs.

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [X] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

**Comment by cellog** [comment]
build is failing on pending-changes check, not sure what because it doesn't say, might have to do a 2-step where we first gitignore and then remove?

**Comment by julien51** [comment]
Yeah that is what I am thinking. The strange thing is that the pending change is actually inside the `locksmith` folder so there is probably more to it.

**Comment by akeem** [comment]
Not sure if this helps to locate the root cause, but looking at the build log it appears as though the pending-changes scripts returns non-zeros for both ` /home/unlock/unlock-app` and ` /home/unlock/locksmith`

**Comment by julien51** [comment]
Hey @cellog PTAL, this time tests passed!

**Pull request merged**
