### PR TITLE
feat(unlock-app): adding a reusable Drawer component

### PR DESCRIPTION
**Pull request by julien51**
# Description

This component will be used in multiple places, starting on the dashboard and the members pages.
It introduces the use of Tailwind and HeadlessUI.

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [X] I have performed a self-review of my own code
- [X] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Example: https://share.getcloudapp.com/v1uLyrv6

**Comment by searchableguy** [comment]
Looks good to me. Bit of a nit would be to move the tailwindcss, autoprefixer, etc to devDependencies as they are part of the build chain.

**Review by searchableguy — APPROVED** [review]

**Comment by searchableguy** [comment]
I'm confused about if there should be an inbuilt close button on the drawer itself or it should be something for consumers to implement.

**Comment by searchableguy** [comment]
Let's add a close button on the top next to the title for accessibility.
image

**Review by searchableguy — CHANGES_REQUESTED** [review]
Add close button, please.

**Comment by julien51** [comment]
Good point!

**Comment by julien51** [comment]
image

**Review by searchableguy — APPROVED** [review]
LGTM

**Pull request merged**
