### PR TITLE
getting erc20Address and decimals from the contract when purchasing a key

### PR DESCRIPTION
**Pull request by julien51**
# Description

This simplifies the API by ensuring that the required data for the key purchase is pulled from the chain.

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
I hope before the end of the weekend. 
Since it has a lot of changes, I need to do thorough testing. Do you need it?

**Comment by cnasc** [comment]
Finishing up signing requires a change to unlock-provider, so we'd need to publish a new version to get that

**Comment by julien51** [comment]
Ok, feel free to submit the changes as a PR and they'll go out with the new version as soon as I am done with the tests tomorrow?

**Comment by cnasc** [comment]
Sounds good

**Pull request merged**
