### PR TITLE
feat(unlock-protocol-com): Add redesigned about page

### PR DESCRIPTION
**Pull request by searchableguy**
# Description

Adds redesigned about page

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Thanks @searchableguy !
I will trust your eye here but do you think we could try with a single column + an illustration on the side mahybe the U with people in it?

I also think we should add pictures of us in there but maybe for a next iteration! @ccarfi it would be great to have your input?

**Comment by searchableguy** [comment]
Oh Absolutely, the current page is pretty much copy of our existing page but with new color and design system. 

I've planned to redesign and align them more in future (same for blog pages which are copied from existing design) after discussing on where to move and getting new copy. I didn't want to do any drastic design of my own before discussing it.

**Comment by searchableguy** [comment]
@julien51 if you want, I could actually add some common elements and make it more exciting 

Let me know what you think of https://graphcdn.io/about or https://supabase.com/company

Something to loop in with chris.

**Comment by searchableguy** [comment]
Merging for now.

**Pull request merged**
