### PR TITLE
adding initial portions of linting

### PR DESCRIPTION
**Pull request by akeem**
# Description

Adding linting configuration and applies the rules for the current state of rover

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by akeem** [comment]
> would you also consider adding the typescript-specific no-unused-vars if it is possible? @cnasc found some issues in unlock-app, not sure if you would have the same ones

@cellog do you mean like this? https://github.com/unlock-protocol/unlock/pull/3629/files#diff-4790485a107e9401bb0850a302e6997bR7

**Comment by cellog** [comment]
That's the line I'm referring to. Here is how paywall does it:

https://github.com/unlock-protocol/unlock/blob/master/paywall/.eslintrc.js#L16

**Comment by akeem** [comment]
> That's the line I'm referring to. Here is how paywall does it:
> 
> https://github.com/unlock-protocol/unlock/blob/master/paywall/.eslintrc.js#L16

Ah cool, I will make this a future considersation

**Comment by cnasc** [comment]
When I tried the paywall config, it caused a bunch of lint errors around using `_` to ignore parameters. https://github.com/unlock-protocol/unlock/issues/3447

**Comment by cellog** [comment]
This should solve that issue, FYI: https://github.com/bradzacher/eslint-plugin-typescript/blob/master/docs/rules/no-unused-vars.md#argsignorepattern

**Pull request merged**
