### PR TITLE
feat(networks): redeploy missing hooks

### PR DESCRIPTION
**Pull request by clemsos**
# Description

Redeploy missing or unverified hooks

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/linea.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x4A553635774b3d6fB6273A83b5B49577dF450227 is verified
- ✅ Contract PublicLockPrevious at 0x70cBE5F72dD85aA634d07d2227a421144Af734b3 is verified
- ✅ Contract Unlock at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0xCD9C9b40D757b56359e19563203D3bc64089638d is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x04664b4290fa1F4001ED25d9576f7C2d980aC64d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0xD925Ac2887Ba4372849F0fd64217A6749552bb21 is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0x8c5D54B2CAA4C2D08B0DDF82a1e6D2641779B8EC is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0xaE8F3F0826A39122401ED634f0a5C19549331432 is verified
- ✅ Unlock source code at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 matches packaged UnlockV13
- ✅ PublicLock source code at 0x4A553635774b3d6fB6273A83b5B49577dF450227 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/linea.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x4A553635774b3d6fB6273A83b5B49577dF450227 is verified
- ✅ Contract PublicLockPrevious at 0x70cBE5F72dD85aA634d07d2227a421144Af734b3 is verified
- ✅ Contract Unlock at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0xCD9C9b40D757b56359e19563203D3bc64089638d is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x04664b4290fa1F4001ED25d9576f7C2d980aC64d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0xD925Ac2887Ba4372849F0fd64217A6749552bb21 is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0x8c5D54B2CAA4C2D08B0DDF82a1e6D2641779B8EC is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0xaE8F3F0826A39122401ED634f0a5C19549331432 is verified
- ✅ Unlock source code at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 matches packaged UnlockV13
- ✅ PublicLock source code at 0x4A553635774b3d6fB6273A83b5B49577dF450227 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/celo.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0xF241F12506fb6Bf1909c6bC176A199166414007a is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x1FF7e338d5E582138C46044dc238543Ce555C963 is verified
- ✅ Contract KeyManager at 0xF6963D3c395A7914De77f771C2fC44b47B8379AC is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x55C7336ea96BABb0bEabD676C07880aa8b76584a is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0xC4E6FDfe46CD1DF46801e080000a4897c42Fd75F is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xdc230F9A08918FaA5ae48B8E13647789A8B6dD46 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0xe49f5FD63cD7ec130B07dad30f068CC08F201e1e is verified
- ✅ Unlock source code at 0x1FF7e338d5E582138C46044dc238543Ce555C963 matches packaged UnlockV13
- ✅ PublicLock source code at 0xF241F12506fb6Bf1909c6bC176A199166414007a matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

### packages/networks/src/networks/linea.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x4A553635774b3d6fB6273A83b5B49577dF450227 is verified
- ✅ Contract PublicLockPrevious at 0x70cBE5F72dD85aA634d07d2227a421144Af734b3 is verified
- ✅ Contract Unlock at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0xCD9C9b40D757b56359e19563203D3bc64089638d is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x04664b4290fa1F4001ED25d9576f7C2d980aC64d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0xD925Ac2887Ba4372849F0fd64217A6749552bb21 is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0x8c5D54B2CAA4C2D08B0DDF82a1e6D2641779B8EC is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0xaE8F3F0826A39122401ED634f0a5C19549331432 is verified
- ✅ Unlock source code at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 matches packaged UnlockV13
- ✅ PublicLock source code at 0x4A553635774b3d6fB6273A83b5B49577dF450227 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/celo.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0xF241F12506fb6Bf1909c6bC176A199166414007a is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0x1FF7e338d5E582138C46044dc238543Ce555C963 is verified
- ✅ Contract KeyManager at 0xF6963D3c395A7914De77f771C2fC44b47B8379AC is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x55C7336ea96BABb0bEabD676C07880aa8b76584a is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0xC4E6FDfe46CD1DF46801e080000a4897c42Fd75F is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xdc230F9A08918FaA5ae48B8E13647789A8B6dD46 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0xe49f5FD63cD7ec130B07dad30f068CC08F201e1e is verified
- ✅ Unlock source code at 0x1FF7e338d5E582138C46044dc238543Ce555C963 matches packaged UnlockV13
- ✅ PublicLock source code at 0xF241F12506fb6Bf1909c6bC176A199166414007a matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

### packages/networks/src/networks/linea.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x4A553635774b3d6fB6273A83b5B49577dF450227 is verified
- ✅ Contract PublicLockPrevious at 0x70cBE5F72dD85aA634d07d2227a421144Af734b3 is verified
- ✅ Contract Unlock at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 is verified
- ✅ Contract KeyManager at 0x338b1f296217485bf4df6CE9f93ab4C73F72b57D is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x6878Ae3c863f6Ebd27B47C02F6B32aAC8B0BA07E is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0xCD9C9b40D757b56359e19563203D3bc64089638d is verified
- ✅ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x04664b4290fa1F4001ED25d9576f7C2d980aC64d is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0xD925Ac2887Ba4372849F0fd64217A6749552bb21 is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0x8c5D54B2CAA4C2D08B0DDF82a1e6D2641779B8EC is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0xaE8F3F0826A39122401ED634f0a5C19549331432 is verified
- ✅ Unlock source code at 0x70B3c9Dd9788570FAAb24B92c3a57d99f8186Cc7 matches packaged UnlockV13
- ✅ PublicLock source code at 0x4A553635774b3d6fB6273A83b5B49577dF450227 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig







Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

### packages/networks/src/networks/polygon.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0x8231d6fD0221C01FCAc5827EdD20D1aeC28EeBe3 is verified
- ✅ Contract PublicLockPrevious at 0x64A3328Cf61025720c26dE2a87B6d913fA6e376a is verified
- ✅ Contract Unlock at 0xE8E5cd156f89F7bdB267EabD5C43Af3d5AF2A78f is verified
- ✅ Contract KeyManager at 0x7111a1aDfbED501beaAd556Bba7cB6dCa3296aa9 is verified
- ✅ Contract UDTv3 at 0xf7E78d9C4c74df889A83C8C8d6D05BF70fF75876 is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD at 0x9F4AE507d7E91Ab37CF35f792940fE079bd4E24d is verified
- ✅ Contract onKeyPurchaseHook_PROMOCODE at 0x93E160838c529873cB7565106bBb79a3226FE07A is verified
- ✅ Contract onKeyPurchaseHook_PASSWORD_CAPPED at 0xc2D767a87d74d82CD4B290a63E2D703Ff1CDf6b9 is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0x64bDe27046F915e2BAb6339Ce4f737E34474344d is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0xBfF080aB4600554c1e8c390d2e070CF423767B64 is verified
- ✅ Unlock source code at 0xE8E5cd156f89F7bdB267EabD5C43Af3d5AF2A78f matches packaged UnlockV13
- ✅ PublicLock source code at 0x8231d6fD0221C01FCAc5827EdD20D1aeC28EeBe3 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the multisig

We have found the following errors :

- ❌ Verification failed for onKeyPurchaseHook_PROMO_CODE_CAPPED at 0x25Ec032F38b87295bA43C825993B9F4E1F4065c9: Contract source code not verified




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Review by julien51 — APPROVED** [review]

**Pull request merged**
