### PR TITLE
Add config for running tenderly debugger

### PR DESCRIPTION
**Pull request by nfurfaro**
# Description
This lets us use tenderly's debugging locally. in order for it to work, you must:
- install tenderly-cli (homebrew or curl)
- start ganache
- in another terminal, run `tenderly proxy`
- run `npx truffle migrate --network tenderly`
- run tests with `yarn debug` (basically truffle test with --network changed to "tenderly")

https://github.com/Tenderly/tenderly-cli#proxy-debugging

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by NickCuso** [comment]
can we make this the default for CI as well?  (maybe in another PR)

**Comment by nfurfaro** [comment]
To be perfectly honest, I'm not actually 100% sure it's working... I'm getting way more detail while running tests, but so far my attempts to introduce an error and generate a stack trace have resulted in "unable to extract stack trace".

**Comment by nfurfaro** [comment]
This could be used in CI as well (once we have confidence in it). NOt available through NPM though so would have to install with curl.

**Comment by nfurfaro** [comment]
Closing for now. Will keep testing locally and PR when I know it's working.

**Comment by NickCuso** [comment]
Had a call with tenderly today. It sounds like this is WIP but will be a great feature soon!

**Pull request closed without merging**
