### PR TITLE
feat(unlock-app) - upgrade to react 18

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
Were you able to find the issue behind some of the odd behavior on unlock-app? 

if I remember correctly, keychain wasn't loading properly and buttons on the manage dashboard weren't working.

**Comment by julien51** [comment]
Also iirc the paywall app was not loading at all :/

**Review by julien51 — APPROVED** [review]
LGTM!

**Review by julien51 — COMMENTED** [review]
Ship it! But please test extensively on staging!

**Comment by kalidiagne** [comment]
> Ship it! But please test extensively on staging!

Tested also locally and fixed some issue i found, checking also on staging when deployed

**Pull request merged**
