### PR TITLE
Adding mailing list back to homepage

### PR DESCRIPTION
**Pull request by benwerd**
# Description

So we can track who's really interested in Unlock. The mailing list just launches a MailChimp subscribe form.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

Screen Shot 2019-07-15 at 12 20 33 PM
Screen Shot 2019-07-15 at 12 26 37 PM

### CODE REVIEW

**Comment by cnasc** [comment]
Looks great, I think the only thing is the text color inside the button. I think the other green buttons usually have a `--darkgrey` text color.

**Comment by benwerd** [comment]
The color was in @smombartz's design - tagging him so he can weigh in.

**Comment by smombartz** [comment]
looks great. green color is good (more visible) and active.

if you want to include a line like "We will never ever share your information. Privacy and your trust are our top priority." or similar — maybe the language can tie back to our values.

**Comment by benwerd** [comment]
@smombartz good call:

Screen Shot 2019-07-15 at 3 52 54 PM

**Comment by benwerd** [comment]
@cla-bot[bot] recheck please

**Comment by benwerd** [comment]
@cla-bot[bot] check

**Pull request merged**
