### PR TITLE
Providing authentication around  requesting cards by email address

### PR DESCRIPTION
**Pull request by akeem**
# Description

In order to close an information hole, callers are now required to sign this get request. Invalid scenarios will receive a 401 error code in response.

There is a bit swirling around in here, since the initial request is a GET we have kept that the same and expecting the personal signed version of the payload attached as a query parameter to the request.

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Let's not merge yet please!

**Comment by julien51** [comment]
@cnasc rightfully noted that we need to update the "old" paywall/checkout for this to be merged first.

So I think this will have to come "last", once we have the new paywall in place...

**Comment by julien51** [comment]
Actually we may never need this, because the new paywall will not use these routes at all.

**Comment by akeem** [comment]
@julien51 ah okay, I guess give it a close if this is no longer required

**Pull request closed without merging**
