### PR TITLE
fix website layout issue on ios13

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description

# Issues

Fixes #
Screenshot 2021-11-09 at 22 39 07

Refs #

Screenshot 2021-11-09 at 22 38 52

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the docs to reflect my changes if applicable
- [x] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
LGTM! 
Please, merge the `master` branch or rebase and push again :)

**Comment by kalidiagne** [comment]
Rebase done!

**Comment by julien51** [comment]
Hey @kalidiagne it looks like something went wrong in your rebasing because the only change now is not the one you had yesterday?

**Comment by julien51** [comment]
Reference: https://github.com/unlock-protocol/unlock/issues/7757

**Review by julien51 — APPROVED** [review]
Thanks a lot!

**Pull request merged**
