### PR TITLE
Add Unlock v10 to contracts package

### PR DESCRIPTION
**Pull request by clemsos**
# Description

Add Unlock v10 to contracts package.

Note: this is achieved by running 

```
yarn hardhat release --contract contracts/Unlock.sol
```

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by clemsos** [comment]
Waiting for #8002 to be merged before adding`PublicLock`

**Comment by clemsos** [comment]
for some reasons, it turns out that a `PublicLockV9` abi is already in the contracts package, even though it is entirely similar to V8. The contract files have 1 small difference though

```shell
# abis files are similar
$ diff src/abis/PublicLock/PublicLockV9.json src/abis/PublicLock/PublicLockV8.json

$ ls -al src/abis/PublicLock/PublicLockV9.json src/abis/PublicLock/PublicLockV8.json
-rw-r--r--  1   348407 Jan  6 13:14 src/abis/PublicLock/PublicLockV8.json
-rw-r--r--  1  348407 Jan  6 13:14 src/abis/PublicLock/PublicLockV9.json

# seems there is an aditional function in the interface
$ diff src/contracts/PublicLock/PublicLockV9.sol src/contracts/PublicLock/PublicLockV8.sol                                                                                                                        130 ↵
1420,1425d1419
<   // Function to read the chainId field.
<   function chainId()
<     external
<     view
<     returns(uint);
<
1442,1443c1436
<     string calldata _URI,
<     uint _chainId
---
>     string calldata _URI
```
 
@julien51 I remember we did this change for multichain compat, right?

**Review by julien51 — APPROVED** [review]

**Comment by julien51** [comment]
Weird, I am not really sure what is going on here :/

**Comment by clemsos** [comment]
Ok merging with just Unlock v10. Will add PublicLock in another PR

**Pull request merged**
