### PR TITLE
feat(unlock-app): Enable tailwind preflight

### PR DESCRIPTION
**Pull request by searchableguy**
# Description
This enables preflight for tailwind. This breaks quite a few existing styling assumption so please check all the important pages. I have tried to fix whatever I found possible.

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
I did end up changing the design a bit on the account wrapper but not a lot.

**Comment by julien51** [comment]
I like that change!

**Comment by searchableguy** [comment]
image

now?

**Comment by julien51** [comment]
ha! Can you split so that both lines are the same size please?
Also now that I think about it, red migth be a bit strong for the disconnect button? Can we just make it grey?

**Comment by searchableguy** [comment]
image

**Review by julien51 — APPROVED** [review]

**Pull request merged**
