### PR TITLE
Unlock.sol Gas Optimized Contract Now 

### PR DESCRIPTION
**Pull request by DevABDee**
# Description

unlcok.sol had many `require` statements with Error Messages. It was making it too much gas costly. As error messages were storing a full length of strings.
So I replace those `require` statements with the `Custom Errors`. Now the contract is more gas optimized (Alhumduilah)

It's saving **162646 Gas** (this is execution cost and obv the function calling gas is reduced as well)

Before Gas Optimization:
beforeUnlock

After Gas Optimization:
afterUnlock

# Issues

Fixes - Gas Optimization  
Refs #9417 

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [-] I have commented my code, particularly in hard-to-understand areas // My changes do not need those, the core is pretty self-explanatory.
- [-] I have updated the docs to reflect my changes if applicable  // My changes does not needed that also
- [-] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works // My changes does not needed that aswell
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

I hope that the Unlock Team & Community will appreciate my small contribution to this beautiful project.

Thanks,
AB Dee.

### CODE REVIEW

**Comment by julien51** [comment]
@DevABDee Thanks a lot of for your contribution here! 

However I think you need to update the tests because these are _absolutely_ needed :)

**Comment by DevABDee** [comment]
> @DevABDee Thanks a lot for your contribution here!
> 
> However I think you need to update the tests because these are _absolutely_ needed :)

Hey @julien51, Thanks for reviewing.

Actually, all the unit tests are clear (and they should be because the changes I made it's just a replacement of simple pieces of code.)
The only problem is that the Bot is not allowing me xD
See this:
test11111
test22222


The Bot is responding this:
> Thank you for your pull request and welcome to Unlock! We require contributors to sign our [Contributor License Agreement](https://github.com/unlock-protocol/unlock/blob/master/CLA.txt), and we don't seem to have the users @DevABDee on file. In order for us to review and merge your code, please contact us (easiest way is to [open an issue](https://github.com/unlock-protocol/unlock/issues)) to get yourself added.

I have no idea what should I do to get added to the list. I have already opened issue #9417 & Read the CLA.
So pls guide me and add me to the contributors' list.
Thanks

**Review by clemsos — APPROVED** [review]

**Comment by clemsos** [comment]
Cool work @DevABDee ~  thanks for this ! I like the prefix on custom errors and may actually keep for other contracts

**Comment by DevABDee** [comment]
Finally!!!!! :D

**Comment by clemsos** [comment]
> Finally!!!!! :D

Aug 3, 2022...

**Pull request merged**
