### PR TITLE
Adding me to the team in the about page

### PR DESCRIPTION
**Pull request by cnasc**
# Description
Adding me to the team in the about page.

screen shot 2019-01-16 at 5 17 18 pm

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

**Comment by cellog** [comment]
since we have a storybook story that is used in testing, these changes break the snapshots. You can fix the build by running `npm test -- -u` and committing the changed snapshot. Love the bio!

**Comment by julien51** [comment]
Ha! Let's talk about that PR when you're back. There is normally a template which is added by default and gives you info about what to do on a PR... for example you're missing a screenshot here ;p

**Comment by cnasc** [comment]
I really need to start remembering to update snapshots

**Comment by julien51** [comment]
Ha! that's what Travis is for ;p

**Comment by julien51** [comment]
Welcome to the team ;)

**Comment by cnasc** [comment]
Glad to be here!

**Pull request merged**
