### PR TITLE
Circle CI force all tests to run on master/production

### PR DESCRIPTION
**Pull request by clemsos**
Seems like tests arent running on master anymore
# Description

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
The failure is because the database does not get reset before running tests :(

**Comment by clemsos** [comment]
> The failure is because the database does not get reset before running tests :(

yep :) https://github.com/unlock-protocol/unlock/pull/7814

**Comment by clemsos** [comment]
also figured out there was a typo in github actions that were causing all tests to run all the time... 1436fc0

**Comment by clemsos** [comment]
This also fixed a typo in gh actions that was forcing all tests to run

**Review by julien51 — APPROVED** [review]

**Pull request merged**
