### PR TITLE
Adds an introduction for Akeem Adeniji

### PR DESCRIPTION
**Pull request by akeem**
Updates the Unlock about page with an image and brief intro for Akeem.

screen shot 2018-12-10 at 4 09 34 pm

### CODE REVIEW

**Comment by julien51** [comment]
Hey! do you mind adding a screenshot? 
the "guidelines" is that when you change the visual aspect of something you should always submit a screenshot in the PR.

**Comment by akeem** [comment]
No worries, and will also escape the character causing the build to fail

**Comment by benwerd** [comment]
Hanging back for my review until tests pass, but 🎉🎉🎉 for this awesome milestone!

**Comment by akeem** [comment]
thank you!

**Pull request merged**
