### PR TITLE
Upgrading Truffle to 4.15

### PR DESCRIPTION
**Pull request by hardlydifficult**
# Description

This bumps the Solidity version to 0.4.25.  Context on the changes is in comments here: https://github.com/unlock-protocol/unlock/pull/1046.  

tldr: This is a minor bug fix update.

Note that due to our approach to versioning, we must change the source files at the same time the package.json is modified.  However it's effectively just config.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

**Comment by hardlydifficult** [comment]
Good question. No. I ran the Truffle tests but assumed Travis CI would handle other testing required.  What are the commands I should execute? And out of curiosity do we have an issue about what's missing from Tavis?

**Comment by nfurfaro** [comment]
I don't know about an issue about what's missing from Travis.
I usually run the tests in `unlock-app` myself as they're quick, but Travis will run them too.
As far as running dev, in `/unlock-app/` run `npm run dev`.

**Comment by nfurfaro** [comment]
Then go to your dashboard, `create lock`, submit, wait for 6 confirmations and then click the `</>` show embed code button, then click the "eye" icon ("Preview Lock").
You should end up here:
image

**Comment by nfurfaro** [comment]
@hardlydifficult I checked out your branch and ren dev, got a bunch of these:
```
PublicLock.sol:1:1: SyntaxError: Sourcefile requires different compiler version (current compiler is 0.4.24+commit.e67f0147.Emscripten.clang - note that nightly builds are consideredto be strictly less than the released version
pragma solidity 0.4.25;
```

**Comment by hardlydifficult** [comment]
> wait...sorry. I probably need to install deps first.

You can check version with `truffle version`.  If you have truffle installed globally, you may need to run `npm update -g truffle`

**Comment by julien51** [comment]
@nfurfaro Thanks for extra care here. I think this is good practice, even though now, at least, Travis should run all the tests before giving the green light.

_That said_, on this PR, for some reason Travis has not run the "branch" build? I am not sure why. The good news is that the Pull Request tests have passed (and after checking the logs I can confirm that all parts of the app were indeed tested).

@hardlydifficult In a matter of extra-care, do you mind closing this PR and opening a new one (feel free to point to this one) to make sure that Travis does tun these other tests too? Thanks a lot...

**Pull request merged**
