### PR TITLE
Add role revoked to remove Lock manager

### PR DESCRIPTION
**Pull request by briankwong65**
# Description

Add RoleRevoked handler to remove Lock manager

# Issues

https://github.com/unlock-protocol/unlock/issues/13362

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
@briankwong65 please complete the CLA nbot step in _another PR_.

**Comment by julien51** [comment]
Also, this PR does not include any tests... Please add tests so we can make sure this is working as expected.

**Comment by StephanGerbeth** [comment]
Is there any support neccessary?

**Comment by briankwong65** [comment]
> @briankwong65 please complete the CLA nbot step in _another PR_.

https://github.com/unlock-protocol/unlock/pull/14228

**Comment by julien51** [comment]
@briankwong65 Thanks! Please add tests!

**Comment by julien51** [comment]
Hey @briankwong65 any progress here please?

**Comment by julien51** [comment]
ok, closing because this is stale.

**Pull request closed without merging**
