### PR TITLE
feat(unlock-app) - change card color when ticket is checked in

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
Screenshot 2022-07-12 at 18 41 17

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
I think we need a stronger indication that this ticket has already been checked in. 
Maybe change the title of the card to "Already Checked-in"!

**Comment by searchableguy** [comment]
Yeah, I think that would work better.

**Comment by kalidiagne** [comment]
Changes style and also update the title when checkedIn

Screenshot 2022-07-12 at 18 52 39

**Review by julien51 — APPROVED** [review]

**Review by searchableguy — APPROVED** [review]

**Comment by kalidiagne** [comment]
Title now include betters info about checked in times 

Screenshot 2022-07-12 at 19 37 56

**Comment by searchableguy** [comment]
Merging because I need the changes. :)

**Pull request merged**
