### PR TITLE
feature(unlock-app): Remove events in an event collection

### PR DESCRIPTION
**Pull request by 0xTxbi**
# Description
This PR introduces the ability to remove events from a given collection.

## ScreenGrab
Screenshot 2024-09-25 at 16 55 38

## Flow
[Loom](https://www.loom.com/share/1bd718bf62b347b6b88cc2c55b9c7c20)

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
@0xTxbi I would love to see screenshots + a recording here!

**Comment by 0xTxbi** [comment]
> @0xTxbi I would love to see screenshots + a recording here!

sure thing! done!

**Comment by julien51** [comment]
Hey @0xTxbi I am concerned that you seemed to have implemented a whole new UI for lists. Any reason for this?

**Comment by 0xTxbi** [comment]
> Hey @0xTxbi I am concerned that you seemed to have implemented a whole new UI for lists. Any reason for this? 

merely an initial draft to explore a contextual accurate way of displaying multiple events whilst facilitating bulk selection and pagination.

should it be replaced with the approach currently used to display event attendees?

**Review by julien51 — APPROVED** [review]
ok, LGTM. please fix the conflicts!

**Pull request merged**
