### PR TITLE
Production Deploy

### PR DESCRIPTION
**Pull request by julien51**
Production manual Deploy production-20240311-210336

This is a production deployment. Please treat with great caution!
This deploys the code from the *master* branch as of commit db666a62334d0272531b4da720c874cd17043c40.

Reviewing this Pull Request's code is impractical; however, you are asked to check whether the current staging environment is stable and could be released. For this, follow these steps:

* [x] The staging environment has been fully deployed
* [x] This pull request has no conflicts with the `production` branch.
* [x] Go to http://staging.unlock-protocol.com/ and ensure that the website loads fine.

## Creator Dashboard
* [x] Click on the "Go to your Dashboard" button and ensure that the dashboard loads as expected
* [x] Create a new Lock (using a test net is the best option) and wait for it to confirm with the right values
* [x] Update the price on this new lock or an older lock
* [x] Enable credit cards on one of your locks
* [x] Withdraw funds on one of the locks

## Paywall
* [x] From the dashboard, open the Demo on one of your locks
* [x] Purchase a key to the lock using your crypto wallet
* [x] Make sure the content gets unlocked (is shown)
* [x] Refresh the page and make sure the content is still unlocked

## Purchase URL
* [x] From the dashboard, create a purchase URL (redirect URL does not matter)
* [x] In the purchase URL, configure metadata collection to collect an email address, as well as at least one other  of data
* [x] By using a recent lock, enable multiple purchases in the URL
* [x] Go through the checkout flow and ensure that it works as expected (data is collected for 2 users + and 2 keys are minted)

## Verification 
* [x] Add a separate address as a verifier
* [x] Create QR code for one of the valid NFT you own and check in using your phone or laptop camera
* [x] Check if metadata is displayed when you are a verifier and check-in is persistent from the members' page.

# Payments methods
## Credit Card flow for Unlock User accounts
* [x] Open the demo for a lock that has credit card enabled
* [x] Follow the steps to unlock using a credit card as a new user
* [x] Make sure unlocking works successfully
* [x] Connect to the keychain using your Unlock credentials
* [x] Ensure the key you just purchased is there

## Swap & purchase
* [x] Update the currency for a lock (e.g. USDC) to enable swap & purchase 
* [x] Open the demo for the lock with the updated currency
* [x] Make sure that swap & purchase is enabled as payment method
* [x] Use swap and purchase and make sure that unlocking works successfully

## Custom credit card price
* [x] Open settings for a lock and go to payments.
* [x] Enable custom credit card and set a fixed price
* [x] Go through the checkout flow and ensure that the custom price correctly shows as the price for the lock
* [x] Make sure that purchase with custom price works successfully

### CODE REVIEW

**Comment by julien51** [comment]
a few extra things to check thoroughly:
* [ ] scan des QR code + "check in" 
* [ ] creating Unlock accounts

**Comment by clemsos** [comment]
Had a failure with credit card here with `{message: "Price diverged by more than 3%. Aborting"}` in the console (not visible to users though)

**Comment by clemsos** [comment]
The credit card total appears wrong here 

Screenshot 2024-03-12 at 11 06 07

**Comment by clemsos** [comment]
Regarding metadata with tickets, if you buy several tickets with the same EOA address, should the metadata always be identical ?

What I did :

- buy a ticket without metadata (token id 1)
- create checkout w metadata 
- buy another ticket with metadata (token id 2)
- result: both token id 1 and token id 2 has the same metadata

Is that expected ?

**Comment by julien51** [comment]
> Had a failure with credit card here with {message: "Price diverged by more than 3%. Aborting"} in the console (not visible to users though).

Ok, was there a lot of time between the time you started the process and the time you finished it? 
Would you mind retrying it?


> The credit card total appears wrong with credit card at a fixed price (should be 7 + 2.90 + 0.70 = 10.60)

Yeah it's missing the "minting fee (gas)" line. Can u please open an issue for this? I can add+hotfix today.

> Is that expected ?

Yes because the metadata by default is attached to the owner address. That way it doesn't "leak" when the ticket is transferred.

**Comment by clemsos** [comment]
> Had a failure with credit card here with `{message: "Price diverged by more than 3%. Aborting"}` in the console (not visible to users though).
> 
> Minting worked with a fixed price though

ok that worked on a 3rd try. It should be Sepolia gas flucutations

**Review by clemsos — APPROVED** [review]

**Pull request merged**
