### PR TITLE
Issue #334 Infinite number of keys

### PR DESCRIPTION
**Pull request by chiro-hiro**
Fixes #

## Proposed Changes

- Allowed user to set unlimited number of keys by click *unlimited* label
- Display unlimited lock in dashboard

### CODE REVIEW

**Comment by chiro-hiro** [comment]
Screenshot:
1. Create new lock
image
2. Click Unlimited label
image

**Comment by julien51** [comment]
Thanks! These look great, but you're still missing the tests + storybooks...
Also, I added a bounty, please apply ASAP ;p

**Comment by cellog** [comment]
Thank you!

**Comment by chiro-hiro** [comment]
Thanks for the guideline ;)

**Comment by cellog** [comment]
@julien51 is there a way to re-run the deploy so we can merge?

**Comment by cellog** [comment]
I'm going to assume netlify is a fluke and merge this

**Pull request merged**
