### PR TITLE
fix formatting issue

### LINKED ISSUE #763: Creator Dashboard Account Menu Labels Missing
**Describe the bug**
The labels on the account menu on the creator dashboard are missing
screen shot 2018-12-18 at 17 10 58

**Expected behavior**
Like the menu on the landing page the menu icons should display a label on hover.
screen shot 2018-12-18 at 17 14 18

### PR DESCRIPTION
**Pull request by cellog**
Fixes #763 

 - The buttons were not using LayoutButton.
 - as="button" was not being used, so remove it
 - use action with a dummy to prevent the link from doing anything, since we don't support it yet

### CODE REVIEW

**Comment by julien51** [comment]
Screenshots? Also I think the *real* fix for now is to remove these icons since there is no implementation on them at this stage!

**Comment by cellog** [comment]
I agree. I'll remove them and resubmit with screenshots

**Comment by cellog** [comment]
still working on this, will be ready momentarily

**Comment by cellog** [comment]
Removed buttons. I also made it simpler to re-enable the buttons, and added labels to `Download` and `ExportLock` for when we eventually want to enable them for post-version 0.

@benwerd this should address your concern about LayoutButton as well. I discovered that `Button` and `LayoutButton` have the same behavior with regards to label, so I put it back to `Button` and visual behavior is still desired

@smombartz I changed Button so that if `label` prop is set, but no `title` we use the `label` as a `title` for accessibility. Please weigh in on whether that is an OK change. I added labels to all of the `src/interface/Button` components as well and we may want to wordsmith those (@julien51).

screen shot 2018-12-19 at 11 11 26 am

**Comment by cellog** [comment]
@julien51 @smombartz ready for re-review

**Comment by cellog** [comment]
Screenshots of changes to buttons

screen shot 2018-12-19 at 12 55 23 pm
screen shot 2018-12-19 at 12 55 14 pm
screen shot 2018-12-19 at 12 54 38 pm
screen shot 2018-12-19 at 12 54 32 pm
screen shot 2018-12-19 at 12 54 20 pm
screen shot 2018-12-19 at 12 54 12 pm
screen shot 2018-12-19 at 12 54 01 pm
screen shot 2018-12-19 at 12 53 55 pm
screen shot 2018-12-19 at 12 53 43 pm
screen shot 2018-12-19 at 12 53 37 pm
screen shot 2018-12-19 at 12 53 23 pm
screen shot 2018-12-19 at 12 53 01 pm
screen shot 2018-12-19 at 12 52 28 pm
screen shot 2018-12-19 at 12 52 12 pm
screen shot 2018-12-19 at 12 47 58 pm
screen shot 2018-12-19 at 12 47 20 pm
screen shot 2018-12-19 at 12 47 07 pm
screen shot 2018-12-19 at 12 46 58 pm
screen shot 2018-12-19 at 12 46 42 pm

**Pull request merged**
