### PR TITLE
Switch to openzeppelin-solidity (from -eth) for the lock

### PR DESCRIPTION
**Pull request by hardlydifficult**
# Description

`openzeppelin-solidity` is similar to `openzeppelin-eth`, however `-eth` contracts have been modified to support upgrading. We need those for `Unlock` but not for the `PublicLock` contract. One of the features used for upgrading is a "gap" variable (reserving space for future use) - which increases the gas cost.

Switching the PublicLock imports to use `-solidity` with one exception, `Ownable`.  There is a limitation in the Solidity compiler which allows for only one contract per name and since we need the initializable version of Ownable for Unlock we cannot import the normal version insider PublicLock without causing an error.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Wait, I thought we *needed* to use `openzeppelin-eth`?
https://github.com/unlock-protocol/unlock/pull/720

**Comment by julien51** [comment]
I'll let @nfurfaro weigh in on that because he worked on the migration in the other direction in https://github.com/unlock-protocol/unlock/pull/720

**Comment by hardlydifficult** [comment]
Correct, we need it for `Unlock` since it's upgradable but when it comes to the `PublicLock`, using `-eth` costs more without any benefit.

**Comment by nfurfaro** [comment]
As I mentioned earlier, The only (potential) downside to this PR is that it explicitly required us to have both oz-eth and oz-solidity as dependencies...but, as `zos-lib` requires oz-solidity anyway, this is functionally no different from what we already have going on.

**Comment by hardlydifficult** [comment]
Yes, that is a downside.  The conflict with Ownership is an example of that concern.  I think we strongly prefer `-eth` anytime a conflict arises, otherwise use `-solidity` where we can for gas optimizations.

**Pull request merged**
