### PR TITLE
Paywall-configuration

### PR DESCRIPTION
**Pull request by ManyRios**
# Description

# Issues

https://github.com/unlock-protocol/unlock/issues/7492

### CODE REVIEW

**Comment by ManyRios** [comment]
don't have permissions to "]Package". It is in master branch...

**Comment by ManyRios** [comment]
I NEED A FEEDBACK HERE

**Comment by julien51** [comment]
Hi! Can you open another/different PR with only one thing: your username added to the `.clabot` file? 

Also, could you document how to easily add this built react app into a static HTML document? This would make things easier for us!

**Comment by julien51** [comment]
> don't have permissions to "]Package". It is in master branch...
Please move files to `https://github.com/unlock-protocol/unlock/tree/master/packages`

**Pull request closed without merging**
