### PR TITLE
Remove the onlyKeyManager modifier

### PR DESCRIPTION
**Pull request by NickCuso**
# Description

Removing onlyKeyManager and using onlyKeyManagerOrApproved instead. I'm not sure there's ever a use case where we do not want both.

However after looking at this I think we should clear approval when the keyManager is changed. Will follow up with another PR.

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [x] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by nfurfaro** [comment]
Based on this doc there are (currently) a number of such cases. We can review and see if this is still accurate.

https://docs.google.com/document/d/11bP7OjY2ei_NO1pzYOoTlrvQ1_9AtqXfmtgwZUYMwY0/edit?pli=1#heading=h.cnmy30f2sp2u

**Comment by nfurfaro** [comment]
>However after looking at this I think we should clear approval when the keyManager is changed.
Yeah I agree here.

**Comment by NickCuso** [comment]
Hmm I think that was a miss when we reviewed this.

Do you remember the rational?
To me it seems to violate the intent of approval - basically I'm approving an operator to act on my behalf. The could transfer the key to themselves and then cancel anyways

**Comment by nfurfaro** [comment]
>The could transfer the key to themselves and then cancel anyways

True. Once they transfer to themselves they would become the keyManager anyway and gain access.

**Pull request merged**
