### PR TITLE
Smart-contracts uses Eslint 6

### PR DESCRIPTION
**Pull request by cnasc**
# Description

Updating the smart contracts to use Eslint 6. All of the code changes in here were done automatically by `eslint --fix`. For the ones it could not do automatically, I added them as exceptions in the `.eslintrc.js`

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cnasc** [comment]
Looks like the automatically-applied fixes break the tests by assuming later JS features than are available in this subrepo. Not sure if we do any transpiling here, but we'll either need to change it or introduce it if we want to use the same lint config as everything else.

**Comment by NickCuso** [comment]
Hmm not sure, but maybe this is because truffle uses babel 6 instead of babel 7 (?)

**Comment by cnasc** [comment]
None of these are critical since we only use JS for tests here; we lived without them before this update. Not updating ESLint for the time being is a valid path.

**Comment by NickCuso** [comment]
Hmm we could also look for which lint rule is breaking our tests and then turn those rules off in config.  That could allow us to keep a consistent style across repos.

**Comment by cnasc** [comment]
The one that shows the failure is this one: https://eslint.org/docs/rules/prefer-object-spread

I'll try to peel it back further and see if I can make it pass, not sure if any others will fail after this is resolved.

**Comment by cnasc** [comment]
Closing in favor of #5656

**Pull request closed without merging**
