### PR TITLE
feat(unlock-app) - fix zoom on input focus mobile

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
Prevent zooming page when an input is focused

**Issue**

Screenshot 2023-03-17 at 11 03 37

**Fix**

Screenshot 2023-03-17 at 11 06 42

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
This prevents any kind of zooming though. I don't think this is good for accessibility.

**Comment by kalidiagne** [comment]
> This prevents any kind of zooming though. I don't think this is good for accessibility.

This will prevent the zoom when input is focused, user will be able to zoom with "pinch to zoom" action

**Comment by searchableguy** [comment]
This will prevent zooming on android phones and other browsers. 

I think a real solution is to set font size to 16px at least on input which would avoid this zoom.

**Comment by julien51** [comment]
@kalidiagne What's the stastus here? Can you do what @searchableguy suggested and see if that works better?

**Comment by kalidiagne** [comment]
> @kalidiagne What's the stastus here? Can you do what @searchableguy suggested and see if that works better?

Added font size to 16px on mobile to prevent zooming 

Screenshot 2023-03-24 at 14 33 47

**Review by julien51 — APPROVED** [review]

**Pull request merged**
