### PR TITLE
feat(unlock-app) - app header component

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description

**Not logged**

Screenshot 2022-09-27 at 21 12 21

**Logged**

Screenshot 2022-09-27 at 21 14 14

**Switch network**

Screenshot 2022-09-27 at 21 26 48

**Network selection mobile**

Screenshot 2022-09-27 at 21 10 35

Screenshot 2022-09-27 at 20 52 22

**Component in pages**

Screenshot 2022-09-27 at 21 18 40

Screenshot 2022-09-27 at 21 18 53

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Review by searchableguy — APPROVED** [review]
LGTM

**Comment by julien51** [comment]
I think it is too early for now but I wonder if we can eventually just remove the button to switch the network because it is not that useful anymore?

**Comment by searchableguy** [comment]
@julien51 I think it won't go anywhere in near future as long as wallet can't switch network without explicit approval for transactions.

**Comment by julien51** [comment]
> @julien51 I think it won't go anywhere in near future as long as wallet can't switch network without explicit approval for transactions.

Well yes I'd still want to ask the user to switch but only when they need to... (ie when they are about to send a transaction)

**Pull request merged**
