### PR TITLE
feat(unlock-app): Checkout redesign

### PR DESCRIPTION
**Pull request by searchableguy**
# Description

This adds redesigned checkout at `/alpha/checkout` path.

I'm adding some URLs below which you can use to test the flow.

### Local

[Local with everything enabled](http://localhost:3000/alpha/checkout?paywallConfig=%7B%22title%22:%22Bakery.fyi%22,%22locks%22:%7B%220xff6e45FdE991cf534d0253e241743cf4238b21D9%22:%7B%22name%22:%22Basic%22,%22network%22:4%7D,%220x582eCeFA60c350d82EAf169df0035f3DDaCC795D%22:%7B%22name%22:%22Premium%22,%22network%22:4%7D,%220xCE62D71c768aeD7EA034c72a1bc4CF58830D9894%22:%7B%22network%22:100,%22name%22:%22Outer%20world%22%7D%7D,%22messageToSign%22:%22You%20agree%20to%20our%20terms%20and%20conditions%20listed%20at:%20https://example.com/tos%22,%22icon%22:%22https://i.ibb.co/sQkJxhb/Ellipse-56.png%22,%22callToAction%22:%7B%7D,%22metadataInputs%22:%5B%7B%22name%22:%22Email%22,%22type%22:%22email%22,%22required%22:true,%22public%22:false%7D,%7B%22name%22:%22Name%22,%22type%22:%22text%22,%22required%22:true%7D%5D,%22pessimistic%22:true%7D)

[Recurring lock enabled](http://localhost:3000/alpha/checkout?redirectUri=https%3A%2F%2Fwww.example.com&paywallConfig=%7B%22locks%22%3A%7B%220x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3%22%3A%7B%22network%22%3A4%2C%22recurringPayments%22%3A3%7D%7D%2C%22pessimistic%22%3Atrue%2C%22persistentCheckout%22%3Atrue%2C%22icon%22%3A%22https%3A%2F%2Fstaging-locksmith.unlock-protocol.com%2Flock%2F0x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3%2Ficon%22%7D)

[Without metadata](http://localhost:3000/alpha/checkout?paywallConfig=%7B%22title%22:%22Bakery.fyi%22,%22locks%22:%7B%220xff6e45FdE991cf534d0253e241743cf4238b21D9%22:%7B%22name%22:%22Basic%22,%22network%22:4%7D,%220x582eCeFA60c350d82EAf169df0035f3DDaCC795D%22:%7B%22name%22:%22Premium%22,%22network%22:4%7D,%220xCE62D71c768aeD7EA034c72a1bc4CF58830D9894%22:%7B%22network%22:100,%22name%22:%22Outer%20world%22%7D%7D,%22messageToSign%22:%22You%20agree%20to%20our%20terms%20and%20conditions%20listed%20at:%20https://example.com/tos%22,%22icon%22:%22https://i.ibb.co/sQkJxhb/Ellipse-56.png%22,%22callToAction%22:%7B%7D,%22pessimistic%22:true,%22captcha%22:true,%22maxRecipients%22:5%7D)

[Without message to sign](http://localhost:3000/alpha/checkout?paywallConfig=%7B%22title%22:%22Bakery.fyi%22,%22locks%22:%7B%220xff6e45FdE991cf534d0253e241743cf4238b21D9%22:%7B%22name%22:%22Basic%22,%22network%22:4%7D,%220x582eCeFA60c350d82EAf169df0035f3DDaCC795D%22:%7B%22name%22:%22Premium%22,%22network%22:4%7D,%220xCE62D71c768aeD7EA034c72a1bc4CF58830D9894%22:%7B%22network%22:100,%22name%22:%22Outer%20world%22%7D%7D,%22icon%22:%22https://i.ibb.co/sQkJxhb/Ellipse-56.png%22,%22callToAction%22:%7B%7D,%22pessimistic%22:true,%22captcha%22:true,%22maxRecipients%22:5%7D)

[Connect](http://localhost:3000/alpha/checkout?client_id=www.ouvre-boite.com&redirect_uri=https%3A%2F%2Fwww.ouvre-boite.com%2F)

### Staging
[Staging with everything enabled](https://staging-app.unlock-protocol.com/alpha/checkout?paywallConfig=%7B%22title%22:%22Bakery.fyi%22,%22locks%22:%7B%220xff6e45FdE991cf534d0253e241743cf4238b21D9%22:%7B%22name%22:%22Basic%22,%22network%22:4%7D,%220x582eCeFA60c350d82EAf169df0035f3DDaCC795D%22:%7B%22name%22:%22Premium%22,%22network%22:4%7D,%220xCE62D71c768aeD7EA034c72a1bc4CF58830D9894%22:%7B%22network%22:100,%22name%22:%22Outer%20world%22%7D%7D,%22messageToSign%22:%22You%20agree%20to%20our%20terms%20and%20conditions%20listed%20at:%20https://example.com/tos%22,%22icon%22:%22https://i.ibb.co/sQkJxhb/Ellipse-56.png%22,%22callToAction%22:%7B%7D,%22metadataInputs%22:%5B%7B%22name%22:%22Email%22,%22type%22:%22email%22,%22required%22:true,%22public%22:false%7D,%7B%22name%22:%22Name%22,%22type%22:%22text%22,%22required%22:true%7D%5D,%22pessimistic%22:true%7D)

[Recurring lock enabled](https://staging-app.unlock-protocol.com/alpha/checkout?redirectUri=https%3A%2F%2Fwww.example.com&paywallConfig=%7B%22locks%22%3A%7B%220x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3%22%3A%7B%22network%22%3A4%2C%22recurringPayments%22%3A3%7D%7D%2C%22pessimistic%22%3Atrue%2C%22persistentCheckout%22%3Atrue%2C%22icon%22%3A%22https%3A%2F%2Fstaging-locksmith.unlock-protocol.com%2Flock%2F0x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3%2Ficon%22%7D)

[Without metadata](https://staging-app.unlock-protocol.com/alpha/checkout?paywallConfig=%7B%22title%22:%22Bakery.fyi%22,%22locks%22:%7B%220xff6e45FdE991cf534d0253e241743cf4238b21D9%22:%7B%22name%22:%22Basic%22,%22network%22:4%7D,%220x582eCeFA60c350d82EAf169df0035f3DDaCC795D%22:%7B%22name%22:%22Premium%22,%22network%22:4%7D,%220xCE62D71c768aeD7EA034c72a1bc4CF58830D9894%22:%7B%22network%22:100,%22name%22:%22Outer%20world%22%7D%7D,%22messageToSign%22:%22You%20agree%20to%20our%20terms%20and%20conditions%20listed%20at:%20https://example.com/tos%22,%22icon%22:%22https://i.ibb.co/sQkJxhb/Ellipse-56.png%22,%22callToAction%22:%7B%7D,%22pessimistic%22:true,%22captcha%22:true,%22maxRecipients%22:5%7D)

[Without message to sign](https://staging-app.unlock-protocol.com/alpha/checkout?paywallConfig=%7B%22title%22:%22Bakery.fyi%22,%22locks%22:%7B%220xff6e45FdE991cf534d0253e241743cf4238b21D9%22:%7B%22name%22:%22Basic%22,%22network%22:4%7D,%220x582eCeFA60c350d82EAf169df0035f3DDaCC795D%22:%7B%22name%22:%22Premium%22,%22network%22:4%7D,%220xCE62D71c768aeD7EA034c72a1bc4CF58830D9894%22:%7B%22network%22:100,%22name%22:%22Outer%20world%22%7D%7D,%22icon%22:%22https://i.ibb.co/sQkJxhb/Ellipse-56.png%22,%22callToAction%22:%7B%7D,%22pessimistic%22:true,%22captcha%22:true,%22maxRecipients%22:5%7D)

[Connect](https://staging-app.unlock-protocol.com/alpha/checkout?client_id=www.ouvre-boite.com&redirect_uri=https%3A%2F%2Fwww.ouvre-boite.com%2F)

There is a `getPaywallConfig.ts` script inside scripts folder in `unlock-app` which can be modified and ran to generate a new URL with different configuration. @julien51 
You can use `ts-node script.ts` or `deno run script.ts` to run it.

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
I wonder why we push generated artifacts for assets package. It really messes up differential view.

**Comment by searchableguy** [comment]
> > I wonder why we push generated artifacts for assets package. It really messes up differential view.
> 
> 
> Indeed, that is weird. Also, weird that they generate differently for you?

That is likely due to version difference (we moved from v5 to v6 svg components in recent update PR). I don't think there should be a change in the appearance for most part.

**Comment by julien51** [comment]
> That is likely due to version difference (we moved from v5 to v6 svg 2 components in recent update PR). I don't think there should be a change in the appearance for most part.

Ok then let's isolate that into a first PR please.
Similarly if you could isolate some of the renaming into their own PR that would be helpful (no need to. change the *new* files as we can merge the renamings first)

**Comment by searchableguy** [comment]
How to force run the tests? @clemsos

**Review by julien51 — APPROVED** [review]

**Pull request merged**
