### PR TITLE
adding the lock spinner when the locks have not been loaded yet

### PR DESCRIPTION
**Pull request by julien51**
# Description

Our UI is broken as long as the locks have not been loaded (see screenshot below sent by... Forbes). @sascha worked on a small "wait screen" to indicate to users that something _will_ happen.
The next mission is going to make tthat *something* happen faster.

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [X] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
image

**Comment by julien51** [comment]
After:

image

**Comment by cnasc** [comment]
I think you forgot to commit a file

**Comment by julien51** [comment]
Thx!

**Pull request merged**
