### PR TITLE
feat(subgraph) - add balance to subgraph

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
Add subgraph to `subgraph`

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by clemsos** [comment]
I think there is a misunderstanding there. The `balanceOf` function does not return the ETH or ERC20 balance of the lock. It will return the number of valid keys for a specific user - see [here](https://docs.unlock-protocol.com/core-protocol/smart-contracts-api/PublicLock#balanceof).

What you want here is how much ETH or ERC20 is in the lock? I will say that is going to be kind of hard to track with the graph as we may lack some of the functions that affects the balance :/ 

I think it may be better to get it directly from the RPC / ERC20 contract directly, no? This is quite the critical info people are looking at and we dont want to have inaccurate data here. 

wdyt?

**Comment by kalidiagne** [comment]
> I think there is a misunderstanding there. The `balanceOf` function does not return the ETH or ERC20 balance of the lock. It will return the number of valid keys for a specific user - see [here](https://docs.unlock-protocol.com/core-protocol/smart-contracts-api/PublicLock#balanceof).
> 
> What you want here is how much ETH or ERC20 is in the lock? I will say that is going to be kind of hard to track with the graph as we may lack some of the functions that affects the balance :/
> 
> I think it may be better to get it directly from the RPC / ERC20 contract directly, no? This is quite the critical info people are looking at and we dont want to have inaccurate data here.
> 
> wdyt?

Yes, what I mean here with `balance` is the total balance that can be withdrawn for the lock.
I get your point here, for now, I think we can get it directly from the contract for when needed.

@julien51 wdyt?

**Comment by julien51** [comment]
> What you want here is how much ETH or ERC20 is in the lock? I will say that is going to be kind of hard to track with the graph as we may lack some of the functions that affects the balance :/

That's a good point. We _could_ still use the PublicLock events and then retrieve the balance from the ERC20 contract but you are correct that this would miss some data (for example if an ERC20 transfer to the lock happens _without_ a `purchase`).

So indeed I think the best way to get the balance of every lock is to use `getBalance` on web3Service for each lock? This should still be MUCH faster since it's a single call (maybe 2 to get decimals...) but at least were not querying _all_ of the PublicLock stuff.

**Comment by julien51** [comment]
@kalidiagne Let me know if you need more clarification about this...

**Comment by kalidiagne** [comment]
not needed, balanced added to `web3service`

**Pull request closed without merging**
