### PR TITLE
Define transferFee and allow it to be changed

### PR DESCRIPTION
**Pull request by hardlydifficult**
# Description

Defining a transfer fee amount, and allowing the Lock owner to change it from its default value.

The transfer fee itself is not yet implemented.  This is a first step towards completing that task.

# Issues

Fixes #
Refs #1997 

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
First: I think ideally it needs to be a %. Does that make this hard-er to implement?
The default should be a rather small %, like maybe 5%.

**Comment by hardlydifficult** [comment]
There's no decimal support directly, using a denominator only is a gas optimization.  But maybe that's overkill and we should use percent instead.  To that end, the refund penalty is currently implemented the same way.

We could simply do a `value.mul(percent).div(100)` to work with percents as people expect - but they must be in whole numbers (i.e. 0.5% is not possible).  ....unless we have them enter basis points instead of percent.

The most flexible approach is to accept both a numerator and a denominator (as two uints).  This would allow any value to be expressed.

**Comment by hardlydifficult** [comment]
Oh btw if we go with numerator / denominator for the frontend a library like https://www.npmjs.com/package/fractional does the conversion to make it easy for users to simply enter x%

**Comment by julien51** [comment]
> The most flexible approach is to accept both a numerator and a denominator (as two uints). This would allow any value to be expressed.

👍 let's do that!

**Comment by hardlydifficult** [comment]
done.  Ready for review.

I'll go ahead and change the refund rate as well to be consistent.

**Comment by hardlydifficult** [comment]
It'll default to 5%, and then the Lock owner can make a tx to change it.  We should support changing it to 0 as well.

Looking at this again, maybe we should require the denominator is > 0 on update

**Comment by hardlydifficult** [comment]
Added new require statement and a test for it.

**Pull request merged**
