### PR TITLE
feat(unlock-app) - remove styled component

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
Remove styled component from demo page and update components eg. `Button`

**Locked page**
Screenshot 2022-10-05 at 16 32 49

**Unlocked page**
Screenshot 2022-10-05 at 16 33 42

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
Might wanna style the buttom as custom to match the feel here.

**Comment by julien51** [comment]
I don't thnik it makes sense to use a purple button on the demo page. This content belongs to the "demo site" itself. Can we do a button that's in the same style as the rest of the page (and not like Unlock Labs's content?)
Also, can you change the background on the locked content? It's of a different color :)

**Comment by kalidiagne** [comment]
> I don't thnik it makes sense to use a purple button on the demo page. This content belongs to the "demo site" itself. Can we do a button that's in the same style as the rest of the page (and not like Unlock Labs's content?) Also, can you change the background on the locked content? It's of a different color :)

The background color for the locked content is the same as a prod

Screenshot 2022-10-06 at 09 46 26

**Comment by kalidiagne** [comment]
Style updated 

Screenshot 2022-10-06 at 11 40 34

**Review by searchableguy — APPROVED** [review]

**Pull request merged**
