### PR TITLE
Experiment: Refactor mixins and add approveForAll (ERC721 standard)

### PR DESCRIPTION
**Pull request by hardlydifficult**
# Description

Adding approveForAll, which is required to meet the ERC721 standard.  Since an owner can have up to 1 Key, the impact of this method is very similar to the standard approve - the difference being the approval is not lost when a transfer occurs.

This change only adds a few functions to the contract.  However I have included a refactor with these changes for consideration.  

The goal of this refactor is to simplify our large PublicLock contract.  I have separated a few distinct capabilities into their own file.  e.g. all approval related data and functions are in `MixinERC721Approval.sol`.  I find this makes it easier to read/review functionality (and may encourage re-use as we implement new types of Locks).

Inheritance in Solidity is effectively a copy/paste then compile process - so the impact of this refactor is 100% non-functional (i.e. the bytecode diff from the refactor alone should be null). 

This approach was inspired by 0x, see https://github.com/0xProject/0x-monorepo/tree/development/contracts/exchange/contracts/src

If you are not onboard with this "mixin" approach, I can roll that back while keeping the new approveForAll implementation.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by hardlydifficult** [comment]
@julien51 @nfurfaro could you both take a look at this one, curious how you feel about the refactor.

**Comment by nfurfaro** [comment]
Will review tonight, but I'm  in favor of the approach in general.

**Comment by hardlydifficult** [comment]
To clarify, if we go with this "mixin" design pattern the long term goal is the PublicLock contract is nothing more than a collection of mixin components.  e.g. https://github.com/0xProject/0x-monorepo/blob/development/contracts/exchange/contracts/src/Exchange.sol

**Comment by nfurfaro** [comment]
Would you change the ILockCore interface at all to reflect the mixin pattern, or leave it as is (monolithic)? Functionally it probably doesn't matter, and it still serves its purpose without a big refactor.

**Comment by hardlydifficult** [comment]
That's a good question.  It may be easier to keep one massive ILockCore file - but we should definitively revisit that when we start to add new lock types.

**Comment by hardlydifficult** [comment]
This is an experiment (but I don't think I can downgrade it to a draft PR)

I will be closing this PR down and follow up with a few separate/more targeted PRs.  But do let me know if you have more comments on this approach as I plan on running with it.

**Comment by nfurfaro** [comment]
@hardlydifficult on the subject of interfaces in the context of the mixin pattern:
 I think making use of both interfaces and abstract contracts will likely make sense here. 
For example, `ILockCore` could be implemented as an abstract contract, allowing it to inherit (and compose) the individual pure interfaces behind each mixin...It could also possibly form the backbone of a new type of lock (Private?), but if that didn't make sense we just use a new abstract contract `IPrivateLock.sol` which composes the interfaces it needs (including any new ones we may need to write).

**Comment by hardlydifficult** [comment]
Yea I agree - creating abstract contracts like IPublicLock which bring a few lock interfaces together is a good approach.

**Comment by hardlydifficult** [comment]
Last PR related to this coming shortly.

**Pull request closed without merging**
