### PR TITLE
fix(ci): simplify perms on Dockerfile

### PR DESCRIPTION
**Pull request by clemsos**
# Description

Some improvements to the Docker build time by simplying the way perms are handled. 

That `chown` step was taking several minutes to recurse in node_modules 

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Review by julien51 — APPROVED** [review]
LGTM!

**Comment by clemsos** [comment]
lets wait to see if [88c66d7](https://github.com/unlock-protocol/unlock/commit/88c66d79549630351f8b16bf3901791fab4d5b78) will fix master

**Comment by clemsos** [comment]
closing in favor to #10363

**Pull request closed without merging**
