### PR TITLE
Add storage gaps to PublicLock

### LINKED ISSUE #7919: Adding `__gap` before upgradable locks
Since we're moving forward with upgradable locks, we need to make our mixins "future proof". OpenZeppelin uses `__gap` variables at the end of each contract so that we can add/change storage inside of the mixins without completely changing the structure of these contracts when we want to upgrade them.

All mixins used in `PublicLock` should have a `__gap` method of say 1,000 uint256 slots.

See details on https://github.com/OpenZeppelin/openzeppelin-contracts/blob/0d40f705a7d4a42ff622ae3a0e1a90305fc5b93e/docs/modules/ROOT/pages/upgradeable.adoc#storage-gaps

### PR DESCRIPTION
**Pull request by clemsos**
# Description

For the safety of future upgrades on `PublicLock` contract, we add [storage gaps](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/0d40f705a7d4a42ff622ae3a0e1a90305fc5b93e/docs/modules/ROOT/pages/upgradeable.adoc#storage-gaps) at the end of our mixins.

# Issues

Fixes #7919
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Review by julien51 — APPROVED** [review]
LGTM!

**Comment by clemsos** [comment]
It seems like 1000 is a bit excessive - it will mean adding 1000 variables per mixin... Not sure how much overhead it adds -- see https://github.com/openzeppelin/openzeppelin-contracts-upgradeable/issues/47

**Comment by clemsos** [comment]
Thank you very much @Amxx for the help 🙏🏻  
We'll stick to 1000 then :)

**Comment by julien51** [comment]
Merci @Amxx !

**Comment by frangio** [comment]
I actually think using too big a gap may add to deployment cost (but not runtime cost). The reason is that a bigger slot number requires more bytecode to push onto the stack. Whether it's 1000 or 50 may not make a big difference though because it will likely be above 1 byte anyway.

**Comment by clemsos** [comment]
Thanks @frangio ! Makes sense about deployment costs. It won't be really an issue for us, as we just intend to deploy the template once -- creating new locks will just deploy a proxy using the template as implementaion.

**Pull request merged**
