### PR TITLE
feat(smart-contracts): balanceOf hook for ERC1155

### PR DESCRIPTION
**Pull request by clemsos**
# Description

This adds a mapper contract to assess key validity based on `balanceOf` of a 3rd part ERC1155-compliant token. 

it works in the same way as the existing ERC721 hook, except it takes one more parameter : the token type id.

```
TOKEN_TYPE_ID = 1
createMapping(lock.address, nft.address, TOKEN_TYPE_ID)
```

## Deployments
 
- Mainnet: [0x8ec9FB8FCC5ab6E0bD04EfD9e42A8f6Be45eaeC2](https://etherscan.io/address/0x8ec9FB8FCC5ab6E0bD04EfD9e42A8f6Be45eaeC2)
- Rinkeby : [0xD7477B7c0CdA4204Cf860e4c27486061b15a5AC3](https://rinkeby.etherscan.io/address/0xD7477B7c0CdA4204Cf860e4c27486061b15a5AC3)
- Polygon: [0x0C0cEEcF5C14EBF1Fcf6779F92766128eeE7098C](https://polygonscan.com/address/0x0C0cEEcF5C14EBF1Fcf6779F92766128eeE7098C)
- Binance: [0x3952787d8Ec653E9179a3Fa5D8c018d7bD8e94c7](https://bscscan.com/address/0x3952787d8Ec653E9179a3Fa5D8c018d7bD8e94c7)
- Gnosis/xdai: [0x4F44e968961f5ff818b788E626564BBAF2c96bAC](https://blockscout.com/xdai/mainnet/address/0x4F44e968961f5ff818b788E626564BBAF2c96bAC#code)
- Optimism: [0xF867712b963F00BF30D372b857Ae7524305A0CE7](https://optimistic.etherscan.io/address/0xF867712b963F00BF30D372b857Ae7524305A0CE7#code)

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Very cool! Do you mind deploying this on all the networks we support and add this to the docs too? Thanks!

**Comment by clemsos** [comment]
Deployed an ERC1155 on Rinkeby at [0xA90b661BAACf4cD0ACE9492563C96FEd8fF4dd3d](https://rinkeby.etherscan.io/address/0xA90b661BAACf4cD0ACE9492563C96FEd8fF4dd3d)

To test, just use the `addToken` feature.

code at : https://gist.github.com/clemsos/ce0c5889365b3838e492939f0e33c99b

**Comment by clemsos** [comment]
> Very cool! Do you mind deploying this on all the networks we support and add this to the docs too? Thanks!

maybe good to test it a bit before deploying?

**Comment by clemsos** [comment]
here is a demo lock for Rinkeby with correct setup: https://rinkeby.etherscan.io/address/0x1F8fadd77299700d955D121be86E0C6A407db25A

**Comment by clemsos** [comment]
ok deployed on various chains, and added ERC1155 support to the exiting ERC721 docs

**Review by julien51 — APPROVED** [review]

**Pull request merged**
