### PR TITLE
Make tests pass without automine enabled

### LINKED ISSUE #2466: Run smart contract tests without automine
Our smart contract test suite currently assumes that the nodes are running with "auto-mining" on (each transaction is immediately mined when the node receives it). 
We should remove that assumption and ensure that the smart contract test suite actually runs on any network (not just ganache).

### PR DESCRIPTION
**Pull request by nfurfaro**
# Description
- I adjusted some of the time-based parameters for the failing tests. Most of the issues came from the fact that without automine, we need to wait after certain transactions for the block to be mined before testing to see if certain values have been set on the contract, etc...
As different networks will have different blocktimes, I tried to set worst-case values so they work with mainnet (and so should work with any other network too). 
- I refactored out the `sleep()` function that Nick added into its own module and made more extensive use of it to wait for mining. 
- I tested the entire smart-contract test suite with a blocktime of 3 seconds, and tested individual files with a blocktime of 14 seconds successfully.

# Issues

Fixes #2466
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by nfurfaro** [comment]
I have hardcoded sleep values here, but we could potentially check to see which network the tests are being run on and set values accordingly. Also, even with hardcoded values, we may be able to go lower than what I have (mostly 20 sec). I wanted to be a bit generous to be on the safe side, but mainnet blocktime is only around 14 seconds I believe.

**Comment by julien51** [comment]
Let's extract that 2000 wait value in a single place so we can change it all over in a single change?

**Comment by NickCuso** [comment]
hmm I don't understand why only two tests are impacted?  what's unique about those?

**Comment by nfurfaro** [comment]
This is a good point, and I don't have a good answer yet. I need to look at this some more.

**Comment by julien51** [comment]
Can you actually change the config to disable automine on this PR to make sure it does the trick?

**Comment by nfurfaro** [comment]
>Can you actually change the config 

Yes, i can and will. Note that a block-time of 3 seconds on my machine took close to an hour to run the test suite.

**Comment by julien51** [comment]
@nfurfaro I think this is good then! @NickCuso what do you think?

**Comment by NickCuso** [comment]
I'm not sure I understand the changes here.  But if it works that's fine, we can try and maybe simplify later.

How about we set CI to use a 1-second block time for tests going forward?

**Comment by nfurfaro** [comment]
@julien51 RE:
> Can you actually change the config to disable automine on this PR to make sure it does the trick?

I didn't do this yet...It looks like CI is already using a block time of 3 seconds? ( which is what I was testing with locally).

**Comment by NickCuso** [comment]
I don't believe CI is using 3 seconds for the smart contract tests.  We would have noticed much longer test times, right?

**Comment by nfurfaro** [comment]
You're right, I went digging through the config and was looking at docker/development/standup.sh, but yes, we would definitely notice a blocktime of 3 secs, its painfully slow. Even 1 sec would be slow, but might be worth it.

**Comment by NickCuso** [comment]
I think it's this line https://github.com/unlock-protocol/unlock/blob/0cc647b92f6a2d23fd0e6e75486a41c9911cfbf0/docker/docker-compose.ci.yml#L8

**Comment by nfurfaro** [comment]
Update: Not ready to merge this, as there's now 1 newly-introduced  test failing.

**Comment by nfurfaro** [comment]
Closing, replaced by #5472

**Pull request closed without merging**
