### PR TITLE
feat(networks): add mainnet safe modules addresses

### PR DESCRIPTION
**Pull request by clemsos**
# Description

This adds safe modules addresses to the mainnet network manifest 

# Issues

Fixes #
Refs # #14489

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/mainnet.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0xc9577b38ADA2B1b251EE99e54cC399027d547B68 is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0xe79B93f8E22676774F2A8dAd469175ebd00029FA is verified
- ✅ Contract KeyManager at 0x9A1f43090307034DBFBE2ba20320Ce815ff046D4 is verified
- ✅ Contract UDTv3 at 0x90DE74265a416e1393A450752175AED98fe11517 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x1d8DD27432cC0aCB93B93c4486F46b67E2208359 is verified
- ✅ Unlock source code at 0xe79B93f8E22676774F2A8dAd469175ebd00029FA matches packaged UnlockV13
- ✅ PublicLock source code at 0xc9577b38ADA2B1b251EE99e54cC399027d547B68 matches packaged PublicLockV14
- ✅ Subgraph up and running

We have found the following errors :

- ❌ Contract onKeyPurchaseHook_PASSWORD at 0x936Ed3E71b5990bC9A94074835D08C6ca7bbFad0 is not verified
- ❌ Contract onKeyPurchaseHook_CAPTCHA at 0xaF96721f8ffc136e4C170446E68Dc6744B6Ee4f4 is not verified
- ❌ Unlock owner is not set to the multisig
- ❌ Unlock Proxy Admin owner is not set to the multisig

**Review by julien51 — APPROVED** [review]

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/mainnet.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0xc9577b38ADA2B1b251EE99e54cC399027d547B68 is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0xe79B93f8E22676774F2A8dAd469175ebd00029FA is verified
- ✅ Contract KeyManager at 0x9A1f43090307034DBFBE2ba20320Ce815ff046D4 is verified
- ✅ Contract UDTv3 at 0x90DE74265a416e1393A450752175AED98fe11517 is verified
- ✅ Contract onKeyPurchaseHook_CAPTCHA at 0xaF96721f8ffc136e4C170446E68Dc6744B6Ee4f4 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x1d8DD27432cC0aCB93B93c4486F46b67E2208359 is verified
- ✅ Unlock source code at 0xe79B93f8E22676774F2A8dAd469175ebd00029FA matches packaged UnlockV13
- ✅ PublicLock source code at 0xc9577b38ADA2B1b251EE99e54cC399027d547B68 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the DAO

We have found the following errors :

- ❌ Contract onKeyPurchaseHook_PASSWORD at 0x936Ed3E71b5990bC9A94074835D08C6ca7bbFad0 is not verified




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/mainnet.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0xc9577b38ADA2B1b251EE99e54cC399027d547B68 is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0xe79B93f8E22676774F2A8dAd469175ebd00029FA is verified
- ✅ Contract KeyManager at 0x9A1f43090307034DBFBE2ba20320Ce815ff046D4 is verified
- ✅ Contract UDTv3 at 0x90DE74265a416e1393A450752175AED98fe11517 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x1d8DD27432cC0aCB93B93c4486F46b67E2208359 is verified
- ✅ Unlock source code at 0xe79B93f8E22676774F2A8dAd469175ebd00029FA matches packaged UnlockV13
- ✅ PublicLock source code at 0xc9577b38ADA2B1b251EE99e54cC399027d547B68 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the DAO

We have found the following errors :

- ❌ Contract onKeyPurchaseHook_PASSWORD at 0x936Ed3E71b5990bC9A94074835D08C6ca7bbFad0 is not verified
- ❌ Contract onKeyPurchaseHook_CAPTCHA at 0xaF96721f8ffc136e4C170446E68Dc6744B6Ee4f4 is not verified




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Comment by unlock-deployer** [comment]
### packages/networks/src/networks/mainnet.ts

The setup is successful :

- ✅ all mandatory keys are present
- ✅ Contract PublicLockLatest at 0xc9577b38ADA2B1b251EE99e54cC399027d547B68 is verified
- ✅ Contract PublicLockPrevious at 0xfe9fD6af67E48D9f05Aa88679Ac294E3f28532eE is verified
- ✅ Contract Unlock at 0xe79B93f8E22676774F2A8dAd469175ebd00029FA is verified
- ✅ Contract KeyManager at 0x9A1f43090307034DBFBE2ba20320Ce815ff046D4 is verified
- ✅ Contract UDTv3 at 0x90DE74265a416e1393A450752175AED98fe11517 is verified
- ✅ Contract onKeyPurchaseHook_GUILD at 0x1d8DD27432cC0aCB93B93c4486F46b67E2208359 is verified
- ✅ Unlock source code at 0xe79B93f8E22676774F2A8dAd469175ebd00029FA matches packaged UnlockV13
- ✅ PublicLock source code at 0xc9577b38ADA2B1b251EE99e54cC399027d547B68 matches packaged PublicLockV14
- ✅ Subgraph up and running
- ✅ Unlock ownership correctly set to the DAO

We have found the following errors :

- ❌ Verification failed for onKeyPurchaseHook_PASSWORD at 0x936Ed3E71b5990bC9A94074835D08C6ca7bbFad0: Max calls per sec rate limit reached (5/sec)
- ❌ Verification failed for onKeyPurchaseHook_CAPTCHA at 0xaF96721f8ffc136e4C170446E68Dc6744B6Ee4f4: Max calls per sec rate limit reached (5/sec)




Some additonal warnings  :

- ⚠️ Contract onKeyPurchaseHook_CUSTOM_CONTRACT is missing
- ⚠️ Contract onKeyPurchaseHook_PROMOCODE is missing
- ⚠️ Contract onKeyPurchaseHook_PROMO_CODE_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_PASSWORD_CAPPED is missing
- ⚠️ Contract onKeyPurchaseHook_GITCOIN is missing
- ⚠️ Contract onKeyPurchaseHook_ADVANCED_TOKEN_URI is missing

**Pull request merged**
