### PR TITLE
Hardhat gas reporter

### LINKED ISSUE #7291: Restore gas reporting in smart contract tests
We used to have extensive reporting in the test suite for contracts. Let's restore this.

### PR DESCRIPTION
**Pull request by clemsos**
# Description

Add gas reporting to hardhat tests 

# Issues

Fixes #7291
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Small linting issues but then LG :)

**Review by julien51 — APPROVED** [review]

**Comment by julien51** [comment]
Hey @clemsos feel free to merge when it's been approved :)

**Comment by clemsos** [comment]
@julien51 I dont have write access to the repo so can not merge it myself

**Comment by julien51** [comment]
Weird!

**Comment by julien51** [comment]
Should be fixed. Please confirm by merging ;p

**Pull request merged**
