### PR TITLE
the `/event` route maps to the `/newevent` page

### PR DESCRIPTION
**Pull request by cnasc**
# Description

Just putting this in the wings for when we want to cut over

### CODE REVIEW

**Comment by julien51** [comment]
Awesome! Let's do some thorough testing on some pages like the NFT meetup or the BOSS tickets or the ones for coinfund to make sure they're strictly identical!

**Comment by julien51** [comment]
Would it be worth adding a redirect from `/newevent` to `/event` too for EthWaterloo?

**Comment by julien51** [comment]
I guess that's probably for another PR!

**Comment by cnasc** [comment]
Yeah I think we can normalize the naming in the future

**Pull request merged**
