### PR TITLE
feat(unlock-protocol-com) - about page

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
New About page 

- [x] about page
- [x] about page - mobile
- [x] add all profile pictures
- [x] add all social links/ref

## Desktop 
Screenshot 2022-12-13 at 10 57 30

Screenshot 2022-12-13 at 10 57 42

Screenshot 2022-12-13 at 10 57 58

Screenshot 2022-12-13 at 10 58 11

Screenshot 2022-12-13 at 10 58 22

Screenshot 2022-12-13 at 14 41 48

## Mobile

Screenshot 2022-12-13 at 11 35 22

Screenshot 2022-12-13 at 11 36 18

Screenshot 2022-12-13 at 11 38 17

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
@kalidiagne Pleaase use the correct images for the team members :D

**Comment by kalidiagne** [comment]
> @kalidiagne Pleaase use the correct images for the team members :D

i think we don't have all the images :D 
ill ask to Chiali if the can me help me :D

**Comment by ccarfi** [comment]
@kalidiagne @julien51 had responded via the copy yesterday here:
https://discord.com/channels/462280183425138719/836315312562765855/1052081999508164699

direct link to copy:
https://docs.google.com/spreadsheets/d/1171-4fgG3YYpMq9ovwIM63Y3NHQWdEtqPFyjaYOEYjY/edit#gid=0

my suggestions in the `Revision 1` column

**Comment by kalidiagne** [comment]
Hover effect profile pics 

https://user-images.githubusercontent.com/20865711/207582819-716f47b5-299f-4600-b22c-81e4c9aa83fb.mov

**Comment by julien51** [comment]
@kalidiagne I think there is something odd on the mobile UI: the paragraph should take the whole width?
Screen Shot 2022-12-14 at 8 53 49 AM

**Comment by julien51** [comment]
I am also not a huge fan of the illustrations on the DAO and Protocol sections. What do you think @ChialiT ?

**Comment by kalidiagne** [comment]
> @kalidiagne I think there is something odd on the mobile UI: the paragraph should take the whole width? Screen Shot 2022-12-14 at 8 53 49 AM

@julien51 you are right! fixed and also added the main background image for the main section 



Screenshot 2022-12-14 at 14 58 37

Screenshot 2022-12-14 at 15 02 50

**Comment by ChialiT** [comment]
@kalidiagne can we push a little on the hero section, please?
image

**Comment by kalidiagne** [comment]
> @kalidiagne can we push a little on the hero section, please? image

@ChialiT 

Screenshot 2022-12-14 at 16 29 48

Screenshot 2022-12-14 at 16 29 52

**Review by julien51 — APPROVED** [review]

**Pull request merged**
