### PR TITLE
feat(unlock-app) - replace hero image

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description

**Desktop** 

Screenshot 2023-07-24 at 21 09 59

**Mobile** 

Screenshot 2023-07-24 at 20 36 26

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by ccarfi** [comment]
Screen Shot 2023-07-24 at 2 39 01 PM

looks good on mobile.

on desktop, possible to scale the Dappcon image so the full image fits on the screen? would love to have this part be able to be shown at a typical screen resolution on desktop.
Screen Shot 2023-07-24 at 2 40 32 PM

Screen Shot 2023-07-24 at 2 41 32 PM

**Review by ccarfi — CHANGES_REQUESTED** [review]
please ensure full image shows on desktop view

**Comment by kalidiagne** [comment]
@ccarfi need your approval also to merge this PR

**Comment by ccarfi** [comment]
thanks! will review and approve when it gets to staging.

**Review by ccarfi — APPROVED** [review]

**Pull request merged**
