### PR TITLE
Add Trust Wallet option on paywall screen

### PR DESCRIPTION
**Pull request by vikmeup**
# Description

Fixes: https://github.com/unlock-protocol/unlock/issues/5507

Add [Trust Wallet](https://trustwallet.com) option to get started in paywall screen.

Screen Shot 2019-12-17 at 5 35 38 PM

Screen Shot 2019-12-17 at 5 35 32 PM

Screen Shot 2019-12-17 at 5 38 04 PM

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Very good @vikmeup !

**Comment by julien51** [comment]
Thanks! Let's get this https://github.com/unlock-protocol/unlock/pull/5511 and then we can merge yours ;) Thx!

**Comment by julien51** [comment]
@vikmeup One final push to rebuild (+ re-run snapshots) and you should be all set! We really really appreciate this... thanks!

**Comment by vikmeup** [comment]
@julien51 take a look. Thanks

**Pull request merged**
