### PR TITLE
feat(unlock-app) - update price and duration from manage lock page

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description

**Modal**
Screenshot 2022-09-23 at 19 56 54

**Button**
Screenshot 2022-09-23 at 19 49 00

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Review by searchableguy — APPROVED** [review]
LGTM

**Comment by julien51** [comment]
I think we should distinguish between the 2 things for clarify: one modal to update the duration, and one other modal to update price/currency. 
In the second one, we should let the user change the token as well by re-using the same UI that we use for deploying?

**Comment by searchableguy** [comment]
I think that would be good, yes. 

Allow people to change to erc20 and custom contracts.

**Comment by kalidiagne** [comment]
**Price update**
Screenshot 2022-09-26 at 11 38 24

**Quantity update**
Screenshot 2022-09-26 at 11 53 05

**Actions**
Screenshot 2022-09-26 at 12 15 24

**Comment by kalidiagne** [comment]
I don't see any function inside `unlock-js` that allows currency change, ill add later the function to enable it.
So actually the button to change currency in disabled, but all the login is in place

**Comment by julien51** [comment]
@kalidiagne Instead of adding 2 buttons below that are "out of context", just add the little pencil icon near "Quantity" and "Price" . 

BTW, we should also add let the creator update the duration,

Finally on the price update, please let the user add an ERC20 token address as well... __exactly__ like we do on the lock creation page!

**Comment by kalidiagne** [comment]
**Update duration**
Screenshot 2022-09-26 at 15 44 14

**Edit actions**
Screenshot 2022-09-26 at 15 50 46

**Review by julien51 — APPROVED** [review]

**Pull request merged**
