### PR TITLE
refactoring(unlock-app): Payments pricing

### PR DESCRIPTION
**Pull request by julien51**
# Description

Showing prices again on the Payment screen and improvements in affordability calculation.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by searchableguy** [comment]
Do we have a screenshot of the changes?

**Comment by julien51** [comment]
Screenshot 2023-10-06 at 9 44 09 AM

**Comment by julien51** [comment]
Screenshot 2023-10-06 at 9 44 52 AM

**Review by clemsos — APPROVED** [review]
LG

**Pull request merged**
