### PR TITLE
remove conflicting rule, add eslint-check to paywall

### LINKED ISSUE #2151: eslint/prettier conflicts
running `npm run eslint-check` in `unlock-app` reveals a conflict between eslint and prettier: the `linebreak-style` rule. This should be removed from `.eslintrc`

### PR DESCRIPTION
**Pull request by cellog**
# Description

This PR removes a conflicting rule between eslint and prettier, and may fix the `npm run reformat` issues blocking some PRs

# Issues

Refs #2151

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [X] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by cellog** [comment]
P.S. this doesn't fix the issue, just checked. Someone (probably me :) will need to do a deep dive into prettier-eslint logs to find the rule that is screwing things up

**Comment by julien51** [comment]
I think we should actually rather change the prettier config, rather than the eslint config if you do no mind?

**Comment by cellog** [comment]
https://github.com/prettier/eslint-config-prettier

**Comment by cellog** [comment]
```
arrow-body-style and prefer-arrow-callback
These rules might cause problems if using eslint-plugin-prettier and --fix.

If you use any of these rules together with the prettier/prettier rule from eslint-plugin-prettier, you can in some cases end up with invalid code due to a bug in ESLint’s autofix.

```

I think this is what is causing the problem

**Comment by julien51** [comment]
I think this is noop? It looks like the problem was in fact due to prettier not using the same parser locally and on CI?

Please confirm and close ;)

**Comment by julien51** [comment]
Could you clarify if just adding the prettier rule actually solves the problem?

**Comment by cellog** [comment]
the fix for the blocker is already in master. This fixes a potential conflict between eslint and prettier. Prettier automatically ensures consistency of line endings in every file, but by default it uses the most common line ending (`"auto"`). To force it to use only `LF` as the line endings, we need the setting explicitly set in `.prettierrc`. Once this is done, the eslint rule for line endings becomes superfluous and can be removed. That is what this PR does.

**Comment by julien51** [comment]
> Once this is done, the eslint rule for line endings becomes superfluous and can be removed. 

I'd much rather keep it for now because I feel like it is better to have a "stricter" Eslint should we eventually change our usage of prettier. Could you please update that? Thanks!

**Pull request closed without merging**
