### PR TITLE
feat(websub): Add signature to headers when notifying subscribers

### PR DESCRIPTION
**Pull request by searchableguy**
# Description

Add signature to our headers using the secret from hook. 

The w3c doesn't mandate that we use sha1 but does mention that many implementation use it despite it being vulnerable to maintain compatibility. Do we want to do that or improve on the security there? (I chose the later for this PR). I can do sha1 though.

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Review by julien51 — APPROVED** [review]
I would feel better with some tests here but in the interest of time, I will approve and expect that youll add a few before merging!

**Comment by searchableguy** [comment]
I'm using msw to intercept network request and mock responses from a server as if it is a real subscriber for notify. We could refactor and improve on this approach to test all parts of locksmith later.

**Comment by julien51** [comment]
Hum, I think a better appraoch would be to isolate the signature logic.

**Comment by searchableguy** [comment]
good to go now? @julien51

**Review by julien51 — APPROVED** [review]
Thank you!

**Pull request merged**
