### PR TITLE
feat(ui) - address input refactor

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description

- [x] add debounce 
- [x] add validation for address or ens 
- [x] add support for default value

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
@searchableguy Would you be able to look at this closely please?

**Review by searchableguy — COMMENTED** [review]
I'm not sure approving as it is the right approach. This is getting messier.

**Review by searchableguy — APPROVED** [review]

**Comment by searchableguy** [comment]
Approving so you can continue but this is really more complicated and error prone than it needs to be.

**Comment by kalidiagne** [comment]
> Approving so you can continue but this is really more complicated and error prone than it needs to be.

Component updated, can you please check?

**Review by searchableguy — APPROVED** [review]

**Pull request merged**
