### PR TITLE
Production Deploy

### PR DESCRIPTION
**Pull request by julien51**
Production manual Deploy production-20230712-171039

This is a production deployment. Please treat with great caution!
This deploys the code from master as of commit c584713fb66b8ed6cde9340ab957a669995aae86.

Reviewing code for this Pull Request is not practical, however, you are asked to check wether the current staging environment is stable and could be released. For this, follow these steps:

* [x] The staging environment has been fully deployed
* [x] This pull request has no conflicts with the `production` branch.
* [x] Go to http://staging.unlock-protocol.com/ and ensure that the website loads fine.

## Creator Dashboard
* [x] Click on the "Go to your Dashboard" button and ensure that the dashboard loads as expected
* [x] Create a new Lock (using a test net is the best option) and wait for it to confirm with the right values
* [x] Update the price on this new lock or an older lock
* [x] Enable credit cards on one of your locks
* [x] Withdraw funds on one of the locks

## Paywall
* [x] From the dashboard open the Demo on one of your locks
* [x] Purchase a key to the lock using your crypto wallet
* [x] Make sure the content gets unlocked (is shown)
* [x] Refresh the page and make sure the content is still unlocked

## Purchase URL
* [x] From the dashboard, create a purchase URL (redirect URL does not matter)
* [x] In the purchase URL, configure metadata collection to collect an email address (`"metadataInputs": [ { name: 'Name', type: 'text', required: true } ],`)
* [x] By using a recent lock, enable multiple purchase in the URL (`"maxRecipients": 6`)
* [x] Go through the checkout flow and ensure that it works as expected (data is collected for 2 users + and 2 keys are minted)
* [ ] Use a v9 lock and check if multiple purchase is successful for compatibility. Use lock address:  on network  gnosis.

## Verification 
* [x] Add a separate address as a verifier
* [x] Create QR code for one of the valid NFT you own and check-in using your phone or laptop camera
* [x] Check if metadata is displayed when you are a verifier and check-in is persistent from the members page.

# Payments methods
## Credit Card flow for Unlock User accounts
* [x] Open the demo for a lock that has credit card enabled
* [x] Follow the steps to unlock using a credit card as a new user
* [x] Make sure unlocking works successfuly
* [x] Connect to the keychain using your Unlock credentials
* [x] Ensure the key you just purchased is there

## Swap & purchase
* [x] Update the currency for a lock (eg. USDC) to enable swap & purchase 
* [x] Open the demo for the lock with the updated currency
* [x] Make sure that swap & purchase is enabled as payment method
* [x] Use swap and purchase and make sure that unlocking works successfuly

## Custom credit card price
* [x] Open settings for a lock and go to payments
* [x] Enable custom credit card and set a fixed price
* [x] Go through the checkout flow and ensure that the custom price correctly show as the price for the lock
* [x] Make sure that purchase with custom price works successfuly

### CODE REVIEW

**Review by kalidiagne — DISMISSED** [review]

**Comment by kalidiagne** [comment]
Also cherry-picked the fix for `unlock fees` (https://github.com/unlock-protocol/unlock/commit/22b0df06ece19209e82abf9a7dff31f85541f778)

**Review by kalidiagne — DISMISSED** [review]

**Comment by kalidiagne** [comment]
> LGTM!
> 
> Found this issue on UI #12362

About this issue, here is the PR with fix https://github.com/unlock-protocol/unlock/pull/12363

**Comment by kalidiagne** [comment]
> > LGTM!
> > Found this issue on UI #12362
> 
> About this issue, here is the PR with fix #12363

Cherry-picked to include also this one

**Review by kalidiagne — DISMISSED** [review]

**Comment by searchableguy** [comment]
I will open another one since we have many commits in.

**Pull request closed without merging**
