### PR TITLE
Now deploying the Unlock smart contract when starting in dev mode.

### PR DESCRIPTION
**Pull request by julien51**
We are not compiling the smart contract anymore when starting unlock app, but rather using the packaged version.

Refs #1842

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [X] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
Dammit absolutely not! Thanks for catching this!

**Comment by hardlydifficult** [comment]
Ideally call `initialize` as well, however that is not important for a test environment.

**Comment by julien51** [comment]
@hardlydifficult Please clarify? I thought this was only useful for zos?

Also @akeem I actually forgot a pretty important part (and it's causing the tests to fail!): we cannot use the artifacts directly anymore! I'll push an update.

**Comment by hardlydifficult** [comment]
We only have an initialize method because of zos, but now that it's there - it's an alternative to using the constructor. 

ATM it only sets the owner address (and resets grossNetworkProduct/totalDiscountGranted values but I'll remove these).  So for testing it's not important, but maybe a best practice in case something important is initialized in the initialize function.

https://github.com/unlock-protocol/unlock/blob/master/smart-contracts/contracts/Unlock.sol#L71

**Pull request merged**
