### PR TITLE
More padding around cc field

### PR DESCRIPTION
**Pull request by benwerd**
# Description

Based on a conversation with @cnasc, I've added more padding to the CC form.

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

Screen Shot 2019-07-19 at 12 24 14 PM

### CODE REVIEW

**Comment by cnasc** [comment]
I wonder if we're actually going to need separate components for the settings page and the embed, since I think one should have padding and one shouldn't. Or maybe add the padding in `AccountContent` around the payment details component instead of always having it baked in

**Comment by benwerd** [comment]
Rebased and changed where the padding is applied. PTAL.

Screen Shot 2019-07-29 at 10 29 43 AM
Screen Shot 2019-07-29 at 10 29 16 AM

**Comment by cnasc** [comment]
Make sure to merge this into master instead of the base branch! LGTM

**Comment by benwerd** [comment]
Rebasing is proving a pain, so I'm going to close this and resubmit the changes (which are obvs small) against master.

**Pull request closed without merging**
