### PR TITLE
Testing PR #2026

### PR DESCRIPTION
**Pull request by hardlydifficult**
Testing the Circle CI build with PR #2026 included.

### CODE REVIEW

**Comment by julien51** [comment]
Dammit. Of course external submissions will not be able to use ChromaticQA or netlify to deploy previews. This is annoying.

**Comment by julien51** [comment]
and I am not sure there are workarounds.

**Comment by hardlydifficult** [comment]
My repo still performs a Travis build, as long as that continues to work we can still get feedback that way.  However that's not surfaced in the PR, I'm unsure how we accept PRs from external contributors... unless maybe a team member clones the branch and resubmits.

**Comment by hardlydifficult** [comment]
Or we could just note which tests are expected to fail.  The app tests are running.  

If we go that route maybe add a comment to the PR template so people don't spin cycles investigating this.

**Comment by julien51** [comment]
Yeah, I think maybe we'll disable chromaticqa for external same with draft deploys for Netlify.

**Comment by julien51** [comment]
@cellog messaged the ChromaticQA support to see what can be done here.

**Comment by julien51** [comment]
Ok, ChromaticQA should now run just fine on all PRs (including forked ones!).
Next: detecting of `$CIRCLE_PR_USERNAME` is set and not deploying to netlify if it is.

**Comment by julien51** [comment]
Hey! do you mind rebasing now to see if this runs?

**Comment by hardlydifficult** [comment]
Rebased.  Fingers crossed.

**Comment by hardlydifficult** [comment]
Looks good @julien51 
Closing.

**Pull request closed without merging**
