### PR TITLE
feat(unlock-app) - replace radiogroup in create lock form

### PR DESCRIPTION
**Pull request by kalidiagne**
# Description
Replace radio group to fix UX issue and technical problem with RadioGroup component: 

fixs:
- The radio button for input selection is hard to use on mobile as well as on desktop. 
- You need to click it twice (one to select and the other to actually start typing).

Screenshot 2022-09-29 at 18 28 40

Screenshot 2022-09-29 at 18 37 28

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by kalidiagne** [comment]
Ill do some more tests before changing to `Ready to review`

**Review by searchableguy — APPROVED** [review]

**Comment by julien51** [comment]
Could you also replace on the airdrop form?

**Comment by julien51** [comment]
And the modals to change duration, pricem supply.... etc

**Comment by kalidiagne** [comment]
> And the modals to change duration, pricem supply.... etc

Screenshot 2022-09-29 at 22 15 48

Screenshot 2022-09-29 at 23 08 32

Screenshot 2022-09-29 at 23 21 21

**Comment by kalidiagne** [comment]
Added default value for edit modal

**Pull request merged**
