### PR TITLE
Renovatebot configuration

### PR DESCRIPTION
**Pull request by hardlydifficult**
# Description

Configuration for Renovatebot, an alternative to Greenkeeper.  It is also free for open-source projects.

The proposed configuration here will:
 - Update once per-month, the 1st between midnight and 3am.
 - Group similar PRs (e.g. update all eslint at once)
 - Pin versions

Let me know if you want to tweak these rules first.  e.g. maybe weekly at first? or don't pin?

There are plenty of other options available we could consider, plus they support updating Docker and Circle config we could consider using.  https://renovatebot.com/docs/

We'll need to turn Greenkeeper off.  Once this is merged, we can flip the bot on. Just click 'install' here https://github.com/marketplace/renovate

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [x] This PR only contains configuration changes (package.json, etc.)
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [ ] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Comment by julien51** [comment]
So, is there a way to manually trigger it too? There are updates which are really cool to get, such as the one to `unlock-js`...

**Comment by hardlydifficult** [comment]
Not manually, but we can create a group which runs on a different schedule.  I'll change it so `unlock-js` updates asap and we can add to that list as appropriate

**Comment by hardlydifficult** [comment]
Updated @julien51 .  Let me know if there's anything else

Will need to try the bot to be sure it's working as expected, I'm not sure we can validate the config another way

**Comment by hardlydifficult** [comment]
@julien51 need the thumbs up still.  I also added deleting the greenkeeper config to the PR, i think that's enough to stop that bot.

Feel free to merge this yourself.  Once merged, click install here: https://github.com/marketplace/renovate

**Pull request merged**
